// Generated by toolchain/translate/generate_copywriting_localizations.py.
// Edit Copywriting or the generator instead of changing keys by hand.

abstract final class CopywritingStringsEs {
  static const Map<String, String> values = <String, String>{
    'security_notifications': 'Notificaciones',
    'security_collections': 'Colecciones',
    'security_feedback': 'Comentarios',
    'security_about_her': 'Sobre ella',
    'security_account_Deletion': 'Eliminación de cuenta',
    'security_add_rounds': 'Agregar rondas',
    'security_all_Gender': 'Todos los géneros',
    'security_appears_exclusively_in_your_character__s_public_profile_This_biographical_information_will_not_be_utilized_in_generation_prompts_or_influence_behavioral_patterns_':
        'Aparece exclusivamente en el perfil público de tu personaje. Esta información biográfica no se utilizará en indicaciones de generación ni influirá en patrones de comportamiento.',
    'security_are_you_sure_you_want_to_delete_your_account_':
        '¿Estás seguro de que quieres eliminar tu cuenta?',
    'security_are_you_sure_you_want_to_log_out_':
        '¿Está seguro de que desea cerrar sesión?',
    'security_audio_Library': 'Biblioteca de audio',
    'security_audio_input_is_too_short_to_send_':
        'La entrada de audio es demasiado corta para enviarla.',
    'security_avatar_upload_failed__please_try_again_later_':
        'Error al cargar el avatar. Vuelve a intentarlo más tarde.',
    'security_avatar_uploaded': 'avatar subido',
    'security_birth_date': 'Fecha de nacimiento',
    'security_by_clicking_Security_security_Subscribe__you_will_be_charged__and_your_subscription_will_automatically_renew_at_the_same_price_and_duration_until_canceled_through_PlayStore_settings__By_proceeding__you_agree_to_our_terms_':
        'Al hacer clic en Security.security_Subscribe, se le cobrará y su suscripción se renovará automáticamente al mismo precio y duración hasta que se cancele a través de la configuración de PlayStore. Al continuar, aceptas nuestros términos.',
    'security_call_Duration': 'Duración de la llamada',
    'security_cannot_get_information__please_retry_later':
        'No se puede obtener información, vuelva a intentarlo más tarde.',
    'security_cannot_get_physique_details__please_retry_later':
        'No se pueden obtener detalles físicos. Vuelva a intentarlo más tarde.',
    'security_cannot_open_date_picker__please_retry_later':
        'No se puede abrir el selector de fechas. Vuelva a intentarlo más tarde.',
    'security_click_to_add': 'Haga clic para agregar',
    'security_click_to_play': 'Haz clic para jugar',
    'security_coin_balance': 'Saldo de monedas',
    'security_connecting___': 'Conectando...',
    'security_copyright_Agreement': 'Acuerdo de derechos de autor',
    'security_create_My_Character': 'Crear mi personaje',
    'security_create_Now': 'Crear ahora',
    'security_create_an_account': 'Crea una cuenta',
    'security_current_device_not_support__try_restart_app_':
        'El dispositivo actual no es compatible, intente reiniciar la aplicación.',
    'security_defines_the_conversational_patterns_between_you_and_your_character__This_crucial_setting_determines_how_your_character_formulates_responses_and_maintains_personality_consistency_':
        'Define los patrones de conversación entre tú y tu personaje. Esta configuración crucial determina cómo tu personaje formula respuestas y mantiene la coherencia de su personalidad.',
    'security_delete_account_': '¿Eliminar cuenta?',
    'security_deleting___': 'Eliminando...',
    'security_describe_the_conversation_scenario_and_involved_characters_':
        'Describe el escenario de la conversación y los personajes involucrados.',
    'security_describe_the_issue': 'Describe el problema',
    'security_dialogue_Style': 'Estilo de diálogo',
    'security_edit_information': 'Editar información',
    'security_enter_verification_code': 'Ingrese el código de verificación',
    'security_entry_your_email': 'Introduce tu correo electrónico',
    'security_expires_on': 'Expira el',
    'security_failed_to_follow': 'No se pudo seguir',
    'security_failed_to_load_subscription_data':
        'No se pudieron cargar los datos de suscripción',
    'security_failed_to_process_subscription__please_try_again_later_':
        'No se pudo procesar la suscripción, inténtelo nuevamente más tarde.',
    'security_failed_to_record_audio__please_try_again':
        'No se pudo grabar el audio, inténtelo de nuevo',
    'security_failed_to_send_gift': 'No se pudo enviar el regalo',
    'security_failed_to_unfollow': 'No se pudo dejar de seguir',
    'security_failed_to_update__please_retry_later':
        'No se pudo actualizar, vuelva a intentarlo más tarde',
    'security_feelie_Pro': 'Feelie Pro',
    'security_fill_in_your_introduction___': 'Complete su introducción...',
    'security_following_the_regeneration_process__you_ll_receive_a_brand_new_image__You_are_also_welcome_to_revisit_the_images_you_created_earlier__Are_you_ready_to_move_forward_':
        'Después del proceso de regeneración, recibirás una imagen completamente nueva. También puedes volver a visitar las imágenes que creaste anteriormente. ¿Estás listo para seguir adelante?',
    'security_for_example___On_the_moonlit_balcony_of_a_neo___Victorian_mansion__an_ethereal_woman_with_bright_blue_hime___cut_hair':
        'Por ejemplo, "En el balcón iluminado por la luna de una mansión neovictoriana, una mujer etérea con hime azul brillante - cabello cortado',
    'security_gem_balance': 'Saldo de gemas',
    'security_generating_in_progress': 'Generando en progreso',
    'security_generating___': 'Generando...',
    'security_get_full_access_': '¡Obtén acceso completo!',
    'security_hold_to_talk': 'Espera para hablar',
    'security_how_would_you_like_OC_to_address_you_':
        '¿Cómo le gustaría que OC se dirigiera a usted?',
    'security_image_Prompt': 'Mensaje de imagen',
    'security_information_updated_': 'Información actualizada.',
    'security_insufficient_balance_': 'Saldo insuficiente.',
    'security_interrupt_AI': 'Interrumpir la IA',
    'security_loading___': 'Cargando...',
    'security_log_out': 'Finalizar la sesión',
    'security_logging_in___': 'Iniciando sesión...',
    'security_master_name_must_be_2_24_characters_in_length':
        'El nombre maestro debe tener entre 2 y 24 caracteres de longitud',
    'security_modify_Now': 'Modificar ahora',
    'security_name_your_character': 'Nombra tu personaje',
    'security_network_error': 'error de red',
    'security_network_error__please_try_again_later':
        'Error de red, inténtelo de nuevo más tarde',
    'security_network_exception__please_try_again_later':
        'Excepción de red, inténtelo de nuevo más tarde',
    'security_no_chat_partner_has_been_initiated_yet':
        'Aún no se ha iniciado ningún compañero de chat',
    'security_no_companions_yet': 'Aún no hay compañeros',
    'security_no_data': 'Sin datos',
    'security_no_user_information__getting_back___':
        'Sin información de usuario, volviendo...',
    'security_notice__Everything_AI_says_is_made_up':
        'Aviso: todo lo que dice la IA es inventado',
    'security_obtain_code': 'Obtener código',
    'security_platform_not_supported_': 'Plataforma no compatible.',
    'security_please_agree_to_the_terms_and_conditions':
        'Por favor acepta los términos y condiciones.',
    'security_please_select_a_product_to_recharge_':
        'Por favor seleccione un producto para recargar.',
    'security_premium_Benefits_for_Audio__unlimited':
        'Beneficios Premium para Audio, ilimitados',
    'security_prior_to_the_creation_process__please_review_our':
        'Antes del proceso de creación, revise nuestra',
    'security_privacy_Policy': 'política de privacidad',
    'security_privacy_policy': 'Política de privacidad',
    'security_pro_Free': 'Pro Gratis',
    'security_pro_only': 'Sólo profesional',
    'security_purchase_done': 'Compra realizada',
    'security_purchased_Success': 'Éxito comprado',
    'security_purchasing___': 'Adquisitivo...',
    'security_recharge_failed_': 'La recarga falló.',
    'security_regeneration_Tips': 'Consejos de regeneración',
    'security_release_Cancel': 'Liberar Cancelar',
    'security_release_Send': 'Liberar Enviar',
    'security_role_image': 'Imagen de rol',
    'security_sF_Pro': 'SF Pro',
    'security_sF_Pro_bold': 'SF Pro bold',
    'security_select_from_gallery': 'Seleccionar de la galería',
    'security_select_from_the_album': 'Seleccionar del álbum',
    'security_selected_date_is_out_of_range_':
        'La fecha seleccionada está fuera de rango.',
    'security_send_failed__please_try_again_later':
        'Error al enviar, inténtelo de nuevo más tarde',
    'security_send_message__reply_by_AI': 'Enviar mensaje, responder por IA',
    'security_sending___': 'Envío...',
    'security_sign_in_with_Apple': 'Iniciar sesión con Apple',
    'security_sign_in_with_E_mail': 'Iniciar sesión con correo electrónico',
    'security_start_create': 'Empezar a crear',
    'security_submitted_successfully': 'Enviado exitosamente',
    'security_supply_detailed_information_about_the_image__such_as_the_clothing_worn__facial_features__and_actions_':
        'Proporcione información detallada sobre la imagen, como la ropa usada, los rasgos faciales y las acciones.',
    'security_take_it_with_camera': 'Tómalo con cámara',
    'security_terms_of_Service': 'Términos de servicio',
    'security_terms_of_service': 'Términos de servicio',
    'security_the_OC_will_address_you_by_the_name_you_enter_':
        'El OC se dirigirá a usted por el nombre que ingrese.',
    'security_the_character_creation_is_still_ongoing__Leaving_at_this_moment_will_forfeit_the_progress_made_so_far__Are_you_sure_you_want_to_go_back_':
        'La creación del personaje aún está en curso. Salir en este momento perderá el progreso realizado hasta ahora. ¿Estás seguro de que quieres volver?',
    'security_the_uploaded_image_serves_as_a_reference_for_facial_features_and_style_elements':
        'La imagen cargada sirve como referencia para rasgos faciales y elementos de estilo.',
    'security_turn_on_the_camera': 'Enciende la cámara',
    'security_unable_to_get_recharge_service__please_retry_later_':
        'No se puede obtener el servicio de recarga, vuelva a intentarlo más tarde.',
    'security_unknown_error__please_upload_again_':
        'Error desconocido, suba nuevamente.',
    'security_unlock_Audio': 'Desbloquear audio',
    'security_unlock_Image': 'Desbloquear imagen',
    'security_unlock_Video': 'Desbloquear vídeo',
    'security_updating_information___': 'Actualizando información...',
    'security_upload_failed__please_try_again_later':
        'La carga falló, inténtalo de nuevo más tarde.',
    'security_uploading_new_avatar___': 'Subiendo nuevo avatar...',
    'security_you_have_muted': 'has silenciado',
    'security_supply_detailed_information_about_the_image__such_as_the_clothing_worn__facial_features__and_actions__For_example___On_the_moonlit_balcony_of_a_neo___Victorian_mansion__an_ethereal_woman_with_bright_blue_hime___cut_hair_leans_against_the_railing__Her_khaki_backless_sweater_flutters_gently_in_the_breeze_as_she_turns_to_look_at_the_viewer_with_an_otherworldly_serenity__':
        'Proporcione información detallada sobre la imagen, como la ropa usada, los rasgos faciales y las acciones. Por ejemplo, "En el balcón iluminado por la luna de una mansión neovictoriana, una mujer etérea con el pelo cortado a hime de un azul brillante se apoya en la barandilla. Su suéter caqui sin espalda ondea suavemente con la brisa mientras se gira para mirar al espectador con una serenidad de otro mundo".',
    'security_cannot_download_source__please_try_again_later':
        'No se puede descargar la fuente, inténtalo de nuevo más tarde.',
    'security_if_you_sign_in__you_agree_to': 'Si inicias sesión, aceptas',
    'security_send_me_a_picture': 'envíame una foto',
    'security_send_me_a_video': 'Envíame un vídeo',
    'security_and_indicate_your_consent_': 'e indicar su consentimiento.',
    'security_consuming_props_during_call':
        'Consumir accesorios durante la llamada.',
    'security_no_more_companions_to_load_': 'No más compañeros para cargar.',
    'security_per_minute': 'por minuto',
    'security_edit': 'Editar',
    'security_video_Call': 'Videollamada',
    'security_i_am_listening___': 'estoy escuchando...',
    'security_i_am_thinking___': 'Estoy pensando...',
    'security_audio_Call': 'llamada de audio',
    'security_canceled_by_caller': 'Cancelado por la persona que llama',
    'security_no_answer__please_try_again_later':
        'No hay respuesta, por favor intenta nuevamente más tarde.',
    'security_no_favorites_yet__go_and_follow_some_people_':
        'Aún no hay favoritos, ¡ve y sigue a algunas personas!',
    'security_benefits_Usage_Detail': 'Detalle de uso de beneficios',
    'security_chat_beyond_reality__role_play_without_limits':
        'Chat más allá de la realidad, juego de roles sin límites',
    'security_please_grant_camera_permission':
        'Por favor conceda permiso a la cámara',
    'security_please_grant_microphone_permission':
        'Por favor conceda permiso al micrófono',
    'security_unlocking_for_free_': '¡Desbloqueo gratis!',
    'security_you__re_now_a_premium_member__nYour_benefits_are_unlocked__nExplore_your_new_perks_':
        '¡Ahora eres miembro premium!\\nTus beneficios están desbloqueados.\\n¡Explora tus nuevos beneficios!',
    'security_by_clicking_subscribe__you_will_be_charged__and_your_subscription_will_automatically_renew_at_the_same_price_and_duration_until_canceled_through_App_Store_settings__By_proceeding__you_agree_to_our_terms_':
        'Al hacer clic en suscribirse, se le cobrará y su suscripción se renovará automáticamente al mismo precio y duración hasta que se cancele a través de la configuración de la App Store. Al continuar, aceptas nuestros términos.',
    'security_daily_Task': 'Tarea diaria',
    'security_premium_Only': 'Sólo premium',
    'security_introduction': 'Introducción',
    'security_premium_Free': 'Prima Gratis',
    'security_an_error_occurred__please_try_again_later_':
        'Se produjo un error, inténtelo nuevamente más tarde.',
    'security_product_id_not_found__please_try_again_later':
        'No se encontró la identificación del producto, inténtelo de nuevo más tarde.',
    'security_call_wasn__t_answered': 'La llamada no fue respondida',
    'security_cancelled_by_Caller': 'Cancelado por la persona que llama',
    'security_consuming_gems_during_call': 'Consumir gemas durante la llamada',
    'security_ending___': 'Final...',
    'security_free_Call': 'llamada gratis',
    'security_not_enough_gems__please_recharge':
        'No hay suficientes gemas, por favor recarga',
    'security_send_a_message_': 'Enviar un mensaje…',
    'security_free_for_first': 'Gratis por primera vez',
    'security_error__max_should_not_be_a_negative_number_or_zero':
        'Error, max no debe ser un número negativo o cero',
    'security_error__min_is_greater_than_or_equal_to_max':
        'Error, el mínimo es mayor o igual que el máximo',
    'security_invites_you': 'te invita',
    'security_aD_Free': 'Anuncio gratuito',
    'security_enter_your_image_prompt__e_g__A_girl__sitting_on_a_bench___':
        'Ingrese su mensaje de imagen, p. Una niña, sentada en un banco...',
    'security_failed_to_grant_coin__Please_try_again_later_':
        'No se pudo otorgar moneda. Inténtelo de nuevo más tarde.',
    'security_failed_to_unlock_resource__Please_try_again_later_':
        'No se pudo desbloquear el recurso. Inténtelo de nuevo más tarde.',
    'security_image_prompt_cannot_be_empty':
        'El mensaje de imagen no puede estar vacío',
    'security_images_you_like': 'Imágenes que te gustan',
    'security_please_select_at_least_one_prompt':
        'Por favor seleccione al menos un mensaje',
    'security_signing_in___': 'Iniciando sesión...',
    'security_all_Chat': 'Todo el chat',
    'security_chat_Models': 'Modelos de chat',
    'security_chat_Now': 'Chatear ahora',
    'security_clear_Chat_History': 'Borrar historial de chat',
    'security_connect_with_everyone_in_one_place':
        'Conéctate con todos en un solo lugar',
    'security_contact_us_for_support_': 'Contáctenos para obtener ayuda.',
    'security_delete_Message': 'Eliminar mensaje',
    'security_design_your_own_unique_character_and_bring_it_to_life_':
        'Diseña tu propio personaje único y dale vida.',
    'security_group_Chat': 'Chat grupal',
    'security_limited_Free': 'Gratis limitado',
    'security_mark_all_as_read': 'Marcar todo como leído',
    'security_message_Setting': 'Configuración de mensajes',
    'security_message_setting': 'Configuración de mensajes',
    'security_reset_Success_': '¡Restablecer éxito!',
    'security_rewind_to_here': 'Rebobinar hasta aquí',
    'security_she_will_forget_conversation_history_with_you_':
        '¡Ella olvidará el historial de conversaciones contigo!',
    'security_shield_Real__s_Messages': 'Proteger los mensajes de Real',
    'security_soulink_Team': 'Equipo Soulink',
    'security_switch_Failed': 'Cambio fallido',
    'security_switch_Succeed_enjoy_your_chat':
        'Cambia con éxito, disfruta de tu chat',
    'security_switch_the_Model': 'Cambiar el modelo',
    'security_contact_us': 'Contáctenos',
    'security_iAP_Service_Not_Available': 'Servicio IAP no disponible',
    'security_iAP_not_available__restart_the_app_and_try_again_':
        'IAP no está disponible, reinicie la aplicación y vuelva a intentarlo.',
    'security_item_info_error': 'Error de información del artículo',
    'security_monthly_Premium': 'Prima Mensual',
    'security_no_recharge_item_available__try_again_later':
        'No hay ningún elemento de recarga disponible, inténtalo de nuevo más tarde',
    'security_payment_failed': 'Pago fallido',
    'security_payment_successful': 'Pago exitoso',
    'security_purchase_successful': 'Compra exitosa',
    'security_receipt_Not_Available': 'Recibo no disponible',
    'security_special_Offer': 'Oferta especial',
    'security_weekly_Premium': 'Prima Semanal',
    'security_yearly_Premium': 'Prima anual',
    'security_about_AI_MODE': 'Acerca del MODO AI',
    'security_about_Me': 'Acerca de mí',
    'security_add_Group_Member': 'Agregar miembro del grupo',
    'security_add_New_Group_Member': 'Agregar nuevo miembro del grupo',
    'security_are_you_sure_you_want_to_disband_this_group__This_action_cannot_be_undone__and_all_members_will_be_removed_':
        '¿Estás seguro de que quieres disolver este grupo? Esta acción no se puede deshacer y todos los miembros serán eliminados.',
    'security_auto___enabled__The_mentioned_member_s__will_reply_your_message_':
        'Auto @ habilitado. Los miembros mencionados responderán su mensaje.',
    'security_click_anywhere_to_continue___':
        'Haga clic en cualquier lugar para continuar...',
    'security_congratulations__You_got_a_new_MODE__enjoy_it_':
        '¡Felicidades! Tienes un nuevo MODO, disfrútalo.',
    'security_contact_List': 'Lista de contactos',
    'security_create_Group': 'Crear grupo',
    'security_dating_Game': 'Juego de citas',
    'security_disband_Group': 'Disolver grupo',
    'security_disband_Group_': '¿Disolver el grupo?',
    'security_download_failed__please_retry_later_':
        'La descarga falló, ¡vuelve a intentarlo más tarde!',
    'security_edit_Group_Name': 'Editar nombre de grupo',
    'security_edit_Group_Scenario': 'Editar escenario de grupo',
    'security_enter_the_Group_Scenario': 'Ingrese al escenario grupal',
    'security_enter_the_group_name': 'Introduzca el nombre del grupo',
    'security_error_occurred__please_try_again':
        'Se produjo un error, inténtalo de nuevo.',
    'security_go_Play': 'ir a jugar',
    'security_group_Info': 'Información del grupo',
    'security_group_Member': 'Miembro del grupo',
    'security_group_Name': 'Nombre del grupo',
    'security_group_Owner': 'Propietario del grupo',
    'security_group_Scenario': 'Escenario de grupo',
    'security_in_Use': 'En uso',
    'security_in_use': 'En uso',
    'security_level_Up_': '¡Elevar a mismo nivel!',
    'security_my_OCs': 'Mis OC',
    'security_not_enough_balance': 'Saldo insuficiente',
    'security_please_agree_to_the_terms_below_first_':
        'Primero acepte los términos a continuación.',
    'security_popular_Search': 'Búsqueda Popular',
    'security_recent_Search': 'Búsqueda reciente',
    'security_search_Failed': 'Búsqueda fallida',
    'security_search_Users_by_ID_or_Name': 'Buscar usuarios por ID o nombre',
    'security_some_error_occur__please_retry_later_':
        'Se produjo algún error. ¡Vuelva a intentarlo más tarde!',
    'security_some_error_occurred__try_again_later_':
        'Se produjo algún error, inténtelo nuevamente más tarde.',
    'security_some_error_occurred__Please_try_again_later_':
        'Se produjo algún error. Inténtelo de nuevo más tarde.',
    'security_start_Game': 'Iniciar juego',
    'security_switch_Succeed__enjoy_your_chat':
        'Switch Succeed, disfruta tu chat',
    'security_switch_to_Chat': 'Cambiar a chat',
    'security_take_a_look__': 'Échale un vistazo >',
    'security_the_MODE_will_only_take_effect_after_you_have_acquired_this_character__Continue_purchasing_':
        'El MODO sólo tendrá efecto después de que hayas adquirido este personaje. ¿Continuar comprando?',
    'security_the_muted_member_will_not_reply_your_message':
        'El miembro silenciado no responderá a tu mensaje.',
    'security_this_member_is_deactivated_': 'Este miembro está desactivado.',
    'security_this_member_is_expired_': 'Este miembro ha caducado.',
    'security_time_limit': 'límite de tiempo',
    'security_try_it': 'Pruébalo',
    'security_unlock_conditions_not_met__Upgrade_your_level_now_':
        'Condiciones de desbloqueo no cumplidas. ¡Mejora tu nivel ahora!',
    'security_unlock_tips': 'Consejos para desbloquear',
    'security_your_reward': 'tu recompensa',
    'security_edit_My_Character': 'Editar mi personaje',
    'security_message_Settings': 'Configuración de mensajes',
    'security_no_datas__click_to_retry_':
        'No hay datos, haga clic para volver a intentarlo.',
    'security_start_Chat': 'Iniciar chat',
    'security_send_a_message___': 'Enviar un mensaje...',
    'security_send_me_a_pic_with_you_tucking_hair_behind_ear_in_sunset__Send_me_a_pic_with_you_touching_flower_petals_at_dusk__Send_me_a_pic_with_you_holding_teacup_by_rain_window__Send_me_a_pic_with_you_twirling_silk_scarf_by_the_lake__Send_me_a_pic_with_you_adjusting_shoelace_in_sunlight__Send_me_a_pic_with_you_skimming_calm_fountain_surface__Send_me_a_pic_with_you_wrapping_shawl_on_the_balcony':
        'Envíame una foto contigo metiendo el cabello detrás de la oreja al atardecer||Envíame una foto contigo tocando pétalos de flores al anochecer||Envíame una foto contigo sosteniendo una taza de té junto a la ventana de lluvia||Envíame una foto contigo girando un pañuelo de seda junto al lago||Envíame una foto contigo ajustando el cordón de los zapatos a la luz del sol||Envíame una foto contigo rozando la tranquila superficie de la fuente||Envíame una foto contigo envolviendo el chal en el balcón',
    'security_nice_to_meet_you_': '¡Encantado de conocerlo!',
    'security_sign_in_with_Google': 'Iniciar sesión con Google',
    'security_failed_to_save__image_URL_is_empty':
        'No se pudo guardar, la URL de la imagen está vacía',
    'security_failed_to_save__try_again_later':
        'No se pudo guardar, inténtalo de nuevo más tarde',
    'security_failed_to_save__try_again_later_Data_Empty_':
        'No se pudo guardar, inténtalo de nuevo más tarde[Datos vacíos]',
    'security_saved_successfully': 'Guardado exitosamente',
    'security_saving___': 'Ahorro...',
    'security_scenario': 'Guión',
    'security_are_you_sure_you_want_to_block_this_user_':
        '¿Estás seguro de que quieres bloquear a este usuario?',
    'security_bock_Messages_from_Strangers': 'Bock Mensajes de extraños',
    'security_aI_Writer': 'Escritor de IA',
    'security_permission_settings': 'Configuración de permisos',
    'security_the_existing_filled_content_will_be_replaced_by_the_template_content_and_cannot_be_undone_':
        'El contenido completo existente será reemplazado por el contenido de la plantilla y no se puede deshacer.',
    'security_what_should_AI_call_you': '¿Cómo debería llamarte la IA?',
    'security_generation_failed__please_try_again_later_':
        'La generación falló, inténtalo de nuevo más tarde.',
    'security_copied_ID_to_clipboard':
        'Copia de identificación al portapapeles',
    'security_character_name_must_be_at_least_3_letters_':
        'El nombre del personaje debe tener al menos 3 letras.',
    'security_more_Details': 'Más detalles',
    'security_feedback_Log': 'Registro de comentarios',
    'security_image_is_Not_ready__please_try_again_later_':
        'La imagen no está lista, inténtalo de nuevo más tarde.',
    'security_not_approved': 'No aprobado',
    'security_under_review': 'En revisión',
    'security_upload_Log_success': 'Carga exitosa del registro',
    'security_about_Soulink': 'Acerca de Soulink',
    'security_are_you_sure_': '¿Está seguro?',
    'security_character_is_private': 'El personaje es privado.',
    'security_complete_tasks_to_get_rewards':
        'Completa tareas para obtener recompensas.',
    'security_cost_Trial_Card': 'Tarjeta de prueba de costos',
    'security_create_Character': 'Crear personaje',
    'security_create_Moment': 'Crear momento',
    'security_create_an_image_with_Generator': 'Crear una imagen con Generador',
    'security_currently_owns_': 'Actualmente posee:',
    'security_daily_post_limit_exceeded':
        'Se superó el límite de publicaciones diarias',
    'security_describe_what_you_want__e_g___A_barista_wipes_the_counter_of_a_small_caf__by_the_river__steam_rising_from_coffee_cups__boats_passing_slowly_outside_the_window__a_cat_napping_on_a_nearby_chair_':
        'Describe lo que quieres, por ejemplo, un barista limpia el mostrador de una pequeña cafetería junto al río, el vapor que sale de las tazas de café, los barcos que pasan lentamente por la ventana, un gato durmiendo una siesta en una silla cercana.',
    'security_don_t_remind_me_again': 'No me lo vuelvas a recordar',
    'security_enable_this_option_to_allow_the_AI_to_generate_image_galleries_based_on_your_information_':
        'Habilite esta opción para permitir que la IA genere galerías de imágenes basadas en su información.',
    'security_enter_the_Description': 'Ingrese la descripción',
    'security_exit_Video_Matching_': '¿Salir de la coincidencia de vídeos?',
    'security_failed_Generate': 'Generación fallida',
    'security_failed_reload': 'Recarga fallida',
    'security_first_message_from_your_character__It_will_help_the_chat_get_off_to_a_better_start_':
        'Primer mensaje de tu personaje. Ayudará a que el chat tenga un mejor comienzo.',
    'security_for_You': 'Para ti',
    'security_generate_Video': 'Generar vídeo',
    'security_generate_config_loading': 'Generar carga de configuración',
    'security_generate_for_Moment': 'Generar por momento',
    'security_generate_video': 'Generar vídeo',
    'security_generating_Gallery': 'Generando galería',
    'security_get_30s_Free_Trial': 'Obtenga una prueba gratuita de 30 años',
    'security_go_Setting': 'Ir a configuración',
    'security_grants_the_first_30_seconds_of_the_call_for_free__After_that__gems_will_be_charged_':
        'Otorga los primeros 30 segundos de la llamada de forma gratuita. Después de eso, se cargarán gemas.',
    'security_i_understand': 'Entiendo',
    'security_image_details__facial_features__clothing':
        'Detalles de la imagen, rasgos faciales, vestimenta.',
    'security_initial_Message': 'Mensaje inicial',
    'security_invites_you_to_video_calling_': 'Te invita a una videollamada...',
    'security_lets_you_make_calls_without_spending_gems_':
        'Te permite realizar llamadas sin gastar gemas.',
    'security_mM_dd_HH_mm': 'MM-dd HH:mm',
    'security_just_now': 'Ahora mismo',
    'security_one_minute_ago': 'Hace 1 minuto',
    'security_minutes_ago': 'Hace {count} minutos',
    'security_one_hour_ago': 'Hace 1 hora',
    'security_hours_ago': 'Hace {count} horas',
    'security_one_day_ago': 'Hace 1 día',
    'security_days_ago': 'Hace {count} días',
    'security_one_week_ago': 'Hace 1 semana',
    'security_weeks_ago': 'Hace {count} semanas',
    'security_maximum_limit_exceeded': 'Límite máximo excedido',
    'security_no_report_reasons_available':
        'No hay motivos de informe disponibles',
    'security_operation_failed': 'Operación fallida',
    'security_permission_required': 'Permiso requerido',
    'security_please_allow_access_to_the_camera_in_the_settings':
        'Por favor permita el acceso a la cámara en la configuración.',
    'security_please_allow_access_to_the_microphone_in_the_settings':
        'Por favor permita el acceso al micrófono en la configuración.',
    'security_please_input_description': 'Por favor ingrese la descripción',
    'security_please_select_a_character_first':
        'Por favor seleccione un personaje primero',
    'security_post_As': 'Publicar como',
    'security_post_successful': 'Publicar con éxito',
    'security_post_updates_for_your_character_and_bring_every_moment_of_their_story_to_life_':
        '¡Publica actualizaciones para tu personaje y da vida a cada momento de su historia!',
    'security_post_your_reply': 'Publica tu respuesta',
    'security_report_Success_': '¡Informe éxito!',
    'security_select_From_Chat_History_Album':
        'Seleccionar del álbum del historial de chat',
    'security_select_Image': 'Seleccionar imagen',
    'security_select_a_Character': 'Selecciona un personaje',
    'security_start_Match': 'Iniciar partido',
    'security_switching_characters_will_clear_the_current_content':
        'Cambiar de personaje borrará el contenido actual',
    'security_the_user_has_been_matched__and_the_other_party_accepts_and_enters_the_video_call':
        'El usuario ha sido emparejado y la otra parte acepta e ingresa a la videollamada.',
    'security_this_moment_does_not_meet_community_requirements__please_edit':
        'Este momento no cumple con los requisitos de la comunidad, edite',
    'security_translation_failure_': 'Error de traducción...',
    'security_you_need_to_have_your_own_role_to_post___nGo_create_a_character':
        '¡Necesitas tener tu propio rol para publicar! \\nVe a crear un personaje',
    'security_you_re_now_using_your_trial_card_or_available_call_time___whichever_applies_':
        'Ahora estás usando tu tarjeta de prueba o el tiempo de llamada disponible, lo que corresponda.',
    'security_please_grant_storage_permission':
        'Por favor conceda permiso de almacenamiento',
    'security_brush_a_strand_of_hair_back_gently__eyes_soft_as_you_gaze_straight_at_me_':
        'Peina suavemente un mechón de cabello hacia atrás, con los ojos suaves mientras me miras directamente.',
    'security_hold_a_book_loosely_in_your_hand__flipping_a_page_slowly_as_you_glance_up_':
        'Sostén un libro sin apretar en tu mano y pasa una página lentamente mientras miras hacia arriba.',
    'security_hold_a_cup_of_warm_drink__blowing_on_it_softly_before_taking_a_small_sip_':
        'Sostenga una taza de bebida caliente y sople suavemente antes de tomar un pequeño sorbo.',
    'security_lean_against_a_bar_counter__drink_in_hand__shoulders_loose_':
        'Apóyate en la barra de un bar, bebida en mano y hombros relajados.',
    'security_lean_against_a_bookshelf__one_hand_brushing_the_spines__calm_and_unhurried_':
        'Recuéstese contra una estantería, rozando con una mano los lomos, tranquilo y sin prisas.',
    'security_lean_against_a_wall__arms_loosely_crossed__watching_me_':
        'Apóyate contra una pared, con los brazos ligeramente cruzados, mirándome.',
    'security_lean_against_the_door_frame__one_leg_crossed_casually__smiling_as_you_watch_me_approach_':
        'Apóyate contra el marco de la puerta, con una pierna cruzada casualmente, sonriendo mientras me ves acercarme.',
    'security_lean_forward_a_little__head_tilted__listening_intently_with_a_calm_expression_':
        'Inclínese un poco hacia adelante, con la cabeza inclinada, escuchando atentamente con una expresión tranquila.',
    'security_lounge_on_a_pool_chair__sunglasses_pushed_up_as_you_glance_over_':
        'Recuéstese en una silla de piscina, con las gafas de sol levantadas mientras mira.',
    'security_relax_on_a_couch__one_arm_resting_casually_as_you_smile_':
        'Relájate en un sofá, con un brazo descansando casualmente mientras sonríes.',
    'security_relax_on_a_sofa_in_the_evening__warm_lights_around_you_':
        'Relájese en un sofá por la noche, rodeado de luces cálidas.',
    'security_rest_one_elbow_on_the_table__fingers_tapping_lightly_as_you_smile_lazily_':
        'Apoye un codo sobre la mesa, golpeteando ligeramente con los dedos mientras sonríe perezosamente.',
    'security_rest_your_chin_on_your_hand__looking_at_me_thoughtfully_':
        'Apoya tu barbilla en tu mano, mirándome pensativamente.',
    'security_rest_your_head_back_against_the_cushion__eyes_half_closed__relaxed_and_unguarded_':
        'Apoye la cabeza contra el cojín, con los ojos medio cerrados, relajados y sin vigilancia.',
    'security_rest_your_palms_flat_on_the_table__leaning_back_slightly__breathing_slowly_and_steadily_':
        'Apoye las palmas de las manos sobre la mesa, inclinándose ligeramente hacia atrás, respirando lenta y constantemente.',
    'security_sit_at_a_rooftop_bar__elbows_on_the_railing__looking_out_at_the_night_view_lazily_':
        'Siéntese en un bar en la azotea, con los codos en la barandilla, contemplando perezosamente la vista nocturna.',
    'security_sit_at_a_table_with_a_drink_nearby__glancing_up_like_you_noticed_me_':
        'Siéntate en una mesa con una bebida cerca y mira hacia arriba como si me hubieras notado.',
    'security_sit_at_an_outdoor_caf___one_hand_around_a_glass__relaxed_posture_':
        'Sentarse en un café al aire libre, con una mano alrededor de un vaso, en postura relajada.',
    'security_sit_back_in_a_chair__legs_relaxed__eyes_steady_on_me_':
        'Siéntate en una silla, con las piernas relajadas y los ojos fijos en mí.',
    'security_sit_by_the_pool_in_a_swimsuit__holding_a_cocktail_and_smiling_':
        'Siéntate junto a la piscina en traje de baño, sosteniendo un cóctel y sonriendo.',
    'security_sit_by_the_window_with_soft_light_on_your_face__slowly_looking_at_me_':
        'Siéntate junto a la ventana con una luz suave en tu rostro, mirándome lentamente.',
    'security_sit_close_to_the_camera__relaxed_and_at_ease_':
        'Siéntate cerca de la cámara, relajado y cómodo.',
    'security_sit_in_a_quiet_room__warm_light_behind_you__calm_and_unhurried_':
        'Siéntese en una habitación tranquila, con una luz cálida detrás de usted, tranquilo y sin prisas.',
    'security_sit_in_a_rattan_chair__rocking_it_gently__body_loose_and_eyes_peaceful_':
        'Siéntese en una silla de ratán, meciéndola suavemente, con el cuerpo relajado y la mirada tranquila.',
    'security_sit_in_a_softly_lit_room__body_relaxed__attention_forward_':
        'Siéntate en una habitación suavemente iluminada, con el cuerpo relajado y la atención hacia adelante.',
    'security_sit_on_a_balcony_at_night__city_lights_behind_you_':
        'Siéntate en un balcón por la noche, con las luces de la ciudad detrás de ti.',
    'security_sit_on_a_garden_bench__surrounded_by_faint_floral_scent__hands_resting_on_the_sides_quietly_':
        'Siéntese en un banco del jardín, rodeado de un leve aroma floral, con las manos apoyadas a los lados en silencio.',
    'security_sit_on_a_terrace__breeze_moving_slightly_as_you_look_over_':
        'Siéntate en una terraza, la brisa se mueve ligeramente mientras miras.',
    'security_sit_on_the_edge_of_the_bed__bare_feet_on_the_carpet__looking_relaxed_and_quiet_':
        'Siéntese en el borde de la cama, con los pies descalzos sobre la alfombra, luciendo relajado y tranquilo.',
    'security_stand_by_the_floor_to_ceiling_window__silhouette_against_the_sky__staring_into_the_distance_softly_':
        'Párese junto a la ventana del piso al techo, su silueta contra el cielo, mirando a lo lejos suavemente.',
    'security_stand_in_a_dimly_lit_hallway__light_outlining_your_figure__looking_at_me_calmly_':
        'Párese en un pasillo poco iluminado, la luz delineando su figura, mirándome con calma.',
    'security_stand_in_the_warm_sunlight__closing_your_eyes_briefly__then_opening_them_to_look_at_me_':
        'Párese bajo la cálida luz del sol, cierre los ojos brevemente y luego ábralos para mirarme.',
    'security_stand_near_a_railing__resting_one_arm_while_watching_quietly_':
        'Párate cerca de una barandilla, apoyando un brazo mientras observas en silencio.',
    'security_stand_near_the_pool__water_reflecting_while_you_take_a_slow_sip_':
        'Párate cerca de la piscina, el agua reflejándose mientras tomas un sorbo lento.',
    'security_stretch_slightly_in_your_seat__then_settle_back_comfortably_':
        'Estírese ligeramente en su asiento y luego recuéstese cómodamente.',
    'security_stretch_your_arms_overhead_lazily__then_drop_them_down__slumping_comfortably_in_the_chair_':
        'Estire los brazos perezosamente sobre la cabeza y luego déjelos caer, desplomándose cómodamente en la silla.',
    'security_tilt_your_glass_slowly__swirling_the_drink_inside__watching_me_with_a_faint_smile_':
        'Inclina tu vaso lentamente, haciendo girar la bebida en su interior, mirándome con una leve sonrisa.',
    'security_turn_toward_me_slowly__like_I_just_arrived_':
        'Gira hacia mí lentamente, como si acabara de llegar.',
    'security_twist_the_ring_on_your_finger_gently__eyes_thoughtful_as_you_fix_your_gaze_on_me_':
        'Gira suavemente el anillo en tu dedo, con los ojos pensativos mientras fijas tu mirada en mí.',
    'security_wrap_your_arms_around_your_knees__sitting_curled_up_slightly__eyes_warm_on_me_':
        'Envuelve tus brazos alrededor de tus rodillas, sentándote ligeramente acurrucado, con tus ojos cálidos sobre mí.',
    'security_create_your_account': 'Crea tu cuenta',
    'security_input_content_here__Option_':
        'Ingrese el contenido aquí (Opción)',
    'security_mina_Team': 'Equipo Mina',
    'security_story_background': 'Antecedentes de la historia',
    'security_tap_to_continue___': 'Toca para continuar...',
    'security_aI_Character': 'Personaje de IA',
    'security_ask_for_pic': 'pedir foto',
    'security_ask_for_video': 'pedir vídeo',
    'security_before_creation__please_review': 'Antes de la creación, revise',
    'security_coins_balance': 'Saldo de monedas',
    'security_fail_to_collect': 'No poder recolectar',
    'security_gems_balance': 'equilibrio de gemas',
    'security_mM_dd__HH_mm_': 'MM月dd日 HH时mm分',
    'security_my_Coins': 'Monedas',
    'security_my_Gems': 'Gemas',
    'security_notice__AI_responses_are_fictional_and_for_entertainment_only':
        'Aviso: las respuestas de la IA son ficticias y solo tienen fines de entretenimiento',
    'security_plus_button_tapped': 'Botón más presionado',
    'security_start_Create': 'Empezar a crear',
    'security_unsupported_message_type': 'Tipo de mensaje no admitido',
    'security_voice_button_tapped': 'Botón de voz presionado',
    'security_All_Chat': 'Todo el chat',
    'security_Create_Video': 'Crear vídeo',
    'security_Generate_Video': 'Generar vídeo',
    'security_Mina_Support': 'Soporte Mina',
    'security_No_groups_yet__go_create_one_': 'Aún no hay grupos, ¡crea uno!',
    'security_Please_input_description': 'Por favor ingrese la descripción',
    'security_Search_by_ID__name__tag___': 'Busca por ID, nombre, etiqueta...',
    'security_The_app_may_not_function_as_expected_until_you_remove_this_plugin_from_pubspec_yaml':
        'Es posible que la aplicación no funcione como se esperaba hasta que elimine este complemento de pubspec.yaml.',
    'security_Video_initialization_failed': 'Falló la inicialización del vídeo',
    'security_Got_coins_reward': 'Obtuve recompensa de monedas',
    'security_Unlock_this_photo': 'Desbloquear esta foto',
    'security_Unlocked_successfully': 'Desbloqueado con éxito',
    'security_Your_balance': 'Tu saldo',
    'security_language': 'Idioma',
    'security_select_language': 'Seleccionar idioma',
    'security_settings': 'Ajustes',
    'security_Cancel': 'Cancelar',
    'security_Confirm': 'Confirmar',
    'security_unlock_cost': 'El desbloqueo costará {amount} {currency}',
    'security_reset': 'Restablecer',
    'security_Report': 'Denunciar',
    'security_block': 'Bloquear',
    'security_switch': 'Cambiar',
    'security_reset_user': '¿Restablecer a {name}?',
    'security_clear_history_with_user': 'Borrar el historial con «{name}»',
    'security_clear_history_confirmation': '¿Seguro que quieres borrar todo el historial con «{name}» (incluidos textos, imágenes, vídeos…)? Esta acción no se puede deshacer.',
  };
}
