// Generated by toolchain/translate/generate_copywriting_localizations.py.
// Edit Copywriting or the generator instead of changing keys by hand.

abstract final class CopywritingStringsDe {
  static const Map<String, String> values = <String, String>{
    'security_about_her': 'Über sie',
    'security_account_Deletion': 'Kontolöschung',
    'security_add_rounds': 'Runden hinzufügen',
    'security_all_Gender': 'Alle Geschlechter',
    'security_appears_exclusively_in_your_character__s_public_profile_This_biographical_information_will_not_be_utilized_in_generation_prompts_or_influence_behavioral_patterns_':
        'Erscheint ausschließlich im öffentlichen Profil Ihres Charakters. Diese biografischen Informationen werden nicht für Generationsaufforderungen verwendet oder beeinflussen Verhaltensmuster.',
    'security_are_you_sure_you_want_to_delete_your_account_':
        'Sind Sie sicher, dass Sie Ihr Konto löschen möchten?',
    'security_are_you_sure_you_want_to_log_out_':
        'Möchten Sie sich wirklich abmelden?',
    'security_audio_Library': 'Audiobibliothek',
    'security_audio_input_is_too_short_to_send_':
        'Der Audioeingang ist zum Senden zu kurz.',
    'security_avatar_upload_failed__please_try_again_later_':
        'Das Hochladen des Avatars ist fehlgeschlagen. Bitte versuchen Sie es später noch einmal.',
    'security_avatar_uploaded': 'Avatar hochgeladen',
    'security_birth_date': 'Geburtsdatum',
    'security_by_clicking_Security_security_Subscribe__you_will_be_charged__and_your_subscription_will_automatically_renew_at_the_same_price_and_duration_until_canceled_through_PlayStore_settings__By_proceeding__you_agree_to_our_terms_':
        'Wenn Sie auf Security.security_Subscribe klicken, wird Ihnen eine Gebühr berechnet und Ihr Abonnement verlängert sich automatisch zum gleichen Preis und zur gleichen Dauer, bis es über die PlayStore-Einstellungen gekündigt wird. Indem Sie fortfahren, stimmen Sie unseren Bedingungen zu.',
    'security_call_Duration': 'Anrufdauer',
    'security_cannot_get_information__please_retry_later':
        'Es können keine Informationen abgerufen werden. Bitte versuchen Sie es später noch einmal',
    'security_cannot_get_physique_details__please_retry_later':
        'Körperdaten können nicht abgerufen werden. Bitte versuchen Sie es später noch einmal',
    'security_cannot_open_date_picker__please_retry_later':
        'Die Datumsauswahl kann nicht geöffnet werden. Bitte versuchen Sie es später noch einmal',
    'security_click_to_add': 'Klicken Sie zum Hinzufügen',
    'security_click_to_play': 'Zum Abspielen klicken',
    'security_coin_balance': 'Münzguthaben',
    'security_connecting___': 'Anschließen...',
    'security_copyright_Agreement': 'Urheberrechtsvereinbarung',
    'security_create_My_Character': 'Erstelle meinen Charakter',
    'security_create_Now': 'Jetzt erstellen',
    'security_create_an_account': 'Erstellen Sie ein Konto',
    'security_current_device_not_support__try_restart_app_':
        'Aktuelles Gerät wird nicht unterstützt. Versuchen Sie, die App neu zu starten.',
    'security_defines_the_conversational_patterns_between_you_and_your_character__This_crucial_setting_determines_how_your_character_formulates_responses_and_maintains_personality_consistency_':
        'Definiert die Gesprächsmuster zwischen Ihnen und Ihrem Charakter. Diese entscheidende Einstellung bestimmt, wie Ihr Charakter Antworten formuliert und die Persönlichkeitskonsistenz aufrechterhält.',
    'security_delete_account_': 'Konto löschen?',
    'security_deleting___': 'Löschen...',
    'security_describe_the_conversation_scenario_and_involved_characters_':
        'Beschreiben Sie das Gesprächsszenario und die beteiligten Charaktere.',
    'security_describe_the_issue': 'Beschreiben Sie das Problem',
    'security_dialogue_Style': 'Dialogstil',
    'security_edit_information': 'Informationen bearbeiten',
    'security_enter_verification_code': 'Geben Sie den Bestätigungscode ein',
    'security_entry_your_email': 'Geben Sie Ihre E-Mail-Adresse ein',
    'security_expires_on': 'Läuft ab am',
    'security_failed_to_follow': 'Konnte nicht folgen',
    'security_failed_to_load_subscription_data':
        'Abonnementdaten konnten nicht geladen werden',
    'security_failed_to_process_subscription__please_try_again_later_':
        'Das Abonnement konnte nicht verarbeitet werden. Bitte versuchen Sie es später erneut.',
    'security_failed_to_record_audio__please_try_again':
        'Audioaufnahme fehlgeschlagen. Bitte versuchen Sie es erneut',
    'security_failed_to_send_gift': 'Geschenk konnte nicht gesendet werden',
    'security_failed_to_unfollow': 'Entfolgen fehlgeschlagen',
    'security_failed_to_update__please_retry_later':
        'Aktualisierung fehlgeschlagen, bitte versuchen Sie es später noch einmal',
    'security_feelie_Pro': 'Feelie Pro',
    'security_fill_in_your_introduction___':
        'Füllen Sie Ihre Einleitung aus...',
    'security_following_the_regeneration_process__you_ll_receive_a_brand_new_image__You_are_also_welcome_to_revisit_the_images_you_created_earlier__Are_you_ready_to_move_forward_':
        'Nach dem Regenerationsprozess erhalten Sie ein brandneues Bild. Gerne können Sie sich auch die zuvor erstellten Bilder noch einmal ansehen. Sind Sie bereit, weiterzumachen?',
    'security_for_example___On_the_moonlit_balcony_of_a_neo___Victorian_mansion__an_ethereal_woman_with_bright_blue_hime___cut_hair':
        'Zum Beispiel: „Auf dem mondbeschienenen Balkon eines neoviktorianischen Herrenhauses steht eine ätherische Frau mit leuchtend blauen, himegeschnittenen Haaren.“',
    'security_gem_balance': 'Edelsteingleichgewicht',
    'security_generating_in_progress': 'Generierung läuft',
    'security_generating___': 'Generieren...',
    'security_get_full_access_': 'Erhalten Sie vollen Zugriff!',
    'security_hold_to_talk': 'Halten Sie die Taste gedrückt, um zu sprechen',
    'security_how_would_you_like_OC_to_address_you_':
        'Wie möchten Sie, dass OC Sie anspricht?',
    'security_image_Prompt': 'Bildaufforderung',
    'security_information_updated_': 'Informationen aktualisiert.',
    'security_insufficient_balance_': 'Unzureichendes Gleichgewicht.',
    'security_interrupt_AI': 'KI unterbrechen',
    'security_loading___': 'Laden...',
    'security_log_out': 'Abmelden',
    'security_logging_in___': 'Anmelden...',
    'security_master_name_must_be_2_24_characters_in_length':
        'Der Mastername muss 2–24 Zeichen lang sein',
    'security_modify_Now': 'Jetzt ändern',
    'security_name_your_character': 'Benennen Sie Ihren Charakter',
    'security_network_error': 'Netzwerkfehler',
    'security_network_error__please_try_again_later':
        'Netzwerkfehler, bitte versuchen Sie es später erneut',
    'security_network_exception__please_try_again_later':
        'Netzwerkfehler, bitte versuchen Sie es später noch einmal',
    'security_no_chat_partner_has_been_initiated_yet':
        'Es wurde noch kein Chatpartner initiiert',
    'security_no_companions_yet': 'Noch keine Begleiter',
    'security_no_data': 'Keine Daten',
    'security_no_user_information__getting_back___':
        'Keine Benutzerinformationen, ich melde mich zurück...',
    'security_notice__Everything_AI_says_is_made_up':
        'Hinweis: Alles, was die KI sagt, ist erfunden',
    'security_obtain_code': 'Code abrufen',
    'security_platform_not_supported_': 'Plattform nicht unterstützt.',
    'security_please_agree_to_the_terms_and_conditions':
        'Bitte stimmen Sie den Allgemeinen Geschäftsbedingungen zu',
    'security_please_select_a_product_to_recharge_':
        'Bitte wählen Sie ein Produkt zum Aufladen aus.',
    'security_premium_Benefits_for_Audio__unlimited':
        'Premium-Vorteile für Audio, unbegrenzt',
    'security_prior_to_the_creation_process__please_review_our':
        'Bitte lesen Sie vor dem Erstellungsprozess unsere',
    'security_privacy_Policy': 'Datenschutzrichtlinie',
    'security_privacy_policy': 'Datenschutzerklärung',
    'security_pro_Free': 'Pro kostenlos',
    'security_pro_only': 'Nur Pro',
    'security_purchase_done': 'Kauf abgeschlossen',
    'security_purchased_Success': 'Erkaufter Erfolg',
    'security_purchasing___': 'Einkauf...',
    'security_recharge_failed_': 'Aufladen fehlgeschlagen.',
    'security_regeneration_Tips': 'Regenerationstipps',
    'security_release_Cancel': 'Loslassen Abbrechen',
    'security_release_Send': 'Senden freigeben',
    'security_role_image': 'Rollenbild',
    'security_sF_Pro': 'SF Pro',
    'security_sF_Pro_bold': 'SF Pro bold',
    'security_select_from_gallery': 'Aus der Galerie auswählen',
    'security_select_from_the_album': 'Aus dem Album auswählen',
    'security_selected_date_is_out_of_range_':
        'Das ausgewählte Datum liegt außerhalb des gültigen Bereichs.',
    'security_send_failed__please_try_again_later':
        'Senden fehlgeschlagen, bitte versuchen Sie es später erneut',
    'security_send_message__reply_by_AI': 'Nachricht senden, Antwort durch KI',
    'security_sending___': 'Senden...',
    'security_sign_in_with_Apple': 'Mit Apple anmelden',
    'security_sign_in_with_E_mail': 'Mit E-Mail anmelden',
    'security_start_create': 'Erstellen starten',
    'security_submitted_successfully': 'Erfolgreich übermittelt',
    'security_supply_detailed_information_about_the_image__such_as_the_clothing_worn__facial_features__and_actions_':
        'Geben Sie detaillierte Informationen zum Bild an, z. B. die getragene Kleidung, Gesichtszüge und Aktionen.',
    'security_take_it_with_camera': 'Nehmen Sie es mit der Kamera auf',
    'security_terms_of_Service': 'Nutzungsbedingungen',
    'security_terms_of_service': 'Nutzungsbedingungen',
    'security_the_OC_will_address_you_by_the_name_you_enter_':
        'Das OK wird Sie mit dem von Ihnen eingegebenen Namen ansprechen.',
    'security_the_character_creation_is_still_ongoing__Leaving_at_this_moment_will_forfeit_the_progress_made_so_far__Are_you_sure_you_want_to_go_back_':
        'Die Charaktererstellung ist noch im Gange. Wenn Sie zu diesem Zeitpunkt abreisen, gehen die bisher erzielten Fortschritte verloren. Sind Sie sicher, dass Sie zurückkehren möchten?',
    'security_the_uploaded_image_serves_as_a_reference_for_facial_features_and_style_elements':
        'Das hochgeladene Bild dient als Referenz für Gesichtszüge und Stilelemente',
    'security_turn_on_the_camera': 'Schalten Sie die Kamera ein',
    'security_unable_to_get_recharge_service__please_retry_later_':
        'Der Aufladedienst konnte nicht genutzt werden. Bitte versuchen Sie es später noch einmal.',
    'security_unknown_error__please_upload_again_':
        'Unbekannter Fehler, bitte erneut hochladen.',
    'security_unlock_Audio': 'Audio entsperren',
    'security_unlock_Image': 'Bild entsperren',
    'security_unlock_Video': 'Video entsperren',
    'security_updating_information___': 'Informationen werden aktualisiert...',
    'security_upload_failed__please_try_again_later':
        'Hochladen fehlgeschlagen, bitte versuchen Sie es später noch einmal',
    'security_uploading_new_avatar___': 'Neuer Avatar wird hochgeladen...',
    'security_you_have_muted': 'Du hast stummgeschaltet',
    'security_supply_detailed_information_about_the_image__such_as_the_clothing_worn__facial_features__and_actions__For_example___On_the_moonlit_balcony_of_a_neo___Victorian_mansion__an_ethereal_woman_with_bright_blue_hime___cut_hair_leans_against_the_railing__Her_khaki_backless_sweater_flutters_gently_in_the_breeze_as_she_turns_to_look_at_the_viewer_with_an_otherworldly_serenity__':
        'Geben Sie detaillierte Informationen zum Bild an, z. B. die getragene Kleidung, Gesichtszüge und Aktionen. Zum Beispiel: „Auf dem mondbeschienenen Balkon eines neoviktorianischen Herrenhauses lehnt eine ätherische Frau mit leuchtend blauem Hime-Schnitt am Geländer. Ihr khakifarbener, rückenfreier Pullover flattert sanft im Wind, während sie sich umdreht, um den Betrachter mit einer überirdischen Gelassenheit anzusehen.“',
    'security_cannot_download_source__please_try_again_later':
        'Die Quelle kann nicht heruntergeladen werden. Bitte versuchen Sie es später noch einmal',
    'security_if_you_sign_in__you_agree_to':
        'Wenn Sie sich anmelden, stimmen Sie zu',
    'security_send_me_a_picture': 'Schicken Sie mir ein Bild',
    'security_send_me_a_video': 'Schicken Sie mir ein Video',
    'security_and_indicate_your_consent_': 'und geben Sie Ihr Einverständnis.',
    'security_consuming_props_during_call':
        'Verbrauch von Requisiten während des Anrufs',
    'security_no_more_companions_to_load_':
        'Es müssen keine Begleiter mehr geladen werden.',
    'security_per_minute': 'pro Minute',
    'security_edit': 'Bearbeiten',
    'security_video_Call': 'Videoanruf',
    'security_i_am_listening___': 'Ich höre...',
    'security_i_am_thinking___': 'Ich denke...',
    'security_audio_Call': 'Audioanruf',
    'security_canceled_by_caller': 'Vom Anrufer abgebrochen',
    'security_no_answer__please_try_again_later':
        'Keine Antwort, bitte versuchen Sie es später noch einmal',
    'security_no_favorites_yet__go_and_follow_some_people_':
        'Noch keine Favoriten, folgen Sie einigen Leuten!',
    'security_benefits_Usage_Detail': 'Einzelheiten zur Nutzung der Vorteile',
    'security_chat_beyond_reality__role_play_without_limits':
        'Chatten Sie über die Realität hinaus, Rollenspiele ohne Grenzen',
    'security_please_grant_camera_permission':
        'Bitte erteilen Sie der Kamera die Erlaubnis',
    'security_please_grant_microphone_permission':
        'Bitte erteilen Sie die Mikrofonerlaubnis',
    'security_unlocking_for_free_': 'Kostenlos freischalten!',
    'security_you__re_now_a_premium_member__nYour_benefits_are_unlocked__nExplore_your_new_perks_':
        'Sie sind jetzt Premium-Mitglied!\\nIhre Vorteile sind freigeschaltet.\\nEntdecken Sie Ihre neuen Vorteile!',
    'security_by_clicking_subscribe__you_will_be_charged__and_your_subscription_will_automatically_renew_at_the_same_price_and_duration_until_canceled_through_App_Store_settings__By_proceeding__you_agree_to_our_terms_':
        'Wenn Sie auf „Abonnieren“ klicken, wird Ihnen eine Gebühr in Rechnung gestellt und Ihr Abonnement verlängert sich automatisch zum gleichen Preis und zur gleichen Dauer, bis es über die App Store-Einstellungen gekündigt wird. Indem Sie fortfahren, stimmen Sie unseren Bedingungen zu.',
    'security_daily_Task': 'Tägliche Aufgabe',
    'security_premium_Only': 'Nur Premium',
    'security_introduction': 'Einleitung',
    'security_premium_Free': 'Premium kostenlos',
    'security_an_error_occurred__please_try_again_later_':
        'Es ist ein Fehler aufgetreten. Bitte versuchen Sie es später noch einmal.',
    'security_product_id_not_found__please_try_again_later':
        'Produkt-ID nicht gefunden, bitte versuchen Sie es später noch einmal',
    'security_call_wasn__t_answered': 'Anruf wurde nicht beantwortet',
    'security_cancelled_by_Caller': 'Vom Anrufer abgebrochen',
    'security_consuming_gems_during_call':
        'Konsumieren von Edelsteinen während des Anrufs',
    'security_ending___': 'Ende...',
    'security_free_Call': 'Kostenloser Anruf',
    'security_not_enough_gems__please_recharge':
        'Nicht genügend Edelsteine, bitte aufladen',
    'security_send_a_message_': 'Eine Nachricht senden…',
    'security_free_for_first': 'Zunächst kostenlos',
    'security_error__max_should_not_be_a_negative_number_or_zero':
        'Fehler, max sollte keine negative Zahl oder Null sein',
    'security_error__min_is_greater_than_or_equal_to_max':
        'Fehler, min ist größer oder gleich max',
    'security_invites_you': 'Lädt dich ein',
    'security_aD_Free': 'Werbefrei',
    'security_enter_your_image_prompt__e_g__A_girl__sitting_on_a_bench___':
        'Geben Sie Ihre Bildaufforderung ein, z. B. Ein Mädchen sitzt auf einer Bank...',
    'security_failed_to_grant_coin__Please_try_again_later_':
        'Münze konnte nicht gewährt werden. Bitte versuchen Sie es später noch einmal.',
    'security_failed_to_unlock_resource__Please_try_again_later_':
        'Ressource konnte nicht entsperrt werden. Bitte versuchen Sie es später noch einmal.',
    'security_image_prompt_cannot_be_empty':
        'Bildaufforderung darf nicht leer sein',
    'security_images_you_like': 'Bilder, die Ihnen gefallen',
    'security_please_select_at_least_one_prompt':
        'Bitte wählen Sie mindestens eine Eingabeaufforderung aus',
    'security_signing_in___': 'Anmelden...',
    'security_all_Chat': 'Alle Chats',
    'security_chat_Models': 'Chat-Modelle',
    'security_chat_Now': 'Jetzt chatten',
    'security_clear_Chat_History': 'Chatverlauf löschen',
    'security_connect_with_everyone_in_one_place':
        'Vernetzen Sie sich mit allen an einem Ort',
    'security_contact_us_for_support_':
        'Kontaktieren Sie uns für Unterstützung.',
    'security_delete_Message': 'Nachricht löschen',
    'security_design_your_own_unique_character_and_bring_it_to_life_':
        'Entwerfen Sie Ihren eigenen einzigartigen Charakter und erwecken Sie ihn zum Leben.',
    'security_group_Chat': 'Gruppenchat',
    'security_limited_Free': 'Begrenzt kostenlos',
    'security_mark_all_as_read': 'Alle als gelesen markieren',
    'security_message_Setting': 'Nachrichteneinstellung',
    'security_message_setting': 'Nachrichteneinstellung',
    'security_reset_Success_': 'Erfolgreich zurücksetzen!',
    'security_rewind_to_here': 'Zurückspulen hierher',
    'security_she_will_forget_conversation_history_with_you_':
        'Sie wird die Gesprächsgeschichte mit Ihnen vergessen!',
    'security_shield_Real__s_Messages': 'Nachrichten von Shield Real',
    'security_soulink_Team': 'Soulink-Team',
    'security_switch_Failed': 'Schalter fehlgeschlagen',
    'security_switch_Succeed_enjoy_your_chat':
        'Switch Erfolgreich, viel Spaß beim Chatten',
    'security_switch_the_Model': 'Wechseln Sie das Modell',
    'security_contact_us': 'Kontaktieren Sie uns',
    'security_iAP_Service_Not_Available': 'IAP-Dienst nicht verfügbar',
    'security_iAP_not_available__restart_the_app_and_try_again_':
        'IAP nicht verfügbar, starten Sie die App neu und versuchen Sie es erneut.',
    'security_item_info_error': 'Artikelinformationsfehler',
    'security_monthly_Premium': 'Monatliche Prämie',
    'security_no_recharge_item_available__try_again_later':
        'Kein Aufladeelement verfügbar, versuchen Sie es später erneut',
    'security_payment_failed': 'Zahlung fehlgeschlagen',
    'security_payment_successful': 'Zahlung erfolgreich',
    'security_purchase_successful': 'Kauf erfolgreich',
    'security_receipt_Not_Available': 'Quittung nicht verfügbar',
    'security_special_Offer': 'Sonderangebot',
    'security_weekly_Premium': 'Wöchentliche Prämie',
    'security_yearly_Premium': 'Jährliche Prämie',
    'security_about_AI_MODE': 'Über den KI-MODUS',
    'security_about_Me': 'Über mich',
    'security_add_Group_Member': 'Gruppenmitglied hinzufügen',
    'security_add_New_Group_Member': 'Neues Gruppenmitglied hinzufügen',
    'security_are_you_sure_you_want_to_disband_this_group__This_action_cannot_be_undone__and_all_members_will_be_removed_':
        'Sind Sie sicher, dass Sie diese Gruppe auflösen möchten? Diese Aktion kann nicht rückgängig gemacht werden und alle Mitglieder werden entfernt.',
    'security_auto___enabled__The_mentioned_member_s__will_reply_your_message_':
        'Auto @ aktiviert. Die genannten Mitglieder werden auf Ihre Nachricht antworten.',
    'security_click_anywhere_to_continue___':
        'Klicken Sie irgendwo, um fortzufahren...',
    'security_congratulations__You_got_a_new_MODE__enjoy_it_':
        'Herzlichen Glückwunsch! Du hast einen neuen MODUS, viel Spaß damit.',
    'security_contact_List': 'Kontaktliste',
    'security_create_Group': 'Gruppe erstellen',
    'security_dating_Game': 'Dating-Spiel',
    'security_disband_Group': 'Gruppe auflösen',
    'security_disband_Group_': 'Gruppe auflösen?',
    'security_download_failed__please_retry_later_':
        'Download fehlgeschlagen, bitte versuchen Sie es später noch einmal!',
    'security_edit_Group_Name': 'Gruppennamen bearbeiten',
    'security_edit_Group_Scenario': 'Gruppenszenario bearbeiten',
    'security_enter_the_Group_Scenario': 'Geben Sie das Gruppenszenario ein',
    'security_enter_the_group_name': 'Geben Sie den Gruppennamen ein',
    'security_error_occurred__please_try_again':
        'Fehler aufgetreten, bitte versuchen Sie es erneut',
    'security_go_Play': 'Geh spielen',
    'security_group_Info': 'Gruppeninfo',
    'security_group_Member': 'Gruppenmitglied',
    'security_group_Name': 'Gruppenname',
    'security_group_Owner': 'Gruppeneigentümer',
    'security_group_Scenario': 'Gruppenszenario',
    'security_in_Use': 'Im Einsatz',
    'security_in_use': 'Im Einsatz',
    'security_level_Up_': 'Level aufsteigen!',
    'security_my_OCs': 'Meine OCs',
    'security_not_enough_balance': 'Nicht genügend Gleichgewicht',
    'security_please_agree_to_the_terms_below_first_':
        'Bitte stimmen Sie zunächst den nachstehenden Bedingungen zu.',
    'security_popular_Search': 'Beliebte Suche',
    'security_recent_Search': 'Letzte Suche',
    'security_search_Failed': 'Suche fehlgeschlagen',
    'security_search_Users_by_ID_or_Name': 'Benutzer nach ID oder Name suchen',
    'security_some_error_occur__please_retry_later_':
        'Es ist ein Fehler aufgetreten, bitte versuchen Sie es später noch einmal!',
    'security_some_error_occurred__try_again_later_':
        'Es ist ein Fehler aufgetreten. Versuchen Sie es später noch einmal.',
    'security_some_error_occurred__Please_try_again_later_':
        'Es ist ein Fehler aufgetreten. Bitte versuchen Sie es später noch einmal.',
    'security_start_Game': 'Spiel starten',
    'security_switch_Succeed__enjoy_your_chat':
        'Switch Erfolgreich, viel Spaß beim Chatten',
    'security_switch_to_Chat': 'Wechseln Sie zum Chat',
    'security_take_a_look__': 'Schauen Sie mal rein >',
    'security_the_MODE_will_only_take_effect_after_you_have_acquired_this_character__Continue_purchasing_':
        'Der MODUS wird erst wirksam, nachdem Sie diesen Charakter erworben haben. Weiter einkaufen?',
    'security_the_muted_member_will_not_reply_your_message':
        'Das stummgeschaltete Mitglied antwortet nicht auf Ihre Nachricht',
    'security_this_member_is_deactivated_': 'Dieses Mitglied ist deaktiviert.',
    'security_this_member_is_expired_': 'Dieses Mitglied ist abgelaufen.',
    'security_time_limit': 'Frist',
    'security_try_it': 'Probieren Sie es aus',
    'security_unlock_conditions_not_met__Upgrade_your_level_now_':
        'Entsperrbedingungen nicht erfüllt. Verbessere jetzt dein Level!',
    'security_unlock_tips': 'Tipps freischalten',
    'security_your_reward': 'Dein Lohn',
    'security_edit_My_Character': 'Meinen Charakter bearbeiten',
    'security_message_Settings': 'Nachrichteneinstellungen',
    'security_no_datas__click_to_retry_':
        'Keine Daten, klicken Sie, um es erneut zu versuchen.',
    'security_start_Chat': 'Chat starten',
    'security_send_a_message___': 'Eine Nachricht senden...',
    'security_send_me_a_pic_with_you_tucking_hair_behind_ear_in_sunset__Send_me_a_pic_with_you_touching_flower_petals_at_dusk__Send_me_a_pic_with_you_holding_teacup_by_rain_window__Send_me_a_pic_with_you_twirling_silk_scarf_by_the_lake__Send_me_a_pic_with_you_adjusting_shoelace_in_sunlight__Send_me_a_pic_with_you_skimming_calm_fountain_surface__Send_me_a_pic_with_you_wrapping_shawl_on_the_balcony':
        'Schicken Sie mir ein Bild, auf dem Sie im Sonnenuntergang Ihre Haare hinters Ohr stecken||Schicken Sie mir ein Bild, auf dem Sie in der Abenddämmerung Blütenblätter berühren||Schicken Sie mir ein Bild, auf dem Sie eine Teetasse am Regenfenster halten||Schicken Sie mir ein Bild, auf dem Sie Ihren Seidenschal am See herumwirbeln||Schicken Sie mir ein Bild, auf dem Sie Ihre Schnürsenkel im Sonnenlicht zurechtrücken||Schicken Sie mir ein Bild, auf dem Sie über die ruhige Wasseroberfläche eines Springbrunnens gleiten||Schicken Sie mir ein Bild, auf dem Sie Ihren Schal auf dem Balkon einwickeln',
    'security_nice_to_meet_you_': 'Schön dich kennenzulernen!',
    'security_sign_in_with_Google': 'Mit Google anmelden',
    'security_failed_to_save__image_URL_is_empty':
        'Speichern fehlgeschlagen, Bild-URL ist leer',
    'security_failed_to_save__try_again_later':
        'Speichern fehlgeschlagen. Versuchen Sie es später erneut',
    'security_failed_to_save__try_again_later_Data_Empty_':
        'Speichern fehlgeschlagen, versuchen Sie es später noch einmal.[Daten leer]',
    'security_saved_successfully': 'Erfolgreich gespeichert',
    'security_saving___': 'Speichern...',
    'security_scenario': 'Szenario',
    'security_are_you_sure_you_want_to_block_this_user_':
        'Sind Sie sicher, dass Sie diesen Benutzer blockieren möchten?',
    'security_bock_Messages_from_Strangers': 'Blocknachrichten von Fremden',
    'security_aI_Writer': 'KI-Autor',
    'security_permission_settings': 'Berechtigungseinstellungen',
    'security_the_existing_filled_content_will_be_replaced_by_the_template_content_and_cannot_be_undone_':
        'Der vorhandene gefüllte Inhalt wird durch den Vorlageninhalt ersetzt und kann nicht rückgängig gemacht werden.',
    'security_what_should_AI_call_you': 'Wie soll AI dich nennen?',
    'security_generation_failed__please_try_again_later_':
        'Generierung fehlgeschlagen, bitte versuchen Sie es später erneut.',
    'security_copied_ID_to_clipboard': 'ID in die Zwischenablage kopiert',
    'security_character_name_must_be_at_least_3_letters_':
        'Der Charaktername muss mindestens 3 Buchstaben haben.',
    'security_more_Details': 'Weitere Details',
    'security_feedback_Log': 'Feedback-Protokoll',
    'security_image_is_Not_ready__please_try_again_later_':
        'Das Bild ist nicht bereit. Bitte versuchen Sie es später noch einmal.',
    'security_not_approved': 'Nicht genehmigt',
    'security_under_review': 'Wird derzeit überprüft',
    'security_upload_Log_success': 'Erfolgreiches Hochladen des Protokolls',
    'security_about_Soulink': 'Über Soulink',
    'security_are_you_sure_': 'Bist du sicher?',
    'security_character_is_private': 'Charakter ist privat',
    'security_complete_tasks_to_get_rewards':
        'Erledige Aufgaben, um Belohnungen zu erhalten',
    'security_cost_Trial_Card': 'Kostenprobekarte',
    'security_create_Character': 'Charakter erstellen',
    'security_create_Moment': 'Moment schaffen',
    'security_create_an_image_with_Generator':
        'Erstellen Sie ein Bild mit Generator',
    'security_currently_owns_': 'Besitzt derzeit:',
    'security_daily_post_limit_exceeded':
        'Das tägliche Postlimit wurde überschritten',
    'security_describe_what_you_want__e_g___A_barista_wipes_the_counter_of_a_small_caf__by_the_river__steam_rising_from_coffee_cups__boats_passing_slowly_outside_the_window__a_cat_napping_on_a_nearby_chair_':
        'Beschreiben Sie, was Sie wollen, z. B.: Ein Barista wischt die Theke eines kleinen Cafés am Fluss ab, Dampf steigt aus Kaffeetassen, Boote fahren langsam vor dem Fenster vorbei, eine Katze schläft auf einem Stuhl in der Nähe.',
    'security_don_t_remind_me_again': 'Erinnere mich nicht noch einmal daran',
    'security_enable_this_option_to_allow_the_AI_to_generate_image_galleries_based_on_your_information_':
        'Aktivieren Sie diese Option, damit die KI Bildergalerien basierend auf Ihren Informationen erstellen kann.',
    'security_enter_the_Description': 'Geben Sie die Beschreibung ein',
    'security_exit_Video_Matching_': 'Video-Matching beenden?',
    'security_failed_Generate': 'Generierung fehlgeschlagen',
    'security_failed_reload': 'Neuladen fehlgeschlagen',
    'security_first_message_from_your_character__It_will_help_the_chat_get_off_to_a_better_start_':
        'Erste Nachricht von deinem Charakter. Dies wird dazu beitragen, dass der Chat besser startet.',
    'security_for_You': 'Für Sie',
    'security_generate_Video': 'Video generieren',
    'security_generate_config_loading':
        'Generieren Sie das Laden der Konfiguration',
    'security_generate_for_Moment': 'Für den Moment generieren',
    'security_generate_video': 'Video generieren',
    'security_generating_Gallery': 'Galerie wird erstellt',
    'security_get_30s_Free_Trial':
        'Holen Sie sich eine 30-sekündige kostenlose Testversion',
    'security_go_Setting': 'Gehen Sie zur Einstellung',
    'security_grants_the_first_30_seconds_of_the_call_for_free__After_that__gems_will_be_charged_':
        'Gewährt die ersten 30 Sekunden des Anrufs kostenlos. Danach werden Edelsteine ​​berechnet.',
    'security_i_understand': 'Ich verstehe',
    'security_image_details__facial_features__clothing':
        'Bilddetails, Gesichtszüge, Kleidung',
    'security_initial_Message': 'Erste Nachricht',
    'security_invites_you_to_video_calling_': 'Lädt Sie zu Videoanrufen ein…',
    'security_lets_you_make_calls_without_spending_gems_':
        'Ermöglicht das Tätigen von Anrufen, ohne Edelsteine auszugeben.',
    'security_mM_dd_HH_mm': 'MM-dd HH:mm',
    'security_just_now': 'Gerade eben',
    'security_one_minute_ago': 'Vor 1 Minute',
    'security_minutes_ago': 'Vor {count} Minuten',
    'security_one_hour_ago': 'Vor 1 Stunde',
    'security_hours_ago': 'Vor {count} Stunden',
    'security_one_day_ago': 'Vor 1 Tag',
    'security_days_ago': 'Vor {count} Tagen',
    'security_one_week_ago': 'Vor 1 Woche',
    'security_weeks_ago': 'Vor {count} Wochen',
    'security_maximum_limit_exceeded': 'Höchstgrenze überschritten',
    'security_no_report_reasons_available': 'Keine Meldegründe verfügbar',
    'security_operation_failed': 'Der Vorgang ist fehlgeschlagen',
    'security_permission_required': 'Genehmigung erforderlich',
    'security_please_allow_access_to_the_camera_in_the_settings':
        'Bitte erlauben Sie den Zugriff auf die Kamera in den Einstellungen',
    'security_please_allow_access_to_the_microphone_in_the_settings':
        'Bitte erlauben Sie den Zugriff auf das Mikrofon in den Einstellungen',
    'security_please_input_description':
        'Bitte geben Sie eine Beschreibung ein',
    'security_please_select_a_character_first':
        'Bitte wählen Sie zuerst ein Zeichen aus',
    'security_post_As': 'Posten als',
    'security_post_successful': 'Beitrag erfolgreich',
    'security_post_updates_for_your_character_and_bring_every_moment_of_their_story_to_life_':
        'Veröffentlichen Sie Updates für Ihren Charakter und erwecken Sie jeden Moment seiner Geschichte zum Leben!',
    'security_post_your_reply': 'Veröffentlichen Sie Ihre Antwort',
    'security_report_Success_': 'Erfolg melden!',
    'security_select_From_Chat_History_Album':
        'Wählen Sie „Aus Chat-Verlaufsalbum“.',
    'security_select_Image': 'Bild auswählen',
    'security_select_a_Character': 'Wählen Sie einen Charakter aus',
    'security_start_Match': 'Spiel starten',
    'security_switching_characters_will_clear_the_current_content':
        'Durch das Wechseln der Zeichen wird der aktuelle Inhalt gelöscht',
    'security_the_user_has_been_matched__and_the_other_party_accepts_and_enters_the_video_call':
        'Der Benutzer wurde zugeordnet und die andere Partei nimmt den Videoanruf an und nimmt daran teil',
    'security_this_moment_does_not_meet_community_requirements__please_edit':
        'Dieser Moment entspricht nicht den Community-Anforderungen, bitte bearbeiten',
    'security_translation_failure_': 'Übersetzungsfehler…',
    'security_you_need_to_have_your_own_role_to_post___nGo_create_a_character':
        'Sie müssen Ihre eigene Rolle zum Posten haben! \\nErstelle einen Charakter',
    'security_you_re_now_using_your_trial_card_or_available_call_time___whichever_applies_':
        'Sie nutzen jetzt Ihre Testkarte oder die verfügbare Gesprächszeit – je nachdem, was zutrifft.',
    'security_please_grant_storage_permission':
        'Bitte erteilen Sie die Speichererlaubnis',
    'security_brush_a_strand_of_hair_back_gently__eyes_soft_as_you_gaze_straight_at_me_':
        'Streichen Sie eine Haarsträhne sanft nach hinten, die Augen sanft, während Sie mich direkt ansehen.',
    'security_hold_a_book_loosely_in_your_hand__flipping_a_page_slowly_as_you_glance_up_':
        'Halten Sie ein Buch locker in der Hand und blättern Sie langsam eine Seite um, während Sie nach oben schauen.',
    'security_hold_a_cup_of_warm_drink__blowing_on_it_softly_before_taking_a_small_sip_':
        'Halten Sie eine Tasse mit warmem Getränk in der Hand und pusten Sie sanft darauf, bevor Sie einen kleinen Schluck trinken.',
    'security_lean_against_a_bar_counter__drink_in_hand__shoulders_loose_':
        'Lehnen Sie sich mit einem Getränk in der Hand und lockeren Schultern an eine Bartheke.',
    'security_lean_against_a_bookshelf__one_hand_brushing_the_spines__calm_and_unhurried_':
        'Lehnen Sie sich ruhig und ohne Eile an ein Bücherregal und streichen Sie mit einer Hand über die Buchrücken.',
    'security_lean_against_a_wall__arms_loosely_crossed__watching_me_':
        'Lehne dich mit locker verschränkten Armen an eine Wand und beobachte mich.',
    'security_lean_against_the_door_frame__one_leg_crossed_casually__smiling_as_you_watch_me_approach_':
        '​​Lehnen Sie sich gegen den Türrahmen, ein Bein lässig gekreuzt, und lächeln Sie, während Sie mich näherkommen sehen.',
    'security_lean_forward_a_little__head_tilted__listening_intently_with_a_calm_expression_':
        'Lehnen Sie sich mit geneigtem Kopf ein wenig nach vorne und hören Sie aufmerksam und mit ruhiger Miene zu.',
    'security_lounge_on_a_pool_chair__sunglasses_pushed_up_as_you_glance_over_':
        'Entspannen Sie sich auf einem Liegestuhl, schieben Sie die Sonnenbrille hoch und schauen Sie hinüber.',
    'security_relax_on_a_couch__one_arm_resting_casually_as_you_smile_':
        'Entspannen Sie sich auf einer Couch, legen Sie einen Arm locker ab und lächeln Sie.',
    'security_relax_on_a_sofa_in_the_evening__warm_lights_around_you_':
        'Entspannen Sie sich abends auf einem Sofa, warmes Licht umgibt Sie.',
    'security_rest_one_elbow_on_the_table__fingers_tapping_lightly_as_you_smile_lazily_':
        'Legen Sie einen Ellbogen auf den Tisch, klopfen Sie leicht mit den Fingern und lächeln Sie träge.',
    'security_rest_your_chin_on_your_hand__looking_at_me_thoughtfully_':
        'Lege dein Kinn auf deine Hand und schaue mich nachdenklich an.',
    'security_rest_your_head_back_against_the_cushion__eyes_half_closed__relaxed_and_unguarded_':
        'Lehnen Sie Ihren Kopf mit halb geschlossenen Augen entspannt und unvorbereitet gegen das Kissen.',
    'security_rest_your_palms_flat_on_the_table__leaning_back_slightly__breathing_slowly_and_steadily_':
        'Legen Sie Ihre Handflächen flach auf den Tisch, lehnen Sie sich leicht zurück und atmen Sie langsam und gleichmäßig.',
    'security_sit_at_a_rooftop_bar__elbows_on_the_railing__looking_out_at_the_night_view_lazily_':
        'Setzen Sie sich an eine Bar auf dem Dach, stützen Sie die Ellenbogen auf das Geländer und schauen Sie träge auf die Nachtansicht hinaus.',
    'security_sit_at_a_table_with_a_drink_nearby__glancing_up_like_you_noticed_me_':
        'Setzen Sie sich an einen Tisch mit einem Getränk in der Nähe und schauen Sie auf, als ob Sie mich bemerkt hätten.',
    'security_sit_at_an_outdoor_caf___one_hand_around_a_glass__relaxed_posture_':
        'Sitzen Sie in einem Straßencafé, eine Hand um ein Glas, entspannte Haltung.',
    'security_sit_back_in_a_chair__legs_relaxed__eyes_steady_on_me_':
        'Lehnen Sie sich mit entspannten Beinen in einem Stuhl zurück, den Blick fest auf mich gerichtet.',
    'security_sit_by_the_pool_in_a_swimsuit__holding_a_cocktail_and_smiling_':
        'Sitzen Sie im Badeanzug am Pool, halten Sie einen Cocktail in der Hand und lächeln Sie.',
    'security_sit_by_the_window_with_soft_light_on_your_face__slowly_looking_at_me_':
        'Setze dich mit sanftem Licht auf dein Gesicht ans Fenster und schaue mich langsam an.',
    'security_sit_close_to_the_camera__relaxed_and_at_ease_':
        'Setzen Sie sich entspannt und entspannt in die Nähe der Kamera.',
    'security_sit_in_a_quiet_room__warm_light_behind_you__calm_and_unhurried_':
        'Setzen Sie sich in einen ruhigen Raum, warmes Licht hinter sich, ruhig und ohne Eile.',
    'security_sit_in_a_rattan_chair__rocking_it_gently__body_loose_and_eyes_peaceful_':
        'Setzen Sie sich auf einen Rattanstuhl und schaukeln Sie ihn sanft, mit entspanntem Körper und ruhigen Augen.',
    'security_sit_in_a_softly_lit_room__body_relaxed__attention_forward_':
        'Setzen Sie sich in einen sanft beleuchteten Raum, mit entspanntem Körper und nach vorne gerichteter Aufmerksamkeit.',
    'security_sit_on_a_balcony_at_night__city_lights_behind_you_':
        'Sitzen Sie nachts auf einem Balkon, die Lichter der Stadt im Rücken.',
    'security_sit_on_a_garden_bench__surrounded_by_faint_floral_scent__hands_resting_on_the_sides_quietly_':
        'Setzen Sie sich auf eine Gartenbank, umgeben von einem schwachen Blumenduft, und legen Sie die Hände ruhig auf die Seiten.',
    'security_sit_on_a_terrace__breeze_moving_slightly_as_you_look_over_':
        'Setzen Sie sich auf eine Terrasse und lassen Sie die Brise leicht wehen, während Sie hinüberblicken.',
    'security_sit_on_the_edge_of_the_bed__bare_feet_on_the_carpet__looking_relaxed_and_quiet_':
        'Setzen Sie sich mit bloßen Füßen auf den Teppich auf die Bettkante und sehen Sie entspannt und ruhig aus.',
    'security_stand_by_the_floor_to_ceiling_window__silhouette_against_the_sky__staring_into_the_distance_softly_':
        'Stellen Sie sich mit der Silhouette gegen den Himmel an das vom Boden bis zur Decke reichende Fenster und starren Sie sanft in die Ferne.',
    'security_stand_in_a_dimly_lit_hallway__light_outlining_your_figure__looking_at_me_calmly_':
        'Stellen Sie sich in einen schwach beleuchteten Flur, das Licht beleuchtet Ihre Figur und schauen Sie mich ruhig an.',
    'security_stand_in_the_warm_sunlight__closing_your_eyes_briefly__then_opening_them_to_look_at_me_':
        'Stehen Sie im warmen Sonnenlicht, schließen Sie kurz Ihre Augen und öffnen Sie sie dann, um mich anzusehen.',
    'security_stand_near_a_railing__resting_one_arm_while_watching_quietly_':
        'Stellen Sie sich in die Nähe eines Geländers, stützen Sie einen Arm ab und schauen Sie ruhig zu.',
    'security_stand_near_the_pool__water_reflecting_while_you_take_a_slow_sip_':
        'Stellen Sie sich in die Nähe des Pools und lassen Sie das Wasser spiegeln, während Sie langsam einen Schluck trinken.',
    'security_stretch_slightly_in_your_seat__then_settle_back_comfortably_':
        'Dehnen Sie sich leicht in Ihrem Sitz und lehnen Sie sich dann bequem zurück.',
    'security_stretch_your_arms_overhead_lazily__then_drop_them_down__slumping_comfortably_in_the_chair_':
        'Strecken Sie Ihre Arme träge über den Kopf, lassen Sie sie dann nach unten fallen und lassen Sie sich bequem auf dem Stuhl nieder.',
    'security_tilt_your_glass_slowly__swirling_the_drink_inside__watching_me_with_a_faint_smile_':
        'Kippen Sie Ihr Glas langsam, schwenken Sie das Getränk darin und beobachten Sie mich mit einem schwachen Lächeln.',
    'security_turn_toward_me_slowly__like_I_just_arrived_':
        'Drehe dich langsam zu mir um, als wäre ich gerade erst angekommen.',
    'security_twist_the_ring_on_your_finger_gently__eyes_thoughtful_as_you_fix_your_gaze_on_me_':
        'Drehen Sie den Ring an Ihrem Finger sanft und blicken Sie nachdenklich, während Sie Ihren Blick auf mich richten.',
    'security_wrap_your_arms_around_your_knees__sitting_curled_up_slightly__eyes_warm_on_me_':
        'Schlingen Sie Ihre Arme um Ihre Knie, sitzen Sie leicht zusammengerollt und blicken Sie mich warm an.',
    'security_create_your_account': 'Erstellen Sie Ihr Konto',
    'security_input_content_here__Option_':
        'Geben Sie hier Inhalte ein (Option)',
    'security_mina_Team': 'Mina-Team',
    'security_story_background': 'Hintergrund der Geschichte',
    'security_tap_to_continue___': 'Tippen Sie, um fortzufahren...',
    'security_aI_Character': 'KI-Charakter',
    'security_ask_for_pic': 'Bitte um Bild',
    'security_ask_for_video': 'Bitten Sie um ein Video',
    'security_before_creation__please_review':
        'Bitte vor der Erstellung überprüfen',
    'security_coins_balance': 'Münzguthaben',
    'security_fail_to_collect': 'Einsammeln fehlgeschlagen',
    'security_gems_balance': 'Edelsteine-Gleichgewicht',
    'security_mM_dd__HH_mm_': 'MM月dd日 HH时mm分',
    'security_my_Coins': 'Münzen',
    'security_my_Gems': 'Edelsteine',
    'security_notice__AI_responses_are_fictional_and_for_entertainment_only':
        'Hinweis: KI-Antworten sind fiktiv und dienen nur der Unterhaltung',
    'security_plus_button_tapped': 'Plus-Taste angetippt',
    'security_start_Create': 'Erstellen starten',
    'security_unsupported_message_type': 'Nicht unterstützter Nachrichtentyp',
    'security_voice_button_tapped': 'Sprachtaste angetippt',
    'security_All_Chat': 'Alle Chats',
    'security_Create_Video': 'Video erstellen',
    'security_Generate_Video': 'Video generieren',
    'security_Mina_Support': 'Mina-Unterstützung',
    'security_No_groups_yet__go_create_one_':
        'Noch keine Gruppen, erstellen Sie eine!',
    'security_Please_input_description':
        'Bitte geben Sie eine Beschreibung ein',
    'security_Search_by_ID__name__tag___': 'Suche nach ID, Name, Tag...',
    'security_The_app_may_not_function_as_expected_until_you_remove_this_plugin_from_pubspec_yaml':
        'Die App funktioniert möglicherweise nicht wie erwartet, bis Sie dieses Plugin aus pubspec.yaml entfernen',
    'security_Video_initialization_failed':
        'Die Videoinitialisierung ist fehlgeschlagen',
    'security_Got_coins_reward': 'Ich habe Münzen als Belohnung erhalten',
    'security_Unlock_this_photo': 'Dieses Foto entsperren',
    'security_Unlocked_successfully': 'Erfolgreich entsperrt',
    'security_Your_balance': 'Ihr Guthaben',
    'security_language': 'Sprache',
    'security_select_language': 'Sprache auswählen',
    'security_settings': 'Einstellungen',
  };
}
