// Generated by toolchain/translate/generate_copywriting_localizations.py.
// Edit Copywriting or the generator instead of changing keys by hand.

abstract final class CopywritingStringsAr {
  static const Map<String, String> values = <String, String>{
    'security_about_her': 'عنها',
    'security_account_Deletion': 'حذف الحساب',
    'security_add_rounds': 'أضف جولات',
    'security_all_Gender': 'جميع الجنسين',
    'security_appears_exclusively_in_your_character__s_public_profile_This_biographical_information_will_not_be_utilized_in_generation_prompts_or_influence_behavioral_patterns_':
        'تظهر حصريًا في الملف الشخصي العام لشخصيتك. لن يتم استخدام معلومات السيرة الذاتية هذه في مطالبات الإنشاء أو التأثير على الأنماط السلوكية.',
    'security_are_you_sure_you_want_to_delete_your_account_':
        'هل أنت متأكد أنك تريد حذف حسابك؟',
    'security_are_you_sure_you_want_to_log_out_':
        'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    'security_audio_Library': 'المكتبة الصوتية',
    'security_audio_input_is_too_short_to_send_':
        'إدخال الصوت قصير جدًا بحيث لا يمكن إرساله.',
    'security_avatar_upload_failed__please_try_again_later_':
        'فشل تحميل الصورة الرمزية، يرجى المحاولة مرة أخرى لاحقًا.',
    'security_avatar_uploaded': 'تم تحميل الصورة الرمزية',
    'security_birth_date': 'تاريخ الميلاد',
    'security_by_clicking_Security_security_Subscribe__you_will_be_charged__and_your_subscription_will_automatically_renew_at_the_same_price_and_duration_until_canceled_through_PlayStore_settings__By_proceeding__you_agree_to_our_terms_':
        'بالضغط على Security.security_Subscribe، سيتم محاسبتك، وسيتم تجديد اشتراكك تلقائيًا بنفس السعر والمدة حتى يتم إلغاؤه من خلال إعدادات PlayStore. من خلال المتابعة، فإنك توافق على شروطنا.',
    'security_call_Duration': 'مدة المكالمة',
    'security_cannot_get_information__please_retry_later':
        'لا يمكن الحصول على المعلومات، يرجى إعادة المحاولة لاحقًا',
    'security_cannot_get_physique_details__please_retry_later':
        'لا يمكن الحصول على تفاصيل اللياقة البدنية، يرجى إعادة المحاولة لاحقًا',
    'security_cannot_open_date_picker__please_retry_later':
        'لا يمكن فتح منتقي التاريخ، يرجى إعادة المحاولة لاحقًا',
    'security_click_to_add': 'انقر للإضافة',
    'security_click_to_play': 'انقر للعب',
    'security_coin_balance': 'رصيد العملة',
    'security_connecting___': 'جارٍ الاتصال...',
    'security_copyright_Agreement': 'اتفاقية حقوق النشر',
    'security_create_My_Character': 'إنشاء شخصيتي',
    'security_create_Now': 'أنشئ الآن',
    'security_create_an_account': 'إنشاء حساب',
    'security_current_device_not_support__try_restart_app_':
        'الجهاز الحالي لا يدعم، حاول إعادة تشغيل التطبيق.',
    'security_defines_the_conversational_patterns_between_you_and_your_character__This_crucial_setting_determines_how_your_character_formulates_responses_and_maintains_personality_consistency_':
        'يحدد أنماط المحادثة بينك وبين شخصيتك. يحدد هذا الإعداد الحاسم كيفية صياغة شخصيتك للاستجابات والحفاظ على اتساق الشخصية.',
    'security_delete_account_': 'هل تريد حذف الحساب؟',
    'security_deleting___': 'جارٍ الحذف...',
    'security_describe_the_conversation_scenario_and_involved_characters_':
        'وصف سيناريو المحادثة والشخصيات المعنية.',
    'security_describe_the_issue': 'قم بوصف المشكلة',
    'security_dialogue_Style': 'أسلوب الحوار',
    'security_edit_information': 'تحرير المعلومات',
    'security_enter_verification_code': 'أدخل رمز التحقق',
    'security_entry_your_email': 'أدخل بريدك الإلكتروني',
    'security_expires_on': 'تنتهي صلاحيته في',
    'security_failed_to_follow': 'فشل في المتابعة',
    'security_failed_to_load_subscription_data': 'فشل تحميل بيانات الاشتراك',
    'security_failed_to_process_subscription__please_try_again_later_':
        'فشلت معالجة الاشتراك، يرجى المحاولة مرة أخرى لاحقًا.',
    'security_failed_to_record_audio__please_try_again':
        'فشل تسجيل الصوت، يرجى المحاولة مرة أخرى',
    'security_failed_to_send_gift': 'فشل في إرسال الهدية',
    'security_failed_to_unfollow': 'تعذّر إلغاء المتابعة',
    'security_failed_to_update__please_retry_later':
        'فشل التحديث، يرجى إعادة المحاولة لاحقًا',
    'security_feelie_Pro': 'فيلي برو',
    'security_fill_in_your_introduction___': 'أكمل المقدمة الخاصة بك...',
    'security_following_the_regeneration_process__you_ll_receive_a_brand_new_image__You_are_also_welcome_to_revisit_the_images_you_created_earlier__Are_you_ready_to_move_forward_':
        'بعد عملية التجديد، سوف تتلقى صورة جديدة تمامًا. نرحب أيضًا بإعادة زيارة الصور التي قمت بإنشائها مسبقًا. هل أنت مستعد للمضي قدما؟',
    'security_for_example___On_the_moonlit_balcony_of_a_neo___Victorian_mansion__an_ethereal_woman_with_bright_blue_hime___cut_hair':
        'على سبيل المثال، "على الشرفة المضاءة بنور القمر في قصر فيكتوري جديد، توجد امرأة أثيرية ذات شعر هيم أزرق لامع',
    'security_gem_balance': 'توازن الجوهرة',
    'security_generating_in_progress': 'جاري الإنشاء',
    'security_generating___': 'جارٍ الإنشاء...',
    'security_get_full_access_': 'الحصول على الوصول الكامل!',
    'security_hold_to_talk': 'عقد للحديث',
    'security_how_would_you_like_OC_to_address_you_': 'كيف تريد أن يخاطبك OC؟',
    'security_image_Prompt': 'موجه الصورة',
    'security_information_updated_': 'تم تحديث المعلومات.',
    'security_insufficient_balance_': 'رصيد غير كاف.',
    'security_interrupt_AI': 'مقاطعة الذكاء الاصطناعي',
    'security_loading___': 'تحميل...',
    'security_log_out': 'تسجيل الخروج',
    'security_logging_in___': 'تسجيل الدخول...',
    'security_master_name_must_be_2_24_characters_in_length':
        'يجب أن يتراوح طول الاسم الرئيسي من 2 إلى 24 حرفًا',
    'security_modify_Now': 'تعديل الآن',
    'security_name_your_character': 'قم بتسمية شخصيتك',
    'security_network_error': 'خطأ في الشبكة',
    'security_network_error__please_try_again_later':
        'حدث خطأ في الشبكة، يرجى المحاولة مرة أخرى لاحقًا',
    'security_network_exception__please_try_again_later':
        'استثناء في الشبكة، يرجى المحاولة مرة أخرى لاحقًا',
    'security_no_chat_partner_has_been_initiated_yet':
        'لم يتم بدء أي شريك دردشة حتى الآن',
    'security_no_companions_yet': 'لا يوجد رفاق بعد',
    'security_no_data': 'لا توجد بيانات',
    'security_no_user_information__getting_back___':
        'لا توجد معلومات للمستخدم، جارٍ الرجوع...',
    'security_notice__Everything_AI_says_is_made_up':
        'ملاحظة: كل ما يقوله الذكاء الاصطناعي مُختلق',
    'security_obtain_code': 'الحصول على الرمز',
    'security_platform_not_supported_': 'النظام الأساسي غير مدعوم.',
    'security_please_agree_to_the_terms_and_conditions':
        'يرجى الموافقة على الشروط والأحكام',
    'security_please_select_a_product_to_recharge_':
        'الرجاء تحديد منتج لإعادة الشحن.',
    'security_premium_Benefits_for_Audio__unlimited':
        'فوائد مميزة للصوت، غير محدودة',
    'security_prior_to_the_creation_process__please_review_our':
        'قبل عملية الإنشاء، يرجى مراجعة موقعنا',
    'security_privacy_Policy': 'سياسة الخصوصية',
    'security_privacy_policy': 'سياسة الخصوصية',
    'security_pro_Free': 'برو مجاني',
    'security_pro_only': 'للمحترفين فقط',
    'security_purchase_done': 'تم الشراء',
    'security_purchased_Success': 'نجاح الشراء',
    'security_purchasing___': 'شراء...',
    'security_recharge_failed_': 'فشلت عملية إعادة الشحن.',
    'security_regeneration_Tips': 'نصائح التجديد',
    'security_release_Cancel': 'الافراج عن إلغاء',
    'security_release_Send': 'الافراج عن إرسال',
    'security_role_image': 'صورة الدور',
    'security_sF_Pro': 'SF Pro',
    'security_sF_Pro_bold': 'SF Pro bold',
    'security_select_from_gallery': 'اختر من المعرض',
    'security_select_from_the_album': 'اختر من الألبوم',
    'security_selected_date_is_out_of_range_': 'التاريخ المحدد خارج النطاق.',
    'security_send_failed__please_try_again_later':
        'فشل الإرسال، يرجى المحاولة مرة أخرى لاحقًا',
    'security_send_message__reply_by_AI':
        'إرسال رسالة، الرد عن طريق منظمة العفو الدولية',
    'security_sending___': 'إرسال...',
    'security_sign_in_with_Apple': 'تسجيل الدخول مع أبل',
    'security_sign_in_with_E_mail': 'تسجيل الدخول باستخدام البريد الإلكتروني',
    'security_start_create': 'ابدأ في الإنشاء',
    'security_submitted_successfully': 'تم الإرسال بنجاح',
    'security_supply_detailed_information_about_the_image__such_as_the_clothing_worn__facial_features__and_actions_':
        'توفير معلومات تفصيلية عن الصورة، مثل الملابس التي يتم ارتداؤها، وملامح الوجه، والحركات.',
    'security_take_it_with_camera': 'خذها مع الكاميرا',
    'security_terms_of_Service': 'شروط الخدمة',
    'security_terms_of_service': 'شروط الخدمة',
    'security_the_OC_will_address_you_by_the_name_you_enter_':
        'سوف يخاطبك OC بالاسم الذي تدخله.',
    'security_the_character_creation_is_still_ongoing__Leaving_at_this_moment_will_forfeit_the_progress_made_so_far__Are_you_sure_you_want_to_go_back_':
        'لا يزال إنشاء الشخصية مستمرًا. إن الخروج في هذه اللحظة سيفقد التقدم الذي تم إحرازه حتى الآن. هل أنت متأكد أنك تريد العودة؟',
    'security_the_uploaded_image_serves_as_a_reference_for_facial_features_and_style_elements':
        'تعمل الصورة التي تم تحميلها كمرجع لملامح الوجه وعناصر النمط',
    'security_turn_on_the_camera': 'قم بتشغيل الكاميرا',
    'security_unable_to_get_recharge_service__please_retry_later_':
        'تعذر الحصول على خدمة إعادة الشحن، يرجى إعادة المحاولة لاحقًا.',
    'security_unknown_error__please_upload_again_':
        'خطأ غير معروف، يرجى التحميل مرة أخرى.',
    'security_unlock_Audio': 'فتح الصوت',
    'security_unlock_Image': 'فتح الصورة',
    'security_unlock_Video': 'فتح الفيديو',
    'security_updating_information___': 'جارٍ تحديث المعلومات...',
    'security_upload_failed__please_try_again_later':
        'فشل التحميل، يرجى المحاولة مرة أخرى في وقت لاحق',
    'security_uploading_new_avatar___': 'جارٍ تحميل الصورة الرمزية الجديدة...',
    'security_you_have_muted': 'لقد كتمت',
    'security_supply_detailed_information_about_the_image__such_as_the_clothing_worn__facial_features__and_actions__For_example___On_the_moonlit_balcony_of_a_neo___Victorian_mansion__an_ethereal_woman_with_bright_blue_hime___cut_hair_leans_against_the_railing__Her_khaki_backless_sweater_flutters_gently_in_the_breeze_as_she_turns_to_look_at_the_viewer_with_an_otherworldly_serenity__':
        'توفير معلومات تفصيلية عن الصورة، مثل الملابس التي يتم ارتداؤها، وملامح الوجه، والحركات. على سبيل المثال، "على شرفة قصر فيكتوري مضاءة بنور القمر، تتكئ امرأة أثيرية ذات شعر أزرق لامع على الدرابزين. ترفرف سترتها الكاكي بدون ظهر بلطف مع النسيم وهي تستدير لتنظر إلى المشاهد بهدوء من عالم آخر."',
    'security_cannot_download_source__please_try_again_later':
        'لا يمكن تحميل المصدر، يرجى المحاولة مرة أخرى في وقت لاحق',
    'security_if_you_sign_in__you_agree_to':
        'إذا قمت بتسجيل الدخول، فإنك توافق على',
    'security_send_me_a_picture': 'ارسل لي صورة',
    'security_send_me_a_video': 'أرسل لي فيديو',
    'security_and_indicate_your_consent_': 'والإشارة إلى موافقتك.',
    'security_consuming_props_during_call': 'استهلاك الدعائم أثناء المكالمة',
    'security_no_more_companions_to_load_': 'لا مزيد من الرفاق للتحميل.',
    'security_per_minute': 'في الدقيقة',
    'security_edit': 'يحرر',
    'security_video_Call': 'مكالمة فيديو',
    'security_i_am_listening___': 'أنا أستمع...',
    'security_i_am_thinking___': 'أنا أفكر...',
    'security_audio_Call': 'مكالمة صوتية',
    'security_canceled_by_caller': 'تم الإلغاء بواسطة المتصل',
    'security_no_answer__please_try_again_later':
        'لا توجد إجابة، يرجى المحاولة مرة أخرى في وقت لاحق',
    'security_no_favorites_yet__go_and_follow_some_people_':
        'لا يوجد مفضلة بعد، اذهب وتابع بعض الأشخاص!',
    'security_benefits_Usage_Detail': 'تفاصيل الاستخدام الفوائد',
    'security_chat_beyond_reality__role_play_without_limits':
        'الدردشة خارج الواقع، لعب الأدوار بلا حدود',
    'security_please_grant_camera_permission': 'يرجى منح إذن الكاميرا',
    'security_please_grant_microphone_permission': 'يرجى منح إذن الميكروفون',
    'security_unlocking_for_free_': 'فتح مجانا!',
    'security_you__re_now_a_premium_member__nYour_benefits_are_unlocked__nExplore_your_new_perks_':
        'أنت الآن عضو مميز!\\nلقد أصبحت مزاياك متاحة.\\nاستكشف المزايا الجديدة!',
    'security_by_clicking_subscribe__you_will_be_charged__and_your_subscription_will_automatically_renew_at_the_same_price_and_duration_until_canceled_through_App_Store_settings__By_proceeding__you_agree_to_our_terms_':
        'بالضغط على اشتراك، سيتم محاسبتك، وسيتم تجديد اشتراكك تلقائيًا بنفس السعر والمدة حتى يتم إلغاؤه من خلال إعدادات متجر التطبيقات. من خلال المتابعة، فإنك توافق على شروطنا.',
    'security_daily_Task': 'المهمة اليومية',
    'security_premium_Only': 'بريميوم فقط',
    'security_introduction': 'مقدمة',
    'security_premium_Free': 'قسط مجاني',
    'security_an_error_occurred__please_try_again_later_':
        'حدث خطأ، يرجى المحاولة مرة أخرى في وقت لاحق.',
    'security_product_id_not_found__please_try_again_later':
        'لم يتم العثور على معرف المنتج، يرجى المحاولة مرة أخرى في وقت لاحق',
    'security_call_wasn__t_answered': 'لم يتم الرد على المكالمة',
    'security_cancelled_by_Caller': 'تم الإلغاء بواسطة المتصل',
    'security_consuming_gems_during_call':
        'استهلاك الأحجار الكريمة أثناء المكالمة',
    'security_ending___': 'إنهاء...',
    'security_free_Call': 'مكالمة مجانية',
    'security_not_enough_gems__please_recharge':
        'لا يوجد ما يكفي من الأحجار الكريمة، يرجى إعادة الشحن',
    'security_send_a_message_': 'أرسل رسالة…',
    'security_free_for_first': 'مجانا لأول مرة',
    'security_error__max_should_not_be_a_negative_number_or_zero':
        'خطأ، يجب ألا يكون الحد الأقصى رقمًا سالبًا أو صفرًا',
    'security_error__min_is_greater_than_or_equal_to_max':
        'خطأ، الحد الأدنى أكبر من أو يساوي الحد الأقصى',
    'security_invites_you': 'يدعوك',
    'security_aD_Free': 'إعلان مجاني',
    'security_enter_your_image_prompt__e_g__A_girl__sitting_on_a_bench___':
        'أدخل موجه الصورة الخاص بك، على سبيل المثال. فتاة تجلس على مقعد...',
    'security_failed_to_grant_coin__Please_try_again_later_':
        'فشل منح العملة. يرجى المحاولة مرة أخرى في وقت لاحق.',
    'security_failed_to_unlock_resource__Please_try_again_later_':
        'فشل في فتح المورد. يرجى المحاولة مرة أخرى في وقت لاحق.',
    'security_image_prompt_cannot_be_empty':
        'لا يمكن ترك رسالة المطالبة بالصورة فارغة',
    'security_images_you_like': 'الصور التي تريدها',
    'security_please_select_at_least_one_prompt':
        'الرجاء تحديد مطالبة واحدة على الأقل',
    'security_signing_in___': 'تسجيل الدخول...',
    'security_all_Chat': 'كل الدردشة',
    'security_chat_Models': 'نماذج الدردشة',
    'security_chat_Now': 'الدردشة الآن',
    'security_clear_Chat_History': 'مسح سجل الدردشة',
    'security_connect_with_everyone_in_one_place':
        'تواصل مع الجميع في مكان واحد',
    'security_contact_us_for_support_': 'اتصل بنا للحصول على الدعم.',
    'security_delete_Message': 'حذف الرسالة',
    'security_design_your_own_unique_character_and_bring_it_to_life_':
        'صمم شخصيتك الفريدة واجعلها تنبض بالحياة.',
    'security_group_Chat': 'دردشة جماعية',
    'security_limited_Free': 'مجانية محدودة',
    'security_mark_all_as_read': 'وضع علامة على الكل كمقروءة',
    'security_message_Setting': 'إعداد الرسالة',
    'security_message_setting': 'إعداد الرسالة',
    'security_reset_Success_': 'إعادة تعيين النجاح!',
    'security_rewind_to_here': 'الترجيع إلى هنا',
    'security_she_will_forget_conversation_history_with_you_':
        'سوف تنسى تاريخ المحادثة معك!',
    'security_shield_Real__s_Messages': 'رسائل Shield Real',
    'security_soulink_Team': 'فريق سولينك',
    'security_switch_Failed': 'فشل التبديل',
    'security_switch_Succeed_enjoy_your_chat':
        'نجاح التبديل، استمتع بالدردشة الخاصة بك',
    'security_switch_the_Model': 'تبديل النموذج',
    'security_contact_us': 'اتصل بنا',
    'security_iAP_Service_Not_Available': 'خدمة IAP غير متوفرة',
    'security_iAP_not_available__restart_the_app_and_try_again_':
        'الشراء داخل التطبيق غير متاح، أعد تشغيل التطبيق وحاول مرة أخرى.',
    'security_item_info_error': 'خطأ في معلومات العنصر',
    'security_monthly_Premium': 'القسط الشهري',
    'security_no_recharge_item_available__try_again_later':
        'لا يوجد عنصر إعادة شحن متاح، حاول مرة أخرى لاحقًا',
    'security_payment_failed': 'فشل الدفع',
    'security_payment_successful': 'تم الدفع بنجاح',
    'security_purchase_successful': 'تم الشراء بنجاح',
    'security_receipt_Not_Available': 'الإيصال غير متوفر',
    'security_special_Offer': 'عرض خاص',
    'security_weekly_Premium': 'قسط أسبوعي',
    'security_yearly_Premium': 'قسط سنوي',
    'security_about_AI_MODE': 'حول وضع الذكاء الاصطناعي',
    'security_about_Me': 'ْعَنِّي',
    'security_add_Group_Member': 'إضافة عضو المجموعة',
    'security_add_New_Group_Member': 'إضافة عضو جديد في المجموعة',
    'security_are_you_sure_you_want_to_disband_this_group__This_action_cannot_be_undone__and_all_members_will_be_removed_':
        'هل أنت متأكد أنك تريد حل هذه المجموعة؟ لا يمكن التراجع عن هذا الإجراء، وسيتم إزالة جميع الأعضاء.',
    'security_auto___enabled__The_mentioned_member_s__will_reply_your_message_':
        'تلقائي @ ممكّن. سيقوم العضو (الأعضاء) المذكورين بالرد على رسالتك.',
    'security_click_anywhere_to_continue___': 'انقر في أي مكان للمتابعة...',
    'security_congratulations__You_got_a_new_MODE__enjoy_it_':
        'تهانينا! لقد حصلت على وضع جديد، استمتع به.',
    'security_contact_List': 'قائمة الاتصال',
    'security_create_Group': 'إنشاء مجموعة',
    'security_dating_Game': 'لعبة المواعدة',
    'security_disband_Group': 'حل المجموعة',
    'security_disband_Group_': 'حل المجموعة؟',
    'security_download_failed__please_retry_later_':
        'فشل التنزيل، يرجى إعادة المحاولة لاحقًا!',
    'security_edit_Group_Name': 'تحرير اسم المجموعة',
    'security_edit_Group_Scenario': 'تحرير سيناريو المجموعة',
    'security_enter_the_Group_Scenario': 'أدخل سيناريو المجموعة',
    'security_enter_the_group_name': 'أدخل اسم المجموعة',
    'security_error_occurred__please_try_again':
        'حدث خطأ، يرجى المحاولة مرة أخرى',
    'security_go_Play': 'اذهب للعب',
    'security_group_Info': 'معلومات المجموعة',
    'security_group_Member': 'عضو المجموعة',
    'security_group_Name': 'اسم المجموعة',
    'security_group_Owner': 'مالك المجموعة',
    'security_group_Scenario': 'سيناريو المجموعة',
    'security_in_Use': 'قيد الاستخدام',
    'security_in_use': 'قيد الاستخدام',
    'security_level_Up_': 'المستوى الأعلى!',
    'security_my_OCs': 'بلدي OC',
    'security_not_enough_balance': 'لا يوجد رصيد كافي',
    'security_please_agree_to_the_terms_below_first_':
        'يرجى الموافقة على الشروط أدناه أولاً.',
    'security_popular_Search': 'بحث شعبي',
    'security_recent_Search': 'البحث الأخير',
    'security_search_Failed': 'فشل البحث',
    'security_search_Users_by_ID_or_Name':
        'البحث عن المستخدمين حسب المعرف أو الاسم',
    'security_some_error_occur__please_retry_later_':
        'حدث بعض الأخطاء، يرجى إعادة المحاولة لاحقًا!',
    'security_some_error_occurred__try_again_later_':
        'حدث خطأ ما، حاول مرة أخرى لاحقًا.',
    'security_some_error_occurred__Please_try_again_later_':
        'حدث بعض الخطأ. يرجى المحاولة مرة أخرى في وقت لاحق.',
    'security_start_Game': 'ابدأ اللعبة',
    'security_switch_Succeed__enjoy_your_chat': 'نجح التبديل، استمتع بالدردشة',
    'security_switch_to_Chat': 'قم بالتبديل إلى الدردشة',
    'security_take_a_look__': 'ألقِ نظرة >',
    'security_the_MODE_will_only_take_effect_after_you_have_acquired_this_character__Continue_purchasing_':
        'لن يصبح الوضع ساري المفعول إلا بعد حصولك على هذه الشخصية. هل تريد مواصلة الشراء؟',
    'security_the_muted_member_will_not_reply_your_message':
        'العضو الذي تم كتم صوته لن يرد على رسالتك',
    'security_this_member_is_deactivated_': 'هذا العضو معطل.',
    'security_this_member_is_expired_': 'هذا العضو منتهي الصلاحية.',
    'security_time_limit': 'الحد الزمني',
    'security_try_it': 'جربه',
    'security_unlock_conditions_not_met__Upgrade_your_level_now_':
        'لم يتم استيفاء شروط فتح القفل. ترقية مستواك الآن!',
    'security_unlock_tips': 'فتح النصائح',
    'security_your_reward': 'مكافأتك',
    'security_edit_My_Character': 'تحرير شخصيتي',
    'security_message_Settings': 'إعدادات الرسالة',
    'security_no_datas__click_to_retry_':
        'لا توجد بيانات، انقر لإعادة المحاولة.',
    'security_start_Chat': 'ابدأ الدردشة',
    'security_send_a_message___': 'أرسل رسالة...',
    'security_send_me_a_pic_with_you_tucking_hair_behind_ear_in_sunset__Send_me_a_pic_with_you_touching_flower_petals_at_dusk__Send_me_a_pic_with_you_holding_teacup_by_rain_window__Send_me_a_pic_with_you_twirling_silk_scarf_by_the_lake__Send_me_a_pic_with_you_adjusting_shoelace_in_sunlight__Send_me_a_pic_with_you_skimming_calm_fountain_surface__Send_me_a_pic_with_you_wrapping_shawl_on_the_balcony':
        'أرسل لي صورة وأنت تدسين شعرك خلف أذنك عند غروب الشمس||أرسل لي صورة وأنت تلمسين بتلات الزهور عند الغسق||أرسل لي صورة وأنت تحملين فنجان شاي بجوار نافذة المطر||أرسل لي صورة وأنت تلتفين وشاحًا حريريًا بجوار البحيرة||أرسل لي صورة وأنت تقومين بتعديل رباط الحذاء في ضوء الشمس||أرسل لي صورة وأنت تمسحين سطح النافورة الهادئ||أرسل لي صورة وأنت تقومين بلف الشال على الشرفة',
    'security_nice_to_meet_you_': 'سعيد بلقائك!',
    'security_sign_in_with_Google': 'قم بتسجيل الدخول باستخدام جوجل',
    'security_failed_to_save__image_URL_is_empty':
        'فشل الحفظ، عنوان URL للصورة فارغ',
    'security_failed_to_save__try_again_later':
        'فشل الحفظ، أعد المحاولة لاحقًا',
    'security_failed_to_save__try_again_later_Data_Empty_':
        'فشل الحفظ، حاول مرة أخرى لاحقًا[البيانات فارغة]',
    'security_saved_successfully': 'تم الحفظ بنجاح',
    'security_saving___': 'توفير...',
    'security_scenario': 'سيناريو',
    'security_are_you_sure_you_want_to_block_this_user_':
        'هل أنت متأكد أنك تريد حظر هذا المستخدم؟',
    'security_bock_Messages_from_Strangers': 'رسائل بوك من الغرباء',
    'security_aI_Writer': 'كاتب الذكاء الاصطناعي',
    'security_permission_settings': 'إعدادات الأذونات',
    'security_the_existing_filled_content_will_be_replaced_by_the_template_content_and_cannot_be_undone_':
        'سيتم استبدال المحتوى المعبأ الحالي بمحتوى القالب ولا يمكن التراجع عنه.',
    'security_what_should_AI_call_you': 'ماذا يجب أن يناديك الذكاء الاصطناعي',
    'security_generation_failed__please_try_again_later_':
        'فشل الإنشاء، يرجى المحاولة مرة أخرى لاحقًا.',
    'security_copied_ID_to_clipboard': 'المعرف المنسوخ إلى الحافظة',
    'security_character_name_must_be_at_least_3_letters_':
        'يجب أن يتكون اسم الشخصية من 3 أحرف على الأقل.',
    'security_more_Details': 'مزيد من التفاصيل',
    'security_feedback_Log': 'سجل الملاحظات',
    'security_image_is_Not_ready__please_try_again_later_':
        'الصورة ليست جاهزة، يرجى المحاولة مرة أخرى في وقت لاحق.',
    'security_not_approved': 'غير معتمد',
    'security_under_review': 'قيد المراجعة',
    'security_upload_Log_success': 'نجاح تحميل السجل',
    'security_about_Soulink': 'حول سولينك',
    'security_are_you_sure_': 'هل أنت متأكد؟',
    'security_character_is_private': 'الشخصية خاصة',
    'security_complete_tasks_to_get_rewards': 'أكمل المهام للحصول على المكافآت',
    'security_cost_Trial_Card': 'بطاقة تجربة التكلفة',
    'security_create_Character': 'إنشاء شخصية',
    'security_create_Moment': 'خلق لحظة',
    'security_create_an_image_with_Generator': 'إنشاء صورة باستخدام المولد',
    'security_currently_owns_': 'يمتلك حاليا:',
    'security_daily_post_limit_exceeded': 'تم تجاوز حد النشر اليومي',
    'security_describe_what_you_want__e_g___A_barista_wipes_the_counter_of_a_small_caf__by_the_river__steam_rising_from_coffee_cups__boats_passing_slowly_outside_the_window__a_cat_napping_on_a_nearby_chair_':
        'صف ما تريد، على سبيل المثال، يقوم باريستا بمسح طاولة مقهى صغير بجوار النهر، والبخار يتصاعد من فناجين القهوة، والقوارب تمر ببطء خارج النافذة، وقطة تغفو على كرسي قريب.',
    'security_don_t_remind_me_again': 'لا تذكرني مرة أخرى',
    'security_enable_this_option_to_allow_the_AI_to_generate_image_galleries_based_on_your_information_':
        'قم بتمكين هذا الخيار للسماح للذكاء الاصطناعي بإنشاء معارض صور بناءً على معلوماتك.',
    'security_enter_the_Description': 'أدخل الوصف',
    'security_exit_Video_Matching_': 'هل تريد الخروج من مطابقة الفيديو؟',
    'security_failed_Generate': 'فشل الإنشاء',
    'security_failed_reload': 'فشلت عملية إعادة التحميل',
    'security_first_message_from_your_character__It_will_help_the_chat_get_off_to_a_better_start_':
        'أول رسالة من شخصيتك سيساعد ذلك في بدء الدردشة بشكل أفضل.',
    'security_for_You': 'لك',
    'security_generate_Video': 'توليد الفيديو',
    'security_generate_config_loading': 'إنشاء تحميل التكوين',
    'security_generate_for_Moment': 'توليد للحظة',
    'security_generate_video': 'توليد الفيديو',
    'security_generating_Gallery': 'معرض توليد',
    'security_get_30s_Free_Trial': 'احصل على نسخة تجريبية مجانية لمدة 30 ثانية',
    'security_go_Setting': 'اذهب إلى الإعداد',
    'security_grants_the_first_30_seconds_of_the_call_for_free__After_that__gems_will_be_charged_':
        'يمنح أول 30 ثانية من المكالمة مجانًا. بعد ذلك، سيتم شحن الأحجار الكريمة.',
    'security_i_understand': 'أفهم',
    'security_image_details__facial_features__clothing':
        'تفاصيل الصورة، ملامح الوجه، الملابس',
    'security_initial_Message': 'الرسالة الأولية',
    'security_invites_you_to_video_calling_': 'يدعوك لإجراء مكالمة فيديو...',
    'security_lets_you_make_calls_without_spending_gems_':
        'يتيح لك إجراء مكالمات دون إنفاق الأحجار الكريمة.',
    'security_mM_dd_HH_mm': 'MM-dd HH:mm',
    'security_just_now': 'الآن',
    'security_one_minute_ago': 'منذ دقيقة واحدة',
    'security_minutes_ago': 'منذ {count} د',
    'security_one_hour_ago': 'منذ ساعة واحدة',
    'security_hours_ago': 'منذ {count} س',
    'security_one_day_ago': 'منذ يوم واحد',
    'security_days_ago': 'منذ {count} يوم',
    'security_one_week_ago': 'منذ أسبوع واحد',
    'security_weeks_ago': 'منذ {count} أسبوع',
    'security_maximum_limit_exceeded': 'تم تجاوز الحد الأقصى',
    'security_no_report_reasons_available': 'لا توجد أسباب التقرير المتاحة',
    'security_operation_failed': 'فشلت العملية',
    'security_permission_required': 'الإذن مطلوب',
    'security_please_allow_access_to_the_camera_in_the_settings':
        'يرجى السماح بالوصول إلى الكاميرا في الإعدادات',
    'security_please_allow_access_to_the_microphone_in_the_settings':
        'يرجى السماح بالوصول إلى الميكروفون في الإعدادات',
    'security_please_input_description': 'الرجاء إدخال الوصف',
    'security_please_select_a_character_first': 'الرجاء تحديد حرف أولا',
    'security_post_As': 'نشر باسم',
    'security_post_successful': 'مشاركة ناجحة',
    'security_post_updates_for_your_character_and_bring_every_moment_of_their_story_to_life_':
        'انشر تحديثات لشخصيتك وأضف الحيوية على كل لحظة من قصتهم!',
    'security_post_your_reply': 'انشر ردك',
    'security_report_Success_': 'تقرير النجاح!',
    'security_select_From_Chat_History_Album': 'اختر من ألبوم محفوظات الدردشة',
    'security_select_Image': 'حدد الصورة',
    'security_select_a_Character': 'حدد حرفًا',
    'security_start_Match': 'ابدأ المباراة',
    'security_switching_characters_will_clear_the_current_content':
        'سيؤدي تبديل الأحرف إلى مسح المحتوى الحالي',
    'security_the_user_has_been_matched__and_the_other_party_accepts_and_enters_the_video_call':
        'تمت مطابقة المستخدم، ويقبل الطرف الآخر مكالمة الفيديو ويدخل فيها',
    'security_this_moment_does_not_meet_community_requirements__please_edit':
        'هذه اللحظة لا تلبي متطلبات المجتمع، يرجى التعديل',
    'security_translation_failure_': 'فشل الترجمة...',
    'security_you_need_to_have_your_own_role_to_post___nGo_create_a_character':
        'يجب أن يكون لديك دورك الخاص للنشر! \\nاذهب لإنشاء شخصية',
    'security_you_re_now_using_your_trial_card_or_available_call_time___whichever_applies_':
        'أنت الآن تستخدم بطاقتك التجريبية أو وقت الاتصال المتاح — أيهما ينطبق.',
    'security_please_grant_storage_permission': 'يرجى منح إذن التخزين',
    'security_brush_a_strand_of_hair_back_gently__eyes_soft_as_you_gaze_straight_at_me_':
        'قم بتمشيط خصلة من الشعر بلطف، وعينيك ناعمتان وأنت تنظر إلي مباشرة.',
    'security_hold_a_book_loosely_in_your_hand__flipping_a_page_slowly_as_you_glance_up_':
        'أمسك كتابًا في يدك بشكل غير محكم، واقلب الصفحة ببطء وأنت تنظر للأعلى.',
    'security_hold_a_cup_of_warm_drink__blowing_on_it_softly_before_taking_a_small_sip_':
        'أمسك كوبًا من المشروب الدافئ، وانفخ عليه بهدوء قبل أن تأخذ رشفة صغيرة.',
    'security_lean_against_a_bar_counter__drink_in_hand__shoulders_loose_':
        'استند إلى طاولة البار، واشرب في يدك، وأكتافك فضفاضة.',
    'security_lean_against_a_bookshelf__one_hand_brushing_the_spines__calm_and_unhurried_':
        'اتكئ على رف الكتب، بيد واحدة تمسح الأشواك، هادئًا وغير مستعجل.',
    'security_lean_against_a_wall__arms_loosely_crossed__watching_me_':
        'استند إلى الحائط، وذراعيه متقاطعتين بشكل غير محكم، يراقبني.',
    'security_lean_against_the_door_frame__one_leg_crossed_casually__smiling_as_you_watch_me_approach_':
        'اتكئ على إطار الباب، واضعًا ساقًا واحدة فوق الأخرى، وابتسم وأنت تشاهدني أقترب.',
    'security_lean_forward_a_little__head_tilted__listening_intently_with_a_calm_expression_':
        'انحنِ إلى الأمام قليلاً، ورأسك مائل، واستمع باهتمام مع تعبير هادئ.',
    'security_lounge_on_a_pool_chair__sunglasses_pushed_up_as_you_glance_over_':
        'استرخ على كرسي حمام السباحة، ونظارتك الشمسية مرفوعة لأعلى وأنت تنظر إليها.',
    'security_relax_on_a_couch__one_arm_resting_casually_as_you_smile_':
        'استرخ على الأريكة، مع وضع إحدى ذراعيك في وضع مريح بينما تبتسم.',
    'security_relax_on_a_sofa_in_the_evening__warm_lights_around_you_':
        'استرخ على الأريكة في المساء، والأضواء الدافئة من حولك.',
    'security_rest_one_elbow_on_the_table__fingers_tapping_lightly_as_you_smile_lazily_':
        'ضع مرفقك على الطاولة، مع النقر بأصابعك بخفة بينما تبتسم بتكاسل.',
    'security_rest_your_chin_on_your_hand__looking_at_me_thoughtfully_':
        'ضع ذقنك على يدك، وانظر إلي بتمعن.',
    'security_rest_your_head_back_against_the_cushion__eyes_half_closed__relaxed_and_unguarded_':
        'أسند رأسك إلى الخلف على الوسادة، وعيناك نصف مغمضتين، مسترخيتين ومن دون حراسة.',
    'security_rest_your_palms_flat_on_the_table__leaning_back_slightly__breathing_slowly_and_steadily_':
        'ضع راحتي يديك بشكل مسطح على الطاولة، متكئًا للخلف قليلًا، وتنفس ببطء وثبات.',
    'security_sit_at_a_rooftop_bar__elbows_on_the_railing__looking_out_at_the_night_view_lazily_':
        'اجلس في حانة على السطح، واضعًا مرفقيك على الدرابزين، وانظر إلى المنظر الليلي بتكاسل.',
    'security_sit_at_a_table_with_a_drink_nearby__glancing_up_like_you_noticed_me_':
        'اجلس على طاولة وتناول مشروبًا بالقرب منك، وانظر للأعلى وكأنك لاحظتني.',
    'security_sit_at_an_outdoor_caf___one_hand_around_a_glass__relaxed_posture_':
        'اجلس في مقهى خارجي، واضعًا إحدى يديك حول كأس، في وضعية استرخاء.',
    'security_sit_back_in_a_chair__legs_relaxed__eyes_steady_on_me_':
        'اجلس على الكرسي، وأرجلك مسترخية، وعيناك ثابتتان علي.',
    'security_sit_by_the_pool_in_a_swimsuit__holding_a_cocktail_and_smiling_':
        'اجلس بجوار حمام السباحة مرتديًا ملابس السباحة واحمل كوكتيلًا وابتسم.',
    'security_sit_by_the_window_with_soft_light_on_your_face__slowly_looking_at_me_':
        'اجلس بجانب النافذة مع ضوء ناعم على وجهك، وانظر إلي ببطء.',
    'security_sit_close_to_the_camera__relaxed_and_at_ease_':
        'اجلس بالقرب من الكاميرا، مسترخيًا ومرتاحًا.',
    'security_sit_in_a_quiet_room__warm_light_behind_you__calm_and_unhurried_':
        'اجلس في غرفة هادئة، وخلفك ضوء دافئ، هادئًا وغير متسرع.',
    'security_sit_in_a_rattan_chair__rocking_it_gently__body_loose_and_eyes_peaceful_':
        'اجلس على كرسي من الخيزران، وقم بهزه بلطف، وجسدك مفكوك وعينيك هادئتان.',
    'security_sit_in_a_softly_lit_room__body_relaxed__attention_forward_':
        'اجلس في غرفة مضاءة بشكل خافت، مع استرخاء الجسم، والانتباه إلى الأمام.',
    'security_sit_on_a_balcony_at_night__city_lights_behind_you_':
        'اجلس في الشرفة ليلاً، وأضواء المدينة خلفك.',
    'security_sit_on_a_garden_bench__surrounded_by_faint_floral_scent__hands_resting_on_the_sides_quietly_':
        'اجلس على مقعد في الحديقة، محاطًا برائحة الأزهار الباهتة، واضعًا يديك على الجانبين بهدوء.',
    'security_sit_on_a_terrace__breeze_moving_slightly_as_you_look_over_':
        'اجلس على الشرفة، وتحرك النسيم قليلاً وأنت تنظر من حولك.',
    'security_sit_on_the_edge_of_the_bed__bare_feet_on_the_carpet__looking_relaxed_and_quiet_':
        'اجلس على حافة السرير، حافي القدمين على السجادة، وتبدو مسترخيًا وهادئًا.',
    'security_stand_by_the_floor_to_ceiling_window__silhouette_against_the_sky__staring_into_the_distance_softly_':
        'قف بجانب النافذة الممتدة من الأرض حتى السقف، وانظر إلى السماء، وانظر إلى المسافة بهدوء.',
    'security_stand_in_a_dimly_lit_hallway__light_outlining_your_figure__looking_at_me_calmly_':
        'قف في الردهة ذات الإضاءة الخافتة، والضوء يحدد شخصيتك، وانظر إلي بهدوء.',
    'security_stand_in_the_warm_sunlight__closing_your_eyes_briefly__then_opening_them_to_look_at_me_':
        'قف في ضوء الشمس الدافئ، وأغمض عينيك لفترة وجيزة، ثم افتحهما لتنظر إلي.',
    'security_stand_near_a_railing__resting_one_arm_while_watching_quietly_':
        'قف بالقرب من السور، وأريح ذراعك أثناء المشاهدة بهدوء.',
    'security_stand_near_the_pool__water_reflecting_while_you_take_a_slow_sip_':
        'قف بالقرب من حمام السباحة، وانعكس الماء بينما تأخذ رشفة بطيئة.',
    'security_stretch_slightly_in_your_seat__then_settle_back_comfortably_':
        'قم بالتمدد قليلًا في مقعدك، ثم استرخ بشكل مريح.',
    'security_stretch_your_arms_overhead_lazily__then_drop_them_down__slumping_comfortably_in_the_chair_':
        'مد ذراعيك فوق رأسك بتكاسل، ثم أنزلهما للأسفل، مستلقيًا بشكل مريح على الكرسي.',
    'security_tilt_your_glass_slowly__swirling_the_drink_inside__watching_me_with_a_faint_smile_':
        'قم بإمالة كأسك ببطء، وحرك المشروب بداخله، وشاهدني بابتسامة باهتة.',
    'security_turn_toward_me_slowly__like_I_just_arrived_':
        'التفت نحوي ببطء، وكأنني وصلت للتو.',
    'security_twist_the_ring_on_your_finger_gently__eyes_thoughtful_as_you_fix_your_gaze_on_me_':
        'قم بلف الخاتم على إصبعك بلطف، وعينيك متأملتين بينما تركز نظرك علي.',
    'security_wrap_your_arms_around_your_knees__sitting_curled_up_slightly__eyes_warm_on_me_':
        'لف ذراعيك حول ركبتيك، واجلس منحنيًا قليلاً، وعينيك دافئة علي.',
    'security_create_your_account': 'أنشئ حسابك',
    'security_input_content_here__Option_': 'إدخال المحتوى هنا (خيار)',
    'security_mina_Team': 'فريق مينا',
    'security_story_background': 'خلفية القصة',
    'security_tap_to_continue___': 'انقر للمتابعة...',
    'security_aI_Character': 'شخصية الذكاء الاصطناعي',
    'security_ask_for_pic': 'اطلب الموافقة المسبقة عن علم',
    'security_ask_for_video': 'اطلب الفيديو',
    'security_before_creation__please_review': 'قبل الإنشاء يرجى المراجعة',
    'security_coins_balance': 'رصيد العملات',
    'security_fail_to_collect': 'فشل في جمع',
    'security_gems_balance': 'توازن الأحجار الكريمة',
    'security_mM_dd__HH_mm_': 'MM月dd日 HH时mm分',
    'security_my_Coins': 'العملات المعدنية',
    'security_my_Gems': 'الجواهر',
    'security_notice__AI_responses_are_fictional_and_for_entertainment_only':
        'ملاحظة: ردود الذكاء الاصطناعي خيالية وللترفيه فقط',
    'security_plus_button_tapped': 'زر زائد استغلالها',
    'security_start_Create': 'ابدأ في الإنشاء',
    'security_unsupported_message_type': 'نوع الرسالة غير معتمد',
    'security_voice_button_tapped': 'تم الضغط على زر الصوت',
    'security_All_Chat': 'كل الدردشة',
    'security_Create_Video': 'إنشاء فيديو',
    'security_Generate_Video': 'توليد الفيديو',
    'security_Mina_Support': 'دعم مينا',
    'security_No_groups_yet__go_create_one_':
        'لا توجد مجموعات حتى الآن، اذهب لإنشاء واحدة!',
    'security_Please_input_description': 'الرجاء إدخال الوصف',
    'security_Search_by_ID__name__tag___':
        'البحث عن طريق الهوية والاسم والعلامة ...',
    'security_The_app_may_not_function_as_expected_until_you_remove_this_plugin_from_pubspec_yaml':
        'قد لا يعمل التطبيق كما هو متوقع حتى تقوم بإزالة هذا المكون الإضافي من pubspec.yaml',
    'security_Video_initialization_failed': 'فشلت تهيئة الفيديو',
    'security_Got_coins_reward': 'حصلت على مكافأة العملات',
    'security_Unlock_this_photo': 'فتح هذه الصورة',
    'security_Unlocked_successfully': 'تم فتحه بنجاح',
    'security_Your_balance': 'رصيدك',
    'security_language': 'لغة',
    'security_select_language': 'اختر اللغة',
    'security_settings': 'الإعدادات',
  };
}
