// Generated by toolchain/translate/generate_copywriting_localizations.py.
// Edit Copywriting or the generator instead of changing keys by hand.

abstract final class CopywritingStringsPt {
  static const Map<String, String> values = <String, String>{
    'security_about_her': 'Sobre ela',
    'security_account_Deletion': 'Exclusão de conta',
    'security_add_rounds': 'Adicionar rodadas',
    'security_all_Gender': 'Todos os gêneros',
    'security_appears_exclusively_in_your_character__s_public_profile_This_biographical_information_will_not_be_utilized_in_generation_prompts_or_influence_behavioral_patterns_':
        'Aparece exclusivamente no perfil público do seu personagem. Essas informações biográficas não serão utilizadas em prompts de geração ou influenciarão padrões de comportamento.',
    'security_are_you_sure_you_want_to_delete_your_account_':
        'Tem certeza de que deseja excluir sua conta?',
    'security_are_you_sure_you_want_to_log_out_':
        'Tem certeza de que deseja sair?',
    'security_audio_Library': 'Biblioteca de Áudio',
    'security_audio_input_is_too_short_to_send_':
        'A entrada de áudio é muito curta para ser enviada.',
    'security_avatar_upload_failed__please_try_again_later_':
        'Falha no upload do avatar. Tente novamente mais tarde.',
    'security_avatar_uploaded': 'Avatar enviado',
    'security_birth_date': 'Data de nascimento',
    'security_by_clicking_Security_security_Subscribe__you_will_be_charged__and_your_subscription_will_automatically_renew_at_the_same_price_and_duration_until_canceled_through_PlayStore_settings__By_proceeding__you_agree_to_our_terms_':
        'Ao clicar em Security.security_Subscribe, você será cobrado e sua assinatura será renovada automaticamente pelo mesmo preço e duração até ser cancelada nas configurações da PlayStore. Ao prosseguir, você concorda com nossos termos.',
    'security_call_Duration': 'Duração da chamada',
    'security_cannot_get_information__please_retry_later':
        'Não é possível obter informações, tente novamente mais tarde',
    'security_cannot_get_physique_details__please_retry_later':
        'Não é possível obter detalhes do físico. Tente novamente mais tarde',
    'security_cannot_open_date_picker__please_retry_later':
        'Não é possível abrir o seletor de data. Tente novamente mais tarde',
    'security_click_to_add': 'Clique para adicionar',
    'security_click_to_play': 'Clique para jogar',
    'security_coin_balance': 'Saldo de moedas',
    'security_connecting___': 'Conectando...',
    'security_copyright_Agreement': 'Acordo de Direitos Autorais',
    'security_create_My_Character': 'Crie meu personagem',
    'security_create_Now': 'Crie agora',
    'security_create_an_account': 'Crie uma conta',
    'security_current_device_not_support__try_restart_app_':
        'O dispositivo atual não é compatível. Tente reiniciar o aplicativo.',
    'security_defines_the_conversational_patterns_between_you_and_your_character__This_crucial_setting_determines_how_your_character_formulates_responses_and_maintains_personality_consistency_':
        'Define os padrões de conversa entre você e seu personagem. Este cenário crucial determina como seu personagem formula respostas e mantém a consistência da personalidade.',
    'security_delete_account_': 'Excluir conta?',
    'security_deleting___': 'Excluindo...',
    'security_describe_the_conversation_scenario_and_involved_characters_':
        'Descreva o cenário da conversa e os personagens envolvidos.',
    'security_describe_the_issue': 'Descreva o problema',
    'security_dialogue_Style': 'Estilo de diálogo',
    'security_edit_information': 'Editar informações',
    'security_enter_verification_code': 'Insira o código de verificação',
    'security_entry_your_email': 'Insira seu e-mail',
    'security_expires_on': 'Expira em',
    'security_failed_to_follow': 'Falha ao seguir',
    'security_failed_to_load_subscription_data':
        'Falha ao carregar dados de assinatura',
    'security_failed_to_process_subscription__please_try_again_later_':
        'Falha ao processar a assinatura. Tente novamente mais tarde.',
    'security_failed_to_record_audio__please_try_again':
        'Falha ao gravar áudio, tente novamente',
    'security_failed_to_send_gift': 'Falha ao enviar presente',
    'security_failed_to_unfollow': 'Falha ao parar de seguir',
    'security_failed_to_update__please_retry_later':
        'Falha ao atualizar, tente novamente mais tarde',
    'security_feelie_Pro': 'Feelie Pro',
    'security_fill_in_your_introduction___': 'Preencha sua introdução...',
    'security_following_the_regeneration_process__you_ll_receive_a_brand_new_image__You_are_also_welcome_to_revisit_the_images_you_created_earlier__Are_you_ready_to_move_forward_':
        'Após o processo de regeneração, você receberá uma imagem totalmente nova. Você também pode revisitar as imagens que criou anteriormente. Você está pronto para seguir em frente?',
    'security_for_example___On_the_moonlit_balcony_of_a_neo___Victorian_mansion__an_ethereal_woman_with_bright_blue_hime___cut_hair':
        'Por exemplo, "Na varanda enluarada de uma mansão neo - vitoriana, uma mulher etérea com cabelo cortado em hime azul brilhante',
    'security_gem_balance': 'Equilíbrio de gemas',
    'security_generating_in_progress': 'Geração em andamento',
    'security_generating___': 'Gerando...',
    'security_get_full_access_': 'Obtenha acesso total!',
    'security_hold_to_talk': 'Espere para falar',
    'security_how_would_you_like_OC_to_address_you_':
        'Como você gostaria que OC se dirigisse a você?',
    'security_image_Prompt': 'Solicitação de imagem',
    'security_information_updated_': 'Informação atualizada.',
    'security_insufficient_balance_': 'Equilíbrio insuficiente.',
    'security_interrupt_AI': 'Interromper IA',
    'security_loading___': 'Carregando...',
    'security_log_out': 'Sair',
    'security_logging_in___': 'Fazendo login...',
    'security_master_name_must_be_2_24_characters_in_length':
        'O nome mestre deve ter de 2 a 24 caracteres',
    'security_modify_Now': 'Modifique agora',
    'security_name_your_character': 'Dê um nome ao seu personagem',
    'security_network_error': 'Erro de rede',
    'security_network_error__please_try_again_later':
        'Erro de rede, tente novamente mais tarde',
    'security_network_exception__please_try_again_later':
        'Exceção de rede, tente novamente mais tarde',
    'security_no_chat_partner_has_been_initiated_yet':
        'Nenhum parceiro de bate-papo foi iniciado ainda',
    'security_no_companions_yet': 'Ainda não há companheiros',
    'security_no_data': 'Sem dados',
    'security_no_user_information__getting_back___':
        'Nenhuma informação do usuário, voltando...',
    'security_notice__Everything_AI_says_is_made_up':
        'Aviso: tudo o que a IA diz é inventado',
    'security_obtain_code': 'Obter código',
    'security_platform_not_supported_': 'Plataforma não suportada.',
    'security_please_agree_to_the_terms_and_conditions':
        'Por favor, concorde com os termos e condições',
    'security_please_select_a_product_to_recharge_':
        'Selecione um produto para recarregar.',
    'security_premium_Benefits_for_Audio__unlimited':
        'Benefícios Premium para Áudio, ilimitados',
    'security_prior_to_the_creation_process__please_review_our':
        'Antes do processo de criação, revise nosso',
    'security_privacy_Policy': 'Política de Privacidade',
    'security_privacy_policy': 'Política de privacidade',
    'security_pro_Free': 'Pró Grátis',
    'security_pro_only': 'Somente profissional',
    'security_purchase_done': 'Compra realizada',
    'security_purchased_Success': 'Sucesso adquirido',
    'security_purchasing___': 'Comprando...',
    'security_recharge_failed_': 'A recarga falhou.',
    'security_regeneration_Tips': 'Dicas de regeneração',
    'security_release_Cancel': 'Liberação Cancelar',
    'security_release_Send': 'Liberar envio',
    'security_role_image': 'Imagem do papel',
    'security_sF_Pro': 'SF Pro',
    'security_sF_Pro_bold': 'SF Pro bold',
    'security_select_from_gallery': 'Selecione da galeria',
    'security_select_from_the_album': 'Selecione no álbum',
    'security_selected_date_is_out_of_range_':
        'A data selecionada está fora do intervalo.',
    'security_send_failed__please_try_again_later':
        'Falha no envio, tente novamente mais tarde',
    'security_send_message__reply_by_AI': 'Enviar mensagem, responder por IA',
    'security_sending___': 'Enviando...',
    'security_sign_in_with_Apple': 'Faça login com a Apple',
    'security_sign_in_with_E_mail': 'Faça login com e-mail',
    'security_start_create': 'Comece a criar',
    'security_submitted_successfully': 'Enviado com sucesso',
    'security_supply_detailed_information_about_the_image__such_as_the_clothing_worn__facial_features__and_actions_':
        'Forneça informações detalhadas sobre a imagem, como roupas usadas, características faciais e ações.',
    'security_take_it_with_camera': 'Tire com a câmera',
    'security_terms_of_Service': 'Termos de Serviço',
    'security_terms_of_service': 'Termos de serviço',
    'security_the_OC_will_address_you_by_the_name_you_enter_':
        'O OC irá se dirigir a você pelo nome que você inserir.',
    'security_the_character_creation_is_still_ongoing__Leaving_at_this_moment_will_forfeit_the_progress_made_so_far__Are_you_sure_you_want_to_go_back_':
        'A criação do personagem ainda está em andamento. Sair neste momento perderá o progresso feito até agora. Tem certeza que deseja voltar?',
    'security_the_uploaded_image_serves_as_a_reference_for_facial_features_and_style_elements':
        'A imagem enviada serve como referência para características faciais e elementos de estilo',
    'security_turn_on_the_camera': 'Ligue a câmera',
    'security_unable_to_get_recharge_service__please_retry_later_':
        'Não foi possível obter o serviço de recarga. Tente novamente mais tarde.',
    'security_unknown_error__please_upload_again_':
        'Erro desconhecido. Faça upload novamente.',
    'security_unlock_Audio': 'Desbloquear áudio',
    'security_unlock_Image': 'Desbloquear imagem',
    'security_unlock_Video': 'Desbloquear vídeo',
    'security_updating_information___': 'Atualizando informações...',
    'security_upload_failed__please_try_again_later':
        'Falha no upload, tente novamente mais tarde',
    'security_uploading_new_avatar___': 'Carregando novo avatar...',
    'security_you_have_muted': 'Você desativou o som',
    'security_supply_detailed_information_about_the_image__such_as_the_clothing_worn__facial_features__and_actions__For_example___On_the_moonlit_balcony_of_a_neo___Victorian_mansion__an_ethereal_woman_with_bright_blue_hime___cut_hair_leans_against_the_railing__Her_khaki_backless_sweater_flutters_gently_in_the_breeze_as_she_turns_to_look_at_the_viewer_with_an_otherworldly_serenity__':
        'Forneça informações detalhadas sobre a imagem, como roupas usadas, características faciais e ações. Por exemplo, "Na varanda iluminada pela lua de uma mansão neo - vitoriana, uma mulher etérea com cabelo cortado em tons de azul brilhante se inclina contra a grade. Seu suéter cáqui sem costas flutua suavemente na brisa enquanto ela se vira para olhar para o espectador com uma serenidade sobrenatural."',
    'security_cannot_download_source__please_try_again_later':
        'Não é possível baixar a fonte, tente novamente mais tarde',
    'security_if_you_sign_in__you_agree_to':
        'Se você fizer login, você concorda em',
    'security_send_me_a_picture': 'Envie-me uma foto',
    'security_send_me_a_video': 'Envie-me um vídeo',
    'security_and_indicate_your_consent_': 'e indique seu consentimento.',
    'security_consuming_props_during_call':
        'Consumindo adereços durante a chamada',
    'security_no_more_companions_to_load_':
        'Não há mais companheiros para carregar.',
    'security_per_minute': 'por minuto',
    'security_edit': 'Editar',
    'security_video_Call': 'Videochamada',
    'security_i_am_listening___': 'Estou ouvindo...',
    'security_i_am_thinking___': 'Estou pensando...',
    'security_audio_Call': 'Chamada de áudio',
    'security_canceled_by_caller': 'Cancelado pelo chamador',
    'security_no_answer__please_try_again_later':
        'Sem resposta, tente novamente mais tarde',
    'security_no_favorites_yet__go_and_follow_some_people_':
        'Ainda não há favoritos, vá e siga algumas pessoas!',
    'security_benefits_Usage_Detail': 'Detalhes de utilização dos benefícios',
    'security_chat_beyond_reality__role_play_without_limits':
        'Bate-papo além da realidade, dramatização sem limites',
    'security_please_grant_camera_permission': 'Conceda permissão à câmera',
    'security_please_grant_microphone_permission':
        'Por favor, conceda permissão ao microfone',
    'security_unlocking_for_free_': 'Desbloqueio de graça!',
    'security_you__re_now_a_premium_member__nYour_benefits_are_unlocked__nExplore_your_new_perks_':
        'Agora você é um membro premium!\\nSeus benefícios foram desbloqueados.\\nExplore suas novas vantagens!',
    'security_by_clicking_subscribe__you_will_be_charged__and_your_subscription_will_automatically_renew_at_the_same_price_and_duration_until_canceled_through_App_Store_settings__By_proceeding__you_agree_to_our_terms_':
        'Ao clicar em assinar, você será cobrado e sua assinatura será renovada automaticamente pelo mesmo preço e duração até ser cancelada nas configurações da App Store. Ao prosseguir, você concorda com nossos termos.',
    'security_daily_Task': 'Tarefa Diária',
    'security_premium_Only': 'Somente Premium',
    'security_introduction': 'Introdução',
    'security_premium_Free': 'Prêmio Grátis',
    'security_an_error_occurred__please_try_again_later_':
        'Ocorreu um erro. Tente novamente mais tarde.',
    'security_product_id_not_found__please_try_again_later':
        'ID do produto não encontrado, tente novamente mais tarde',
    'security_call_wasn__t_answered': 'A chamada não foi atendida',
    'security_cancelled_by_Caller': 'Cancelado pelo chamador',
    'security_consuming_gems_during_call': 'Consumir gemas durante a chamada',
    'security_ending___': 'Terminando...',
    'security_free_Call': 'Chamada Gratuita',
    'security_not_enough_gems__please_recharge':
        'Gemas insuficientes, recarregue',
    'security_send_a_message_': 'Envie uma mensagem…',
    'security_free_for_first': 'Gratuito para o primeiro',
    'security_error__max_should_not_be_a_negative_number_or_zero':
        'Erro, max não deve ser um número negativo ou zero',
    'security_error__min_is_greater_than_or_equal_to_max':
        'Erro, min é maior ou igual a max',
    'security_invites_you': 'Convida você',
    'security_aD_Free': 'Sem anúncios',
    'security_enter_your_image_prompt__e_g__A_girl__sitting_on_a_bench___':
        'Insira seu prompt de imagem, por ex. Uma garota sentada em um banco...',
    'security_failed_to_grant_coin__Please_try_again_later_':
        'Falha ao conceder moeda. Por favor, tente novamente mais tarde.',
    'security_failed_to_unlock_resource__Please_try_again_later_':
        'Falha ao desbloquear recurso. Por favor, tente novamente mais tarde.',
    'security_image_prompt_cannot_be_empty':
        'O prompt da imagem não pode ficar vazio',
    'security_images_you_like': 'Imagens que você gosta',
    'security_please_select_at_least_one_prompt':
        'Selecione pelo menos um prompt',
    'security_signing_in___': 'Fazendo login...',
    'security_all_Chat': 'Todo o bate-papo',
    'security_chat_Models': 'Modelos de bate-papo',
    'security_chat_Now': 'Converse agora',
    'security_clear_Chat_History': 'Limpar histórico de bate-papo',
    'security_connect_with_everyone_in_one_place':
        'Conecte-se com todos em um só lugar',
    'security_contact_us_for_support_': 'Contate-nos para suporte.',
    'security_delete_Message': 'Excluir mensagem',
    'security_design_your_own_unique_character_and_bring_it_to_life_':
        'Crie seu próprio personagem único e dê vida a ele.',
    'security_group_Chat': 'Bate-papo em grupo',
    'security_limited_Free': 'Gratuito limitado',
    'security_mark_all_as_read': 'Marcar tudo como lido',
    'security_message_Setting': 'Configuração de mensagem',
    'security_message_setting': 'Configuração de mensagem',
    'security_reset_Success_': 'Reinicialização com sucesso!',
    'security_rewind_to_here': 'Retroceda até aqui',
    'security_she_will_forget_conversation_history_with_you_':
        'Ela vai esquecer o histórico de conversas com você!',
    'security_shield_Real__s_Messages': 'Mensagens do Shield Real',
    'security_soulink_Team': 'Equipe Soulink',
    'security_switch_Failed': 'Falha na troca',
    'security_switch_Succeed_enjoy_your_chat':
        'Switch com sucesso, aproveite seu bate-papo',
    'security_switch_the_Model': 'Mudar o modelo',
    'security_contact_us': 'Contate-nos',
    'security_iAP_Service_Not_Available': 'Serviço IAP não disponível',
    'security_iAP_not_available__restart_the_app_and_try_again_':
        'IAP não disponível, reinicie o aplicativo e tente novamente.',
    'security_item_info_error': 'Erro nas informações do item',
    'security_monthly_Premium': 'Prêmio Mensal',
    'security_no_recharge_item_available__try_again_later':
        'Nenhum item de recarga disponível, tente novamente mais tarde',
    'security_payment_failed': 'Falha no pagamento',
    'security_payment_successful': 'Pagamento bem-sucedido',
    'security_purchase_successful': 'Compra bem-sucedida',
    'security_receipt_Not_Available': 'Recibo não disponível',
    'security_special_Offer': 'Oferta Especial',
    'security_weekly_Premium': 'Prêmio Semanal',
    'security_yearly_Premium': 'Prêmio Anual',
    'security_about_AI_MODE': 'Sobre o MODO IA',
    'security_about_Me': 'Sobre mim',
    'security_add_Group_Member': 'Adicionar membro do grupo',
    'security_add_New_Group_Member': 'Adicionar novo membro do grupo',
    'security_are_you_sure_you_want_to_disband_this_group__This_action_cannot_be_undone__and_all_members_will_be_removed_':
        'Tem certeza de que deseja dissolver este grupo? Esta ação não pode ser desfeita e todos os membros serão removidos.',
    'security_auto___enabled__The_mentioned_member_s__will_reply_your_message_':
        'Auto @ ativado. O(s) membro(s) mencionado(s) responderão sua mensagem.',
    'security_click_anywhere_to_continue___':
        'Clique em qualquer lugar para continuar...',
    'security_congratulations__You_got_a_new_MODE__enjoy_it_':
        'Parabéns! Você tem um novo MODO, aproveite.',
    'security_contact_List': 'Lista de Contatos',
    'security_create_Group': 'Criar grupo',
    'security_dating_Game': 'Jogo de namoro',
    'security_disband_Group': 'Dissolver Grupo',
    'security_disband_Group_': 'Dissolver grupo?',
    'security_download_failed__please_retry_later_':
        'Falha no download, tente novamente mais tarde!',
    'security_edit_Group_Name': 'Editar nome do grupo',
    'security_edit_Group_Scenario': 'Editar cenário de grupo',
    'security_enter_the_Group_Scenario': 'Entre no cenário do grupo',
    'security_enter_the_group_name': 'Digite o nome do grupo',
    'security_error_occurred__please_try_again':
        'Ocorreu um erro, tente novamente',
    'security_go_Play': 'Vá brincar',
    'security_group_Info': 'Informações do grupo',
    'security_group_Member': 'Membro do Grupo',
    'security_group_Name': 'Nome do grupo',
    'security_group_Owner': 'Proprietário do grupo',
    'security_group_Scenario': 'Cenário de grupo',
    'security_in_Use': 'Em uso',
    'security_in_use': 'Em uso',
    'security_level_Up_': 'Suba de nível!',
    'security_my_OCs': 'Meus OCs',
    'security_not_enough_balance': 'Equilíbrio insuficiente',
    'security_please_agree_to_the_terms_below_first_':
        'Concorde primeiro com os termos abaixo.',
    'security_popular_Search': 'Pesquisa popular',
    'security_recent_Search': 'Pesquisa recente',
    'security_search_Failed': 'Falha na pesquisa',
    'security_search_Users_by_ID_or_Name': 'Pesquisar usuários por ID ou nome',
    'security_some_error_occur__please_retry_later_':
        'Ocorreu algum erro, tente novamente mais tarde!',
    'security_some_error_occurred__try_again_later_':
        'Ocorreu algum erro, tente novamente mais tarde.',
    'security_some_error_occurred__Please_try_again_later_':
        'Ocorreu algum erro. Por favor, tente novamente mais tarde.',
    'security_start_Game': 'Iniciar o jogo',
    'security_switch_Succeed__enjoy_your_chat':
        'Switch com sucesso, aproveite seu bate-papo',
    'security_switch_to_Chat': 'Mudar para bate-papo',
    'security_take_a_look__': 'Dê uma olhada >',
    'security_the_MODE_will_only_take_effect_after_you_have_acquired_this_character__Continue_purchasing_':
        'O MODO só terá efeito após você adquirir este personagem. Continuar comprando?',
    'security_the_muted_member_will_not_reply_your_message':
        'O membro silenciado não responderá sua mensagem',
    'security_this_member_is_deactivated_': 'Este membro está desativado.',
    'security_this_member_is_expired_': 'Este membro expirou.',
    'security_time_limit': 'Prazo',
    'security_try_it': 'Experimente',
    'security_unlock_conditions_not_met__Upgrade_your_level_now_':
        'Condições de desbloqueio não atendidas. Atualize seu nível agora!',
    'security_unlock_tips': 'Dicas de desbloqueio',
    'security_your_reward': 'Sua recompensa',
    'security_edit_My_Character': 'Editar meu personagem',
    'security_message_Settings': 'Configurações de mensagens',
    'security_no_datas__click_to_retry_':
        'Sem dados, clique para tentar novamente.',
    'security_start_Chat': 'Iniciar bate-papo',
    'security_send_a_message___': 'Envie uma mensagem...',
    'security_send_me_a_pic_with_you_tucking_hair_behind_ear_in_sunset__Send_me_a_pic_with_you_touching_flower_petals_at_dusk__Send_me_a_pic_with_you_holding_teacup_by_rain_window__Send_me_a_pic_with_you_twirling_silk_scarf_by_the_lake__Send_me_a_pic_with_you_adjusting_shoelace_in_sunlight__Send_me_a_pic_with_you_skimming_calm_fountain_surface__Send_me_a_pic_with_you_wrapping_shawl_on_the_balcony':
        'Me mande uma foto com você colocando o cabelo atrás da orelha ao pôr do sol || Me mande uma foto com você tocando pétalas de flores ao entardecer || Me mande uma foto com você segurando uma xícara de chá perto da janela de chuva || Me mande uma foto com você girando o lenço de seda à beira do lago || Me mande uma foto com você ajustando o cadarço na luz do sol || Me mande uma foto com você deslizando pela superfície calma da fonte || Me mande uma foto com você embrulhando o xale na varanda',
    'security_nice_to_meet_you_': 'Prazer em conhecê-lo!',
    'security_sign_in_with_Google': 'Faça login com o Google',
    'security_failed_to_save__image_URL_is_empty':
        'Falha ao salvar, o URL da imagem está vazio',
    'security_failed_to_save__try_again_later':
        'Falha ao salvar, tente novamente mais tarde',
    'security_failed_to_save__try_again_later_Data_Empty_':
        'Falha ao salvar, tente novamente mais tarde[Dados vazios]',
    'security_saved_successfully': 'Salvo com sucesso',
    'security_saving___': 'Salvando...',
    'security_scenario': 'Cenário',
    'security_are_you_sure_you_want_to_block_this_user_':
        'Tem certeza de que deseja bloquear este usuário?',
    'security_bock_Messages_from_Strangers': 'Mensagens Bock de estranhos',
    'security_aI_Writer': 'Escritor de IA',
    'security_permission_settings': 'Configurações de permissão',
    'security_the_existing_filled_content_will_be_replaced_by_the_template_content_and_cannot_be_undone_':
        'O conteúdo preenchido existente será substituído pelo conteúdo do modelo e não poderá ser desfeito.',
    'security_what_should_AI_call_you': 'Como a IA deve chamá-lo',
    'security_generation_failed__please_try_again_later_':
        'Falha na geração. Tente novamente mais tarde.',
    'security_copied_ID_to_clipboard':
        'ID copiado para a área de transferência',
    'security_character_name_must_be_at_least_3_letters_':
        'O nome do personagem deve ter pelo menos 3 letras.',
    'security_more_Details': 'Mais detalhes',
    'security_feedback_Log': 'Registro de comentários',
    'security_image_is_Not_ready__please_try_again_later_':
        'A imagem não está pronta. Tente novamente mais tarde.',
    'security_not_approved': 'Não aprovado',
    'security_under_review': 'Em revisão',
    'security_upload_Log_success': 'Carregar registro com sucesso',
    'security_about_Soulink': 'Sobre o Soullink',
    'security_are_you_sure_': 'Tem certeza?',
    'security_character_is_private': 'O personagem é privado',
    'security_complete_tasks_to_get_rewards':
        'Conclua tarefas para obter recompensas',
    'security_cost_Trial_Card': 'Cartão de avaliação de custo',
    'security_create_Character': 'Criar personagem',
    'security_create_Moment': 'Criar momento',
    'security_create_an_image_with_Generator':
        'Crie uma imagem com o Generator',
    'security_currently_owns_': 'Atualmente possui:',
    'security_daily_post_limit_exceeded': 'Limite de postagem diária excedido',
    'security_describe_what_you_want__e_g___A_barista_wipes_the_counter_of_a_small_caf__by_the_river__steam_rising_from_coffee_cups__boats_passing_slowly_outside_the_window__a_cat_napping_on_a_nearby_chair_':
        'Descreva o que você deseja, por exemplo, Um barista limpa o balcão de um pequeno café à beira do rio, vapor saindo de xícaras de café, barcos passando lentamente do lado de fora da janela, um gato cochilando em uma cadeira próxima.',
    'security_don_t_remind_me_again': 'Não me lembre de novo',
    'security_enable_this_option_to_allow_the_AI_to_generate_image_galleries_based_on_your_information_':
        'Habilite esta opção para permitir que a IA gere galerias de imagens com base em suas informações.',
    'security_enter_the_Description': 'Insira a descrição',
    'security_exit_Video_Matching_': 'Sair da correspondência de vídeo?',
    'security_failed_Generate': 'Falha na geração',
    'security_failed_reload': 'Falha ao recarregar',
    'security_first_message_from_your_character__It_will_help_the_chat_get_off_to_a_better_start_':
        'Primeira mensagem do seu personagem. Isso ajudará o bate-papo a começar melhor.',
    'security_for_You': 'Para você',
    'security_generate_Video': 'Gerar vídeo',
    'security_generate_config_loading': 'Gerar carregamento de configuração',
    'security_generate_for_Moment': 'Gerar para o momento',
    'security_generate_video': 'Gerar vídeo',
    'security_generating_Gallery': 'Gerando Galeria',
    'security_get_30s_Free_Trial': 'Obtenha uma avaliação gratuita de 30 anos',
    'security_go_Setting': 'Ir configuração',
    'security_grants_the_first_30_seconds_of_the_call_for_free__After_that__gems_will_be_charged_':
        'Concede gratuitamente os primeiros 30 segundos da chamada. Depois disso, as joias serão cobradas.',
    'security_i_understand': 'Eu entendo',
    'security_image_details__facial_features__clothing':
        'Detalhes da imagem, características faciais, roupas',
    'security_initial_Message': 'Mensagem Inicial',
    'security_invites_you_to_video_calling_':
        'Convida você para videochamadas…',
    'security_lets_you_make_calls_without_spending_gems_':
        'Permite fazer ligações sem gastar joias.',
    'security_mM_dd_HH_mm': 'MM-dd HH:mm',
    'security_just_now': 'Agora mesmo',
    'security_one_minute_ago': 'Há 1 minuto',
    'security_minutes_ago': 'Há {count} minutos',
    'security_one_hour_ago': 'Há 1 hora',
    'security_hours_ago': 'Há {count} horas',
    'security_one_day_ago': 'Há 1 dia',
    'security_days_ago': 'Há {count} dias',
    'security_one_week_ago': 'Há 1 semana',
    'security_weeks_ago': 'Há {count} semanas',
    'security_maximum_limit_exceeded': 'Limite máximo excedido',
    'security_no_report_reasons_available':
        'Nenhum motivo de relatório disponível',
    'security_operation_failed': 'Operação falhou',
    'security_permission_required': 'Permissão necessária',
    'security_please_allow_access_to_the_camera_in_the_settings':
        'Permita o acesso à câmera nas configurações',
    'security_please_allow_access_to_the_microphone_in_the_settings':
        'Permita o acesso ao microfone nas configurações',
    'security_please_input_description': 'Insira a descrição',
    'security_please_select_a_character_first':
        'Selecione um personagem primeiro',
    'security_post_As': 'Publicar como',
    'security_post_successful': 'Postagem bem-sucedida',
    'security_post_updates_for_your_character_and_bring_every_moment_of_their_story_to_life_':
        'Publique atualizações para seu personagem e dê vida a cada momento de sua história!',
    'security_post_your_reply': 'Poste sua resposta',
    'security_report_Success_': 'Relatar sucesso!',
    'security_select_From_Chat_History_Album':
        'Selecione no álbum do histórico de bate-papo',
    'security_select_Image': 'Selecionar imagem',
    'security_select_a_Character': 'Selecione um personagem',
    'security_start_Match': 'Iniciar partida',
    'security_switching_characters_will_clear_the_current_content':
        'A troca de caracteres limpará o conteúdo atual',
    'security_the_user_has_been_matched__and_the_other_party_accepts_and_enters_the_video_call':
        'O usuário foi correspondido e a outra parte aceita e entra na videochamada',
    'security_this_moment_does_not_meet_community_requirements__please_edit':
        'Este momento não atende aos requisitos da comunidade, edite',
    'security_translation_failure_': 'Falha na tradução…',
    'security_you_need_to_have_your_own_role_to_post___nGo_create_a_character':
        'Você precisa ter sua própria função para postar! \\nVá criar um personagem',
    'security_you_re_now_using_your_trial_card_or_available_call_time___whichever_applies_':
        'Agora você está usando seu cartão de teste ou o tempo de chamada disponível, o que for aplicável.',
    'security_please_grant_storage_permission':
        'Conceda permissão de armazenamento',
    'security_brush_a_strand_of_hair_back_gently__eyes_soft_as_you_gaze_straight_at_me_':
        'Penteie uma mecha de cabelo para trás suavemente, com os olhos suaves enquanto olha diretamente para mim.',
    'security_hold_a_book_loosely_in_your_hand__flipping_a_page_slowly_as_you_glance_up_':
        'Segure um livro livremente em sua mão, virando a página lentamente enquanto olha para cima.',
    'security_hold_a_cup_of_warm_drink__blowing_on_it_softly_before_taking_a_small_sip_':
        'Segure uma xícara de bebida quente, soprando suavemente antes de tomar um pequeno gole.',
    'security_lean_against_a_bar_counter__drink_in_hand__shoulders_loose_':
        'Encoste-se no balcão do bar, com a bebida na mão e os ombros soltos.',
    'security_lean_against_a_bookshelf__one_hand_brushing_the_spines__calm_and_unhurried_':
        'Encoste-se em uma estante, uma mão roçando as lombadas, calmo e sem pressa.',
    'security_lean_against_a_wall__arms_loosely_crossed__watching_me_':
        'Encoste-se na parede, com os braços cruzados, me observando.',
    'security_lean_against_the_door_frame__one_leg_crossed_casually__smiling_as_you_watch_me_approach_':
        '​​Encoste-se no batente da porta, uma perna cruzada casualmente, sorrindo enquanto me vê aproximar.',
    'security_lean_forward_a_little__head_tilted__listening_intently_with_a_calm_expression_':
        'Incline-se um pouco para frente, cabeça inclinada, ouvindo atentamente com uma expressão calma.',
    'security_lounge_on_a_pool_chair__sunglasses_pushed_up_as_you_glance_over_':
        'Relaxe em uma cadeira de piscina, com os óculos escuros levantados enquanto você olha por cima.',
    'security_relax_on_a_couch__one_arm_resting_casually_as_you_smile_':
        'Relaxe em um sofá, com um braço descansando casualmente enquanto sorri.',
    'security_relax_on_a_sofa_in_the_evening__warm_lights_around_you_':
        'Relaxe em um sofá à noite, com luzes quentes ao seu redor.',
    'security_rest_one_elbow_on_the_table__fingers_tapping_lightly_as_you_smile_lazily_':
        'Descanse um cotovelo sobre a mesa, batendo levemente os dedos enquanto sorri preguiçosamente.',
    'security_rest_your_chin_on_your_hand__looking_at_me_thoughtfully_':
        'Apoie o queixo na mão e me olhe pensativamente.',
    'security_rest_your_head_back_against_the_cushion__eyes_half_closed__relaxed_and_unguarded_':
        'Descanse a cabeça contra a almofada, os olhos semicerrados, relaxados e desprotegidos.',
    'security_rest_your_palms_flat_on_the_table__leaning_back_slightly__breathing_slowly_and_steadily_':
        'Descanse as palmas das mãos sobre a mesa, inclinando-se ligeiramente para trás, respirando lenta e continuamente.',
    'security_sit_at_a_rooftop_bar__elbows_on_the_railing__looking_out_at_the_night_view_lazily_':
        'Sente-se em um bar na cobertura, com os cotovelos apoiados na grade, olhando preguiçosamente para a vista noturna.',
    'security_sit_at_a_table_with_a_drink_nearby__glancing_up_like_you_noticed_me_':
        'Sente-se em uma mesa com uma bebida por perto, olhando para cima como se você tivesse me notado.',
    'security_sit_at_an_outdoor_caf___one_hand_around_a_glass__relaxed_posture_':
        'Sente-se em um café ao ar livre, com uma mão em volta de um copo, em postura relaxada.',
    'security_sit_back_in_a_chair__legs_relaxed__eyes_steady_on_me_':
        'Sente-se em uma cadeira, com as pernas relaxadas e os olhos fixos em mim.',
    'security_sit_by_the_pool_in_a_swimsuit__holding_a_cocktail_and_smiling_':
        'Sente-se à beira da piscina em traje de banho, segurando um coquetel e sorrindo.',
    'security_sit_by_the_window_with_soft_light_on_your_face__slowly_looking_at_me_':
        'Sente-se perto da janela com uma luz suave no rosto, olhando lentamente para mim.',
    'security_sit_close_to_the_camera__relaxed_and_at_ease_':
        'Sente-se perto da câmera, relaxado e à vontade.',
    'security_sit_in_a_quiet_room__warm_light_behind_you__calm_and_unhurried_':
        'Sente-se em uma sala silenciosa, com luz quente atrás de você, calmo e sem pressa.',
    'security_sit_in_a_rattan_chair__rocking_it_gently__body_loose_and_eyes_peaceful_':
        'Sente-se em uma cadeira de vime, balançando-a suavemente, o corpo solto e os olhos em paz.',
    'security_sit_in_a_softly_lit_room__body_relaxed__attention_forward_':
        'Sente-se em uma sala suavemente iluminada, com o corpo relaxado e a atenção voltada para a frente.',
    'security_sit_on_a_balcony_at_night__city_lights_behind_you_':
        'Sente-se em uma varanda à noite, com as luzes da cidade atrás de você.',
    'security_sit_on_a_garden_bench__surrounded_by_faint_floral_scent__hands_resting_on_the_sides_quietly_':
        'Sente-se em um banco de jardim, cercado por um leve perfume floral, com as mãos apoiadas nas laterais em silêncio.',
    'security_sit_on_a_terrace__breeze_moving_slightly_as_you_look_over_':
        'Sente-se em um terraço, com a brisa movendo-se levemente enquanto você olha.',
    'security_sit_on_the_edge_of_the_bed__bare_feet_on_the_carpet__looking_relaxed_and_quiet_':
        'Sente-se na beira da cama, com os pés descalços no carpete, parecendo relaxado e quieto.',
    'security_stand_by_the_floor_to_ceiling_window__silhouette_against_the_sky__staring_into_the_distance_softly_':
        'Fique perto da janela do chão ao teto, silhueta contra o céu, olhando suavemente para longe.',
    'security_stand_in_a_dimly_lit_hallway__light_outlining_your_figure__looking_at_me_calmly_':
        'Fique em um corredor mal iluminado, a luz delineando sua figura, olhando para mim com calma.',
    'security_stand_in_the_warm_sunlight__closing_your_eyes_briefly__then_opening_them_to_look_at_me_':
        'Fique sob a luz quente do sol, fechando os olhos brevemente e depois abrindo-os para olhar para mim.',
    'security_stand_near_a_railing__resting_one_arm_while_watching_quietly_':
        'Fique perto de uma grade, apoiando um braço enquanto observa em silêncio.',
    'security_stand_near_the_pool__water_reflecting_while_you_take_a_slow_sip_':
        'Fique perto da piscina, com a água refletindo enquanto você toma um gole lento.',
    'security_stretch_slightly_in_your_seat__then_settle_back_comfortably_':
        'Alongue-se ligeiramente no assento e depois recoste-se confortavelmente.',
    'security_stretch_your_arms_overhead_lazily__then_drop_them_down__slumping_comfortably_in_the_chair_':
        'Estique os braços acima da cabeça preguiçosamente e depois abaixe-os, afundando-se confortavelmente na cadeira.',
    'security_tilt_your_glass_slowly__swirling_the_drink_inside__watching_me_with_a_faint_smile_':
        'Incline seu copo lentamente, girando a bebida dentro, me observando com um leve sorriso.',
    'security_turn_toward_me_slowly__like_I_just_arrived_':
        'Vire-se para mim lentamente, como se eu tivesse acabado de chegar.',
    'security_twist_the_ring_on_your_finger_gently__eyes_thoughtful_as_you_fix_your_gaze_on_me_':
        'Gire o anel em seu dedo suavemente, com os olhos pensativos enquanto fixa seu olhar em mim.',
    'security_wrap_your_arms_around_your_knees__sitting_curled_up_slightly__eyes_warm_on_me_':
        'Passe os braços em volta dos joelhos, sentando-se ligeiramente enrolado, olhos quentes em mim.',
    'security_create_your_account': 'Crie sua conta',
    'security_input_content_here__Option_': 'Insira o conteúdo aqui (opção)',
    'security_mina_Team': 'Equipe Mina',
    'security_story_background': 'Contexto da história',
    'security_tap_to_continue___': 'Toque para continuar...',
    'security_aI_Character': 'Personagem IA',
    'security_ask_for_pic': 'Peça foto',
    'security_ask_for_video': 'Peça vídeo',
    'security_before_creation__please_review': 'Antes da criação, revise',
    'security_coins_balance': 'Saldo de moedas',
    'security_fail_to_collect': 'Falha na coleta',
    'security_gems_balance': 'Saldo de gemas',
    'security_mM_dd__HH_mm_': 'MM月dd日 HH时mm分',
    'security_my_Coins': 'Moedas',
    'security_my_Gems': 'Gemas',
    'security_notice__AI_responses_are_fictional_and_for_entertainment_only':
        'Aviso: as respostas da IA são fictícias e apenas para entretenimento',
    'security_plus_button_tapped': 'Botão de adição pressionado',
    'security_start_Create': 'Iniciar a criação',
    'security_unsupported_message_type': 'Tipo de mensagem não suportado',
    'security_voice_button_tapped': 'Botão de voz tocado',
    'security_All_Chat': 'Todo o bate-papo',
    'security_Create_Video': 'Criar vídeo',
    'security_Generate_Video': 'Gerar vídeo',
    'security_Mina_Support': 'Suporte Mina',
    'security_No_groups_yet__go_create_one_': 'Ainda não há grupos, crie um!',
    'security_Please_input_description': 'Insira a descrição',
    'security_Search_by_ID__name__tag___': 'Pesquise por ID, nome, etiqueta...',
    'security_The_app_may_not_function_as_expected_until_you_remove_this_plugin_from_pubspec_yaml':
        'O aplicativo pode não funcionar conforme esperado até que você remova este plugin de pubspec.yaml',
    'security_Video_initialization_failed': 'Falha na inicialização do vídeo',
    'security_Got_coins_reward': 'Recebi recompensa em moedas',
    'security_Unlock_this_photo': 'Desbloqueie esta foto',
    'security_Unlocked_successfully': 'Desbloqueado com sucesso',
    'security_Your_balance': 'Seu saldo',
    'security_language': 'Idioma',
    'security_select_language': 'Selecione o idioma',
    'security_settings': 'Definições',
  };
}
