// Generated by toolchain/translate/generate_copywriting_localizations.py.
// Edit Copywriting or the generator instead of changing keys by hand.

abstract final class CopywritingStringsEn {
  static const Map<String, String> values = <String, String>{
    // 'security_notifications': 'Notifications',
    // 'security_collections': 'Collections',
    // 'security_feedback': 'Feedback',
    // 'security_about_her': 'About her',
    // 'security_account_Deletion': 'Account Deletion',
    // 'security_add_rounds': 'Add rounds',
    // 'security_all_Gender': 'All Gender',
    // 'security_appears_exclusively_in_your_character__s_public_profile_This_biographical_information_will_not_be_utilized_in_generation_prompts_or_influence_behavioral_patterns_':
    //     'Appears exclusively in your character\\\'s public profile.This biographical information will not be utilized in generation prompts or influence behavioral patterns.',
    // 'security_are_you_sure_you_want_to_delete_your_account_':
    //     'Are you sure you want to delete your account?',
    // 'security_are_you_sure_you_want_to_log_out_':
    //     'Are you sure you want to log out?',
    // 'security_audio_Library': 'Audio Library',
    // 'security_audio_input_is_too_short_to_send_':
    //     'Audio input is too short to send.',
    // 'security_avatar_upload_failed__please_try_again_later_':
    //     'Avatar upload failed, please try again later.',
    // 'security_avatar_uploaded': 'Avatar uploaded',
    // 'security_birth_date': 'Birth date',
    // 'security_by_clicking_Security_security_Subscribe__you_will_be_charged__and_your_subscription_will_automatically_renew_at_the_same_price_and_duration_until_canceled_through_PlayStore_settings__By_proceeding__you_agree_to_our_terms_':
    //     'By clicking Security.security_Subscribe, you will be charged, and your subscription will automatically renew at the same price and duration until canceled through PlayStore settings. By proceeding, you agree to our terms.',
    // 'security_call_Duration': 'Call Duration',
    // 'security_cannot_get_information__please_retry_later':
    //     'Cannot get information, please retry later',
    // 'security_cannot_get_physique_details__please_retry_later':
    //     'Cannot get physique details, please retry later',
    // 'security_cannot_open_date_picker__please_retry_later':
    //     'Cannot open date picker, please retry later',
    // 'security_click_to_add': 'Click to add',
    // 'security_click_to_play': 'Click to play',
    // 'security_coin_balance': 'Coin balance',
    // 'security_connecting___': 'Connecting...',
    // 'security_copyright_Agreement': 'Copyright Agreement',
    // 'security_create_My_Character': 'Create My Character',
    // 'security_create_Now': 'Create Now',
    // 'security_create_an_account': 'Create an account',
    // 'security_current_device_not_support__try_restart_app_':
    //     'Current device not support, try restart app.',
    // 'security_defines_the_conversational_patterns_between_you_and_your_character__This_crucial_setting_determines_how_your_character_formulates_responses_and_maintains_personality_consistency_':
    //     'Defines the conversational patterns between you and your character. This crucial setting determines how your character formulates responses and maintains personality consistency.',
    // 'security_delete_account_': 'Delete account?',
    // 'security_deleting___': 'Deleting...',
    // 'security_describe_the_conversation_scenario_and_involved_characters_':
    //     'Describe the conversation scenario and involved characters.',
    // 'security_describe_the_issue': 'Describe the issue',
    // 'security_dialogue_Style': 'Dialogue Style',
    // 'security_edit_information': 'Edit information',
    // 'security_enter_verification_code': 'Enter verification code',
    // 'security_entry_your_email': 'Entry your email',
    // 'security_expires_on': 'Expires on',
    // 'security_failed_to_follow': 'Failed to follow',
    // 'security_failed_to_load_subscription_data':
    //     'Failed to load subscription data',
    // 'security_failed_to_process_subscription__please_try_again_later_':
    //     'Failed to process subscription, please try again later.',
    // 'security_failed_to_record_audio__please_try_again':
    //     'Failed to record audio, please try again',
    // 'security_failed_to_send_gift': 'Failed to send gift',
    // 'security_failed_to_unfollow': 'Failed to unfollow',
    // 'security_failed_to_update__please_retry_later':
    //     'Failed to update, please retry later',
    // 'security_feelie_Pro': 'Feelie Pro',
    // 'security_fill_in_your_introduction___': 'Fill in your introduction...',
    // 'security_following_the_regeneration_process__you_ll_receive_a_brand_new_image__You_are_also_welcome_to_revisit_the_images_you_created_earlier__Are_you_ready_to_move_forward_':
    //     'Following the regeneration process, you’ll receive a brand-new image. You are also welcome to revisit the images you created earlier. Are you ready to move forward?',
    // 'security_for_example___On_the_moonlit_balcony_of_a_neo___Victorian_mansion__an_ethereal_woman_with_bright_blue_hime___cut_hair':
    //     'For example, "On the moonlit balcony of a neo - Victorian mansion, an ethereal woman with bright blue hime - cut hair',
    // 'security_gem_balance': 'Gem balance',
    // 'security_generating_in_progress': 'Generating in progress',
    // 'security_generating___': 'Generating...',
    // 'security_get_full_access_': 'Get full access!',
    // 'security_hold_to_talk': 'Hold to talk',
    // 'security_how_would_you_like_OC_to_address_you_':
    //     'How would you like OC to address you?',
    // 'security_image_Prompt': 'Image Prompt',
    // 'security_information_updated_': 'Information updated.',
    // 'security_insufficient_balance_': 'Insufficient balance.',
    // 'security_interrupt_AI': 'Interrupt AI',
    // 'security_loading___': 'Loading...',
    // 'security_log_out': 'Log out',
    // 'security_logging_in___': 'Logging in...',
    // 'security_master_name_must_be_2_24_characters_in_length':
    //     'Master name must be 2-24 characters in length',
    // 'security_modify_Now': 'Modify Now',
    // 'security_name_your_character': 'Name your character',
    // 'security_network_error': 'Network error',
    // 'security_network_error__please_try_again_later':
    //     'Network error, please try again later',
    // 'security_network_exception__please_try_again_later':
    //     'Network exception, please try again later',
    // 'security_no_chat_partner_has_been_initiated_yet':
    //     'No chat partner has been initiated yet',
    // 'security_no_companions_yet': 'No companions yet',
    // 'security_no_data': 'No data',
    // 'security_no_user_information__getting_back___':
    //     'No user information, getting back...',
    // 'security_notice__Everything_AI_says_is_made_up':
    //     'Notice: Everything AI says is made up',
    // 'security_obtain_code': 'Obtain code',
    // 'security_platform_not_supported_': 'Platform not supported.',
    // 'security_please_agree_to_the_terms_and_conditions':
    //     'Please agree to the terms and conditions',
    // 'security_please_select_a_product_to_recharge_':
    //     'Please select a product to recharge.',
    // 'security_premium_Benefits_for_Audio__unlimited':
    //     'Premium Benefits for Audio, unlimited',
    // 'security_prior_to_the_creation_process__please_review_our':
    //     'Prior to the creation process, please review our',
    // 'security_privacy_Policy': 'Privacy Policy',
    // 'security_privacy_policy': 'Privacy policy',
    // 'security_pro_Free': 'Pro Free',
    // 'security_pro_only': 'Pro only',
    // 'security_purchase_done': 'Purchase done',
    // 'security_purchased_Success': 'Purchased Success',
    // 'security_purchasing___': 'Purchasing...',
    // 'security_recharge_failed_': 'Recharge failed.',
    // 'security_regeneration_Tips': 'Regeneration Tips',
    // 'security_release_Cancel': 'Release Cancel',
    // 'security_release_Send': 'Release Send',
    // 'security_role_image': 'Role image',
    // 'security_sF_Pro': 'SF Pro',
    // 'security_sF_Pro_bold': 'SF Pro bold',
    // 'security_select_from_gallery': 'Select from gallery',
    // 'security_select_from_the_album': 'Select from the album',
    // 'security_selected_date_is_out_of_range_': 'Selected date is out of range.',
    // 'security_send_failed__please_try_again_later':
    //     'Send failed, please try again later',
    // 'security_send_message__reply_by_AI': 'Send message, reply by AI',
    // 'security_sending___': 'Sending...',
    // 'security_sign_in_with_Apple': 'Sign in with Apple',
    // 'security_sign_in_with_E_mail': 'Sign in with E-mail',
    // 'security_start_create': 'Start create',
    // 'security_submitted_successfully': 'Submitted successfully',
    // 'security_supply_detailed_information_about_the_image__such_as_the_clothing_worn__facial_features__and_actions_':
    //     'Supply detailed information about the image, such as the clothing worn, facial features, and actions.',
    // 'security_take_it_with_camera': 'Take it with camera',
    // 'security_terms_of_Service': 'Terms of Service',
    // 'security_terms_of_service': 'Terms of service',
    // 'security_the_OC_will_address_you_by_the_name_you_enter_':
    //     'The OC will address you by the name you enter.',
    // 'security_the_character_creation_is_still_ongoing__Leaving_at_this_moment_will_forfeit_the_progress_made_so_far__Are_you_sure_you_want_to_go_back_':
    //     'The character creation is still ongoing. Leaving at this moment will forfeit the progress made so far. Are you sure you want to go back?',
    // 'security_the_uploaded_image_serves_as_a_reference_for_facial_features_and_style_elements':
    //     'The uploaded image serves as a reference for facial features and style elements',
    // 'security_turn_on_the_camera': 'Turn on the camera',
    // 'security_unable_to_get_recharge_service__please_retry_later_':
    //     'Unable to get recharge service, please retry later.',
    // 'security_unknown_error__please_upload_again_':
    //     'Unknown error, please upload again.',
    // 'security_unlock_Audio': 'Unlock Audio',
    // 'security_unlock_Image': 'Unlock Image',
    // 'security_unlock_Video': 'Unlock Video',
    // 'security_updating_information___': 'Updating information...',
    // 'security_upload_failed__please_try_again_later':
    //     'Upload failed, please try again later',
    // 'security_uploading_new_avatar___': 'Uploading new avatar...',
    // 'security_you_have_muted': 'You have muted',
    // 'security_supply_detailed_information_about_the_image__such_as_the_clothing_worn__facial_features__and_actions__For_example___On_the_moonlit_balcony_of_a_neo___Victorian_mansion__an_ethereal_woman_with_bright_blue_hime___cut_hair_leans_against_the_railing__Her_khaki_backless_sweater_flutters_gently_in_the_breeze_as_she_turns_to_look_at_the_viewer_with_an_otherworldly_serenity__':
    //     'Supply detailed information about the image, such as the clothing worn, facial features, and actions. For example, "On the moonlit balcony of a neo - Victorian mansion, an ethereal woman with bright blue hime - cut hair leans against the railing. Her khaki backless sweater flutters gently in the breeze as she turns to look at the viewer with an otherworldly serenity."',
    // 'security_cannot_download_source__please_try_again_later':
    //     'Cannot download source, please try again later',
    // 'security_if_you_sign_in__you_agree_to': 'If you sign in, you agree to ',
    // 'security_send_me_a_picture': 'Send me a picture',
    // 'security_send_me_a_video': 'Send me a video',
    // 'security_and_indicate_your_consent_': ' and indicate your consent.',
    // 'security_consuming_props_during_call': 'Consuming props during call',
    // 'security_no_more_companions_to_load_': 'No more companions to load.',
    // 'security_per_minute': ' per minute',
    // 'security_edit': 'Edit',
    // 'security_video_Call': 'Video Call',
    // 'security_i_am_listening___': 'I am listening...',
    // 'security_i_am_thinking___': 'I am thinking...',
    // 'security_audio_Call': 'Audio Call',
    // 'security_canceled_by_caller': 'Canceled by caller',
    // 'security_no_answer__please_try_again_later':
    //     'No answer, please try again later',
    // 'security_no_favorites_yet__go_and_follow_some_people_':
    //     'No favorites yet, go and follow some people!',
    // 'security_benefits_Usage_Detail': 'Benefits Usage Detail',
    // 'security_chat_beyond_reality__role_play_without_limits':
    //     'Chat beyond reality, role play without limits',
    // 'security_please_grant_camera_permission': 'Please grant camera permission',
    // 'security_please_grant_microphone_permission':
    //     'Please grant microphone permission',
    // 'security_unlocking_for_free_': 'Unlocking for free!',
    // 'security_you__re_now_a_premium_member__nYour_benefits_are_unlocked__nExplore_your_new_perks_':
    //     'You\\\'re now a premium member!\\nYour benefits are unlocked.\\nExplore your new perks!',
    // 'security_by_clicking_subscribe__you_will_be_charged__and_your_subscription_will_automatically_renew_at_the_same_price_and_duration_until_canceled_through_App_Store_settings__By_proceeding__you_agree_to_our_terms_':
    //     'By clicking subscribe, you will be charged, and your subscription will automatically renew at the same price and duration until canceled through App Store settings. By proceeding, you agree to our terms.',
    // 'security_daily_Task': 'Daily Task',
    // 'security_premium_Only': 'Premium Only',
    // 'security_introduction': 'Introduction ',
    // 'security_premium_Free': 'Premium Free',
    // 'security_an_error_occurred__please_try_again_later_':
    //     'An error occurred, please try again later.',
    // 'security_product_id_not_found__please_try_again_later':
    //     'Product id not found, please try again later',
    // 'security_call_wasn__t_answered': 'Call wasn\\\'t answered',
    // 'security_cancelled_by_Caller': 'Cancelled by Caller',
    // 'security_consuming_gems_during_call': 'Consuming gems during call',
    // 'security_ending___': 'Ending...',
    // 'security_free_Call': 'Free Call',
    // 'security_not_enough_gems__please_recharge':
    //     'Not enough gems, please recharge',
    // 'security_send_a_message_': 'Send a message…',
    // 'security_free_for_first': 'Free for first ',
    // 'security_error__max_should_not_be_a_negative_number_or_zero':
    //     'Error, max should not be a negative number or zero',
    // 'security_error__min_is_greater_than_or_equal_to_max':
    //     'Error, min is greater than or equal to max',
    // 'security_invites_you': 'Invites you',
    // 'security_aD_Free': 'AD Free',
    // 'security_enter_your_image_prompt__e_g__A_girl__sitting_on_a_bench___':
    //     'Enter your image prompt, e.g. A girl, sitting on a bench...',
    // 'security_failed_to_grant_coin__Please_try_again_later_':
    //     'Failed to grant coin. Please try again later.',
    // 'security_failed_to_unlock_resource__Please_try_again_later_':
    //     'Failed to unlock resource. Please try again later.',
    // 'security_image_prompt_cannot_be_empty': 'Image prompt cannot be empty',
    // 'security_images_you_like': 'Images you like',
    // 'security_please_select_at_least_one_prompt':
    //     'Please select at least one prompt',
    // 'security_signing_in___': 'Signing in...',
    // 'security_all_Chat': 'All Chat',
    // 'security_chat_Models': 'Chat Models',
    // 'security_chat_Now': 'Chat Now',
    // 'security_clear_Chat_History': 'Clear Chat History',
    // 'security_connect_with_everyone_in_one_place':
    //     'Connect with everyone in one place',
    // 'security_contact_us_for_support_': 'Contact us for support.',
    // 'security_delete_Message': 'Delete Message',
    // 'security_design_your_own_unique_character_and_bring_it_to_life_':
    //     'Design your own unique character and bring it to life.',
    // 'security_group_Chat': 'Group Chat',
    // 'security_limited_Free': 'Limited Free ',
    // 'security_mark_all_as_read': 'Mark all as read',
    // 'security_message_Setting': 'Message Setting',
    // 'security_message_setting': 'Message setting',
    // 'security_reset_Success_': 'Reset Success!',
    // 'security_rewind_to_here': 'Rewind to here',
    // 'security_she_will_forget_conversation_history_with_you_':
    //     'She will forget conversation history with you!',
    // 'security_shield_Real__s_Messages': 'Shield Real\\\'s Messages',
    // 'security_soulink_Team': 'Soulink Team',
    // 'security_switch_Failed': 'Switch Failed',
    // 'security_switch_Succeed_enjoy_your_chat': 'Switch Succeed,enjoy your chat',
    // 'security_switch_the_Model': 'Switch the Model',
    // 'security_contact_us': 'Contact us',
    // 'security_iAP_Service_Not_Available': 'IAP Service Not Available',
    // 'security_iAP_not_available__restart_the_app_and_try_again_':
    //     'IAP not available, restart the app and try again.',
    // 'security_item_info_error': 'Item info error',
    // 'security_monthly_Premium': 'Monthly Premium',
    // 'security_no_recharge_item_available__try_again_later':
    //     'No recharge item available, try again later',
    // 'security_payment_failed': 'Payment failed',
    // 'security_payment_successful': 'Payment successful',
    // 'security_purchase_successful': 'Purchase successful',
    // 'security_receipt_Not_Available': 'Receipt Not Available',
    // 'security_special_Offer': 'Special Offer',
    // 'security_weekly_Premium': 'Weekly Premium',
    // 'security_yearly_Premium': 'Yearly Premium',
    // 'security_about_AI_MODE': 'About AI MODE',
    // 'security_about_Me': 'About Me',
    // 'security_add_Group_Member': 'Add Group Member',
    // 'security_add_New_Group_Member': 'Add New Group Member',
    // 'security_are_you_sure_you_want_to_disband_this_group__This_action_cannot_be_undone__and_all_members_will_be_removed_':
    //     'Are you sure you want to disband this group? This action cannot be undone, and all members will be removed.',
    // 'security_auto___enabled__The_mentioned_member_s__will_reply_your_message_':
    //     'Auto @ enabled. The mentioned member(s) will reply your message.',
    // 'security_click_anywhere_to_continue___': 'Click anywhere to continue...',
    // 'security_congratulations__You_got_a_new_MODE__enjoy_it_':
    //     'Congratulations! You got a new MODE, enjoy it.',
    // 'security_contact_List': 'Contact List',
    // 'security_create_Group': 'Create Group',
    // 'security_dating_Game': 'Dating Game',
    // 'security_disband_Group': 'Disband Group',
    // 'security_disband_Group_': 'Disband Group?',
    // 'security_download_failed__please_retry_later_':
    //     'Download failed, please retry later!',
    // 'security_edit_Group_Name': 'Edit Group Name',
    // 'security_edit_Group_Scenario': 'Edit Group Scenario',
    // 'security_enter_the_Group_Scenario': 'Enter the Group Scenario',
    // 'security_enter_the_group_name': 'Enter the group name',
    // 'security_error_occurred__please_try_again':
    //     'Error occurred, please try again',
    // 'security_go_Play': 'Go Play',
    // 'security_group_Info': 'Group Info',
    // 'security_group_Member': 'Group Member',
    // 'security_group_Name': 'Group Name',
    // 'security_group_Owner': 'Group Owner',
    // 'security_group_Scenario': 'Group Scenario',
    // 'security_in_Use': 'In Use',
    // 'security_in_use': 'In use',
    // 'security_level_Up_': 'Level Up!',
    // 'security_my_OCs': 'My OCs',
    // 'security_not_enough_balance': 'Not enough balance',
    // 'security_please_agree_to_the_terms_below_first_':
    //     'Please agree to the terms below first.',
    // 'security_popular_Search': 'Popular Search',
    // 'security_recent_Search': 'Recent Search',
    // 'security_search_Failed': 'Search Failed',
    // 'security_search_Users_by_ID_or_Name': 'Search Users by ID or Name',
    // 'security_some_error_occur__please_retry_later_':
    //     'Some error occur, please retry later!',
    // 'security_some_error_occurred__try_again_later_':
    //     'Some error occurred, try again later.',
    // 'security_some_error_occurred__Please_try_again_later_':
    //     'Some error occurred. Please try again later.',
    // 'security_start_Game': 'Start Game',
    // 'security_switch_Succeed__enjoy_your_chat':
    //     'Switch Succeed, enjoy your chat',
    // 'security_switch_to_Chat': 'Switch to Chat',
    // 'security_take_a_look__': 'Take a look >',
    // 'security_the_MODE_will_only_take_effect_after_you_have_acquired_this_character__Continue_purchasing_':
    //     'The MODE will only take effect after you have acquired this character. Continue purchasing?',
    // 'security_the_muted_member_will_not_reply_your_message':
    //     'The muted member will not reply your message',
    // 'security_this_member_is_deactivated_': 'This member is deactivated.',
    // 'security_this_member_is_expired_': 'This member is expired.',
    // 'security_time_limit': 'Time limit',
    // 'security_try_it': 'Try it',
    // 'security_unlock_conditions_not_met__Upgrade_your_level_now_':
    //     'Unlock conditions not met. Upgrade your level now!',
    // 'security_unlock_tips': 'Unlock tips',
    // 'security_your_reward': 'Your reward',
    // 'security_edit_My_Character': 'Edit My Character',
    // 'security_message_Settings': 'Message Settings',
    // 'security_no_datas__click_to_retry_': 'No datas, click to retry.',
    // 'security_start_Chat': 'Start Chat',
    // 'security_send_a_message___': 'Send a message...',
    // 'security_send_me_a_pic_with_you_tucking_hair_behind_ear_in_sunset__Send_me_a_pic_with_you_touching_flower_petals_at_dusk__Send_me_a_pic_with_you_holding_teacup_by_rain_window__Send_me_a_pic_with_you_twirling_silk_scarf_by_the_lake__Send_me_a_pic_with_you_adjusting_shoelace_in_sunlight__Send_me_a_pic_with_you_skimming_calm_fountain_surface__Send_me_a_pic_with_you_wrapping_shawl_on_the_balcony':
    //     'Send me a pic with you tucking hair behind ear in sunset||Send me a pic with you touching flower petals at dusk||Send me a pic with you holding teacup by rain window||Send me a pic with you twirling silk scarf by the lake||Send me a pic with you adjusting shoelace in sunlight||Send me a pic with you skimming calm fountain surface||Send me a pic with you wrapping shawl on the balcony',
    // 'security_nice_to_meet_you_': 'Nice to meet you!',
    // 'security_sign_in_with_Google': 'Sign in with Google',
    // 'security_failed_to_save__image_URL_is_empty':
    //     'Failed to save, image URL is empty',
    // 'security_failed_to_save__try_again_later':
    //     'Failed to save, try again later',
    // 'security_failed_to_save__try_again_later_Data_Empty_':
    //     'Failed to save, try again later[Data Empty]',
    // 'security_saved_successfully': 'Saved successfully',
    // 'security_saving___': 'Saving...',
    // 'security_scenario': 'Scenario ',
    // 'security_are_you_sure_you_want_to_block_this_user_':
    //     'Are you sure you want to block this user?',
    // 'security_bock_Messages_from_Strangers': 'Bock Messages from Strangers',
    // 'security_aI_Writer': 'AI Writer',
    // 'security_permission_settings': 'Permission settings',
    // 'security_the_existing_filled_content_will_be_replaced_by_the_template_content_and_cannot_be_undone_':
    //     'The existing filled content will be replaced by the template content and cannot be undone.',
    // 'security_what_should_AI_call_you': 'What should AI call you',
    // 'security_generation_failed__please_try_again_later_':
    //     'Generation failed, please try again later.',
    // 'security_copied_ID_to_clipboard': 'Copied ID to clipboard',
    // 'security_character_name_must_be_at_least_3_letters_':
    //     'Character name must be at least 3 letters.',
    // 'security_more_Details': 'More Details',
    // 'security_feedback_Log': 'Feedback Log',
    // 'security_image_is_Not_ready__please_try_again_later_':
    //     'Image is Not ready, please try again later.',
    // 'security_not_approved': 'Not approved',
    // 'security_under_review': 'Under review',
    // 'security_upload_Log_success': 'Upload Log success',
    // 'security_about_Soulink': 'About Soulink',
    // 'security_are_you_sure_': 'Are you sure?',
    // 'security_character_is_private': 'Character is private',
    // 'security_complete_tasks_to_get_rewards': 'Complete tasks to get rewards',
    // 'security_cost_Trial_Card': 'Cost Trial Card',
    // 'security_create_Character': 'Create Character',
    // 'security_create_Moment': 'Create Moment',
    // 'security_create_an_image_with_Generator': 'Create an image with Generator',
    // 'security_currently_owns_': 'Currently owns: ',
    // 'security_daily_post_limit_exceeded': 'Daily post limit exceeded',
    // 'security_describe_what_you_want__e_g___A_barista_wipes_the_counter_of_a_small_caf__by_the_river__steam_rising_from_coffee_cups__boats_passing_slowly_outside_the_window__a_cat_napping_on_a_nearby_chair_':
    //     'Describe what you want, e.g., A barista wipes the counter of a small café by the river, steam rising from coffee cups, boats passing slowly outside the window, a cat napping on a nearby chair.',
    // 'security_don_t_remind_me_again': 'Don\'t remind me again',
    // 'security_enable_this_option_to_allow_the_AI_to_generate_image_galleries_based_on_your_information_':
    //     'Enable this option to allow the AI to generate image galleries based on your information.',
    // 'security_enter_the_Description': 'Enter the Description',
    // 'security_exit_Video_Matching_': 'Exit Video Matching?',
    // 'security_failed_Generate': 'Failed Generate',
    // 'security_failed_reload': 'Failed reload',
    // 'security_first_message_from_your_character__It_will_help_the_chat_get_off_to_a_better_start_':
    //     'First message from your character. It will help the chat get off to a better start.',
    // 'security_for_You': 'For You',
    // 'security_generate_Video': 'Generate Video',
    // 'security_generate_config_loading': 'Generate config loading',
    // 'security_generate_for_Moment': 'Generate for Moment',
    // 'security_generate_video': 'Generate video',
    // 'security_generating_Gallery': 'Generating Gallery',
    // 'security_get_30s_Free_Trial': 'Get 30s Free Trial',
    // 'security_go_Setting': 'Go Setting',
    // 'security_grants_the_first_30_seconds_of_the_call_for_free__After_that__gems_will_be_charged_':
    //     'Grants the first 30 seconds of the call for free. After that, gems will be charged.',
    // 'security_i_understand': 'I understand',
    // 'security_image_details__facial_features__clothing':
    //     'Image details, facial features, clothing',
    // 'security_initial_Message': 'Initial Message',
    // 'security_invites_you_to_video_calling_': 'Invites you to video calling…',
    // 'security_lets_you_make_calls_without_spending_gems_':
    //     'Lets you make calls without spending gems.',
    // 'security_mM_dd_HH_mm': 'MM-dd HH:mm',
    // 'security_maximum_limit_exceeded': 'Maximum limit exceeded',
    // 'security_no_report_reasons_available': 'No report reasons available',
    // 'security_operation_failed': 'Operation failed',
    // 'security_permission_required': 'Permission required',
    // 'security_please_allow_access_to_the_camera_in_the_settings':
    //     'Please allow access to the camera in the settings',
    // 'security_please_allow_access_to_the_microphone_in_the_settings':
    //     'Please allow access to the microphone in the settings',
    // 'security_please_input_description': 'Please input description',
    // 'security_please_select_a_character_first':
    //     'Please select a character first',
    // 'security_post_As': 'Post As',
    // 'security_post_successful': 'Post successful',
    // 'security_post_updates_for_your_character_and_bring_every_moment_of_their_story_to_life_':
    //     'Post updates for your character and bring every moment of their story to life!',
    // 'security_post_your_reply': 'Post your reply',
    // 'security_report_Success_': 'Report Success!',
    // 'security_select_From_Chat_History_Album': 'Select From Chat History Album',
    // 'security_select_Image': 'Select Image',
    // 'security_select_a_Character': 'Select a Character',
    // 'security_start_Match': 'Start Match',
    // 'security_switching_characters_will_clear_the_current_content':
    //     'Switching characters will clear the current content',
    // 'security_the_user_has_been_matched__and_the_other_party_accepts_and_enters_the_video_call':
    //     'The user has been matched, and the other party accepts and enters the video call',
    // 'security_this_moment_does_not_meet_community_requirements__please_edit':
    //     'This moment does not meet community requirements, please edit',
    // 'security_translation_failure_': 'Translation failure…',
    // 'security_you_need_to_have_your_own_role_to_post___nGo_create_a_character':
    //     'You need to have your own role to post! \\nGo create a character',
    // 'security_you_re_now_using_your_trial_card_or_available_call_time___whichever_applies_':
    //     'You\'re now using your trial card or available call time — whichever applies.',
    // 'security_please_grant_storage_permission':
    //     'Please grant storage permission',
    // 'security_brush_a_strand_of_hair_back_gently__eyes_soft_as_you_gaze_straight_at_me_':
    //     'Brush a strand of hair back gently, eyes soft as you gaze straight at me.',
    // 'security_hold_a_book_loosely_in_your_hand__flipping_a_page_slowly_as_you_glance_up_':
    //     'Hold a book loosely in your hand, flipping a page slowly as you glance up.',
    // 'security_hold_a_cup_of_warm_drink__blowing_on_it_softly_before_taking_a_small_sip_':
    //     'Hold a cup of warm drink, blowing on it softly before taking a small sip.',
    // 'security_lean_against_a_bar_counter__drink_in_hand__shoulders_loose_':
    //     'Lean against a bar counter, drink in hand, shoulders loose.',
    // 'security_lean_against_a_bookshelf__one_hand_brushing_the_spines__calm_and_unhurried_':
    //     'Lean against a bookshelf, one hand brushing the spines, calm and unhurried.',
    // 'security_lean_against_a_wall__arms_loosely_crossed__watching_me_':
    //     'Lean against a wall, arms loosely crossed, watching me.',
    // 'security_lean_against_the_door_frame__one_leg_crossed_casually__smiling_as_you_watch_me_approach_':
    //     'Lean against the door frame, one leg crossed casually, smiling as you watch me approach.',
    // 'security_lean_forward_a_little__head_tilted__listening_intently_with_a_calm_expression_':
    //     'Lean forward a little, head tilted, listening intently with a calm expression.',
    // 'security_lounge_on_a_pool_chair__sunglasses_pushed_up_as_you_glance_over_':
    //     'Lounge on a pool chair, sunglasses pushed up as you glance over.',
    // 'security_relax_on_a_couch__one_arm_resting_casually_as_you_smile_':
    //     'Relax on a couch, one arm resting casually as you smile.',
    // 'security_relax_on_a_sofa_in_the_evening__warm_lights_around_you_':
    //     'Relax on a sofa in the evening, warm lights around you.',
    // 'security_rest_one_elbow_on_the_table__fingers_tapping_lightly_as_you_smile_lazily_':
    //     'Rest one elbow on the table, fingers tapping lightly as you smile lazily.',
    // 'security_rest_your_chin_on_your_hand__looking_at_me_thoughtfully_':
    //     'Rest your chin on your hand, looking at me thoughtfully.',
    // 'security_rest_your_head_back_against_the_cushion__eyes_half_closed__relaxed_and_unguarded_':
    //     'Rest your head back against the cushion, eyes half-closed, relaxed and unguarded.',
    // 'security_rest_your_palms_flat_on_the_table__leaning_back_slightly__breathing_slowly_and_steadily_':
    //     'Rest your palms flat on the table, leaning back slightly, breathing slowly and steadily.',
    // 'security_sit_at_a_rooftop_bar__elbows_on_the_railing__looking_out_at_the_night_view_lazily_':
    //     'Sit at a rooftop bar, elbows on the railing, looking out at the night view lazily.',
    // 'security_sit_at_a_table_with_a_drink_nearby__glancing_up_like_you_noticed_me_':
    //     'Sit at a table with a drink nearby, glancing up like you noticed me.',
    // 'security_sit_at_an_outdoor_caf___one_hand_around_a_glass__relaxed_posture_':
    //     'Sit at an outdoor café, one hand around a glass, relaxed posture.',
    // 'security_sit_back_in_a_chair__legs_relaxed__eyes_steady_on_me_':
    //     'Sit back in a chair, legs relaxed, eyes steady on me.',
    // 'security_sit_by_the_pool_in_a_swimsuit__holding_a_cocktail_and_smiling_':
    //     'Sit by the pool in a swimsuit, holding a cocktail and smiling.',
    // 'security_sit_by_the_window_with_soft_light_on_your_face__slowly_looking_at_me_':
    //     'Sit by the window with soft light on your face, slowly looking at me.',
    // 'security_sit_close_to_the_camera__relaxed_and_at_ease_':
    //     'Sit close to the camera, relaxed and at ease.',
    // 'security_sit_in_a_quiet_room__warm_light_behind_you__calm_and_unhurried_':
    //     'Sit in a quiet room, warm light behind you, calm and unhurried.',
    // 'security_sit_in_a_rattan_chair__rocking_it_gently__body_loose_and_eyes_peaceful_':
    //     'Sit in a rattan chair, rocking it gently, body loose and eyes peaceful.',
    // 'security_sit_in_a_softly_lit_room__body_relaxed__attention_forward_':
    //     'Sit in a softly lit room, body relaxed, attention forward.',
    // 'security_sit_on_a_balcony_at_night__city_lights_behind_you_':
    //     'Sit on a balcony at night, city lights behind you.',
    // 'security_sit_on_a_garden_bench__surrounded_by_faint_floral_scent__hands_resting_on_the_sides_quietly_':
    //     'Sit on a garden bench, surrounded by faint floral scent, hands resting on the sides quietly.',
    // 'security_sit_on_a_terrace__breeze_moving_slightly_as_you_look_over_':
    //     'Sit on a terrace, breeze moving slightly as you look over.',
    // 'security_sit_on_the_edge_of_the_bed__bare_feet_on_the_carpet__looking_relaxed_and_quiet_':
    //     'Sit on the edge of the bed, bare feet on the carpet, looking relaxed and quiet.',
    // 'security_stand_by_the_floor_to_ceiling_window__silhouette_against_the_sky__staring_into_the_distance_softly_':
    //     'Stand by the floor-to-ceiling window, silhouette against the sky, staring into the distance softly.',
    // 'security_stand_in_a_dimly_lit_hallway__light_outlining_your_figure__looking_at_me_calmly_':
    //     'Stand in a dimly lit hallway, light outlining your figure, looking at me calmly.',
    // 'security_stand_in_the_warm_sunlight__closing_your_eyes_briefly__then_opening_them_to_look_at_me_':
    //     'Stand in the warm sunlight, closing your eyes briefly, then opening them to look at me.',
    // 'security_stand_near_a_railing__resting_one_arm_while_watching_quietly_':
    //     'Stand near a railing, resting one arm while watching quietly.',
    // 'security_stand_near_the_pool__water_reflecting_while_you_take_a_slow_sip_':
    //     'Stand near the pool, water reflecting while you take a slow sip.',
    // 'security_stretch_slightly_in_your_seat__then_settle_back_comfortably_':
    //     'Stretch slightly in your seat, then settle back comfortably.',
    // 'security_stretch_your_arms_overhead_lazily__then_drop_them_down__slumping_comfortably_in_the_chair_':
    //     'Stretch your arms overhead lazily, then drop them down, slumping comfortably in the chair.',
    // 'security_tilt_your_glass_slowly__swirling_the_drink_inside__watching_me_with_a_faint_smile_':
    //     'Tilt your glass slowly, swirling the drink inside, watching me with a faint smile.',
    // 'security_turn_toward_me_slowly__like_I_just_arrived_':
    //     'Turn toward me slowly, like I just arrived.',
    // 'security_twist_the_ring_on_your_finger_gently__eyes_thoughtful_as_you_fix_your_gaze_on_me_':
    //     'Twist the ring on your finger gently, eyes thoughtful as you fix your gaze on me.',
    // 'security_wrap_your_arms_around_your_knees__sitting_curled_up_slightly__eyes_warm_on_me_':
    //     'Wrap your arms around your knees, sitting curled up slightly, eyes warm on me.',
    // 'security_create_your_account': 'Create your account',
    // 'security_input_content_here__Option_': 'Input content here (Option)',
    // 'security_mina_Team': 'Mina Team',
    // 'security_story_background': 'Story background',
    // 'security_tap_to_continue___': 'Tap to continue...',
    // 'security_aI_Character': 'AI Character',
    // 'security_ask_for_pic': 'Ask for pic',
    // 'security_ask_for_video': 'Ask for video',
    // 'security_before_creation__please_review':
    //     'Before creation, please review ',
    // 'security_coins_balance': 'Coins balance',
    // 'security_fail_to_collect': 'Fail to collect',
    // 'security_gems_balance': 'Gems balance',
    // 'security_mM_dd__HH_mm_': 'MM月dd日 HH时mm分',
    // 'security_my_Coins': 'Coins',
    // 'security_my_Gems': 'Gems',
    // 'security_notice__AI_responses_are_fictional_and_for_entertainment_only':
    //     'Notice: AI responses are fictional and for entertainment only',
    // 'security_plus_button_tapped': 'Plus button tapped',
    // 'security_start_Create': 'Start Create',
    // 'security_unsupported_message_type': 'Unsupported message type',
    // 'security_voice_button_tapped': 'Voice button tapped',
    // 'security_All_Chat': 'All Chat',
    // 'security_Create_Video': 'Create Video',
    // 'security_Generate_Video': 'Generate Video',
    // 'security_Mina_Support': 'Mina Support',
    // 'security_No_groups_yet__go_create_one_': 'No groups yet, go create one!',
    // 'security_Please_input_description': 'Please input description',
    // 'security_Search_by_ID__name__tag___': 'Search by ID, name, tag...',
    // 'security_The_app_may_not_function_as_expected_until_you_remove_this_plugin_from_pubspec_yaml':
    //     'The app may not function as expected until you remove this plugin from pubspec.yaml',
    // 'security_Video_initialization_failed': 'Video initialization failed',
    // 'security_Got_coins_reward': 'Got coins reward',
    // 'security_Unlock_this_photo': 'Unlock this photo',
    // 'security_Unlocked_successfully': 'Unlocked successfully',
    // 'security_Your_balance': 'Your balance',
    // 'security_language': 'Language',
    // 'security_select_language': 'Select language',
    // 'security_settings': 'Settings',
    'security_Cancel': 'Cancel',
    'security_Confirm': 'Confirm',
    'security_unlock_cost': 'Unlocking will cost {amount} {currency}',
    'security_reset': 'Reset',
    'security_Report': 'Report',
    'security_block': 'Block',
    'security_switch': 'Switch',
    'security_reset_user': 'Reset {name}?',
    'security_clear_history_with_user': 'Clear history with "{name}"',
    'security_clear_history_confirmation': 'Are you sure you want to clear all history with "{name}" (including texts, images, videos...)? This action cannot be undone.',
  };
}
