// Generated by toolchain/translate/generate_copywriting_localizations.py.
// Edit Copywriting or the generator instead of changing keys by hand.

abstract final class CopywritingStringsIt {
  static const Map<String, String> values = <String, String>{
    'security_notifications': 'Notifiche',
    'security_collections': 'Raccolte',
    'security_feedback': 'Feedback',
    'security_about_her': 'Su di lei',
    'security_account_Deletion': 'Cancellazione dell\'account',
    'security_add_rounds': 'Aggiungi giri',
    'security_all_Gender': 'Tutti i sessi',
    'security_appears_exclusively_in_your_character__s_public_profile_This_biographical_information_will_not_be_utilized_in_generation_prompts_or_influence_behavioral_patterns_':
        'Appare esclusivamente nel profilo pubblico del tuo personaggio. Queste informazioni biografiche non verranno utilizzate nei suggerimenti di generazione né influenzeranno i modelli comportamentali.',
    'security_are_you_sure_you_want_to_delete_your_account_':
        'Sei sicuro di voler eliminare il tuo account?',
    'security_are_you_sure_you_want_to_log_out_': 'Sei sicuro di voler uscire?',
    'security_audio_Library': 'Libreria audio',
    'security_audio_input_is_too_short_to_send_':
        'L\'ingresso audio è troppo breve per essere inviato.',
    'security_avatar_upload_failed__please_try_again_later_':
        'Caricamento avatar non riuscito, riprova più tardi.',
    'security_avatar_uploaded': 'Avatar caricato',
    'security_birth_date': 'Data di nascita',
    'security_by_clicking_Security_security_Subscribe__you_will_be_charged__and_your_subscription_will_automatically_renew_at_the_same_price_and_duration_until_canceled_through_PlayStore_settings__By_proceeding__you_agree_to_our_terms_':
        'Facendo clic su Security.security_Subscribe, ti verrà addebitato un importo e il tuo abbonamento si rinnoverà automaticamente allo stesso prezzo e alla stessa durata fino all\'annullamento tramite le impostazioni del PlayStore. Procedendo accetti i nostri termini.',
    'security_call_Duration': 'Durata della chiamata',
    'security_cannot_get_information__please_retry_later':
        'Impossibile ottenere informazioni, riprovare più tardi',
    'security_cannot_get_physique_details__please_retry_later':
        'Impossibile ottenere i dettagli del fisico, riprovare più tardi',
    'security_cannot_open_date_picker__please_retry_later':
        'Impossibile aprire il selettore della data, riprovare più tardi',
    'security_click_to_add': 'Fare clic per aggiungere',
    'security_click_to_play': 'Fare clic per riprodurre',
    'security_coin_balance': 'Saldo delle monete',
    'security_connecting___': 'Collegamento...',
    'security_copyright_Agreement': 'Accordo sul diritto d\'autore',
    'security_create_My_Character': 'Crea il mio personaggio',
    'security_create_Now': 'Crea ora',
    'security_create_an_account': 'Crea un account',
    'security_current_device_not_support__try_restart_app_':
        'Il dispositivo corrente non è supportato, prova a riavviare l\'app.',
    'security_defines_the_conversational_patterns_between_you_and_your_character__This_crucial_setting_determines_how_your_character_formulates_responses_and_maintains_personality_consistency_':
        'Definisce gli schemi di conversazione tra te e il tuo personaggio. Questa impostazione cruciale determina il modo in cui il tuo personaggio formula le risposte e mantiene la coerenza della personalità.',
    'security_delete_account_': 'Eliminare l\'account?',
    'security_deleting___': 'Eliminazione...',
    'security_describe_the_conversation_scenario_and_involved_characters_':
        'Descrivi lo scenario della conversazione e i personaggi coinvolti.',
    'security_describe_the_issue': 'Descrivere il problema',
    'security_dialogue_Style': 'Stile di dialogo',
    'security_edit_information': 'Modificare le informazioni',
    'security_enter_verification_code': 'Inserisci il codice di verifica',
    'security_entry_your_email': 'Inserisci la tua email',
    'security_expires_on': 'Scade il',
    'security_failed_to_follow': 'Impossibile seguire',
    'security_failed_to_load_subscription_data':
        'Impossibile caricare i dati dell\'abbonamento',
    'security_failed_to_process_subscription__please_try_again_later_':
        'Impossibile elaborare l\'iscrizione, riprovare più tardi.',
    'security_failed_to_record_audio__please_try_again':
        'Impossibile registrare l\'audio, riprovare',
    'security_failed_to_send_gift': 'Impossibile inviare il regalo',
    'security_failed_to_unfollow': 'Impossibile smettere di seguire',
    'security_failed_to_update__please_retry_later':
        'Impossibile aggiornare, riprovare più tardi',
    'security_feelie_Pro': 'Feelie Pro',
    'security_fill_in_your_introduction___': 'Completa la tua introduzione...',
    'security_following_the_regeneration_process__you_ll_receive_a_brand_new_image__You_are_also_welcome_to_revisit_the_images_you_created_earlier__Are_you_ready_to_move_forward_':
        'Dopo il processo di rigenerazione, riceverai un\'immagine nuova di zecca. Puoi anche rivisitare le immagini che hai creato in precedenza. Sei pronto per andare avanti?',
    'security_for_example___On_the_moonlit_balcony_of_a_neo___Victorian_mansion__an_ethereal_woman_with_bright_blue_hime___cut_hair':
        'Ad esempio, "Sul balcone illuminato dalla luna di una villa neo-vittoriana, una donna eterea con capelli tagliati hime di un blu brillante',
    'security_gem_balance': 'Equilibrio delle gemme',
    'security_generating_in_progress': 'Generazione in corso',
    'security_generating___': 'Generazione...',
    'security_get_full_access_': 'Ottieni accesso completo!',
    'security_hold_to_talk': 'Aspetta per parlare',
    'security_how_would_you_like_OC_to_address_you_':
        'Come vorresti che OC si rivolgesse a te?',
    'security_image_Prompt': 'Richiesta immagine',
    'security_information_updated_': 'Informazioni aggiornate.',
    'security_insufficient_balance_': 'Equilibrio insufficiente.',
    'security_interrupt_AI': 'Interrompi l\'IA',
    'security_loading___': 'Caricamento...',
    'security_log_out': 'Disconnettersi',
    'security_logging_in___': 'Accesso...',
    'security_master_name_must_be_2_24_characters_in_length':
        'Il nome del master deve contenere da 2 a 24 caratteri',
    'security_modify_Now': 'Modifica ora',
    'security_name_your_character': 'Dai un nome al tuo personaggio',
    'security_network_error': 'Errore di rete',
    'security_network_error__please_try_again_later':
        'Errore di rete, riprovare più tardi',
    'security_network_exception__please_try_again_later':
        'Eccezione di rete, riprovare più tardi',
    'security_no_chat_partner_has_been_initiated_yet':
        'Nessun partner di chat è stato ancora avviato',
    'security_no_companions_yet': 'Ancora nessun compagno',
    'security_no_data': 'Nessun dato',
    'security_no_user_information__getting_back___':
        'Nessuna informazione utente, ritorno in corso...',
    'security_notice__Everything_AI_says_is_made_up':
        'Nota: tutto ciò che dice l\'intelligenza artificiale è inventato',
    'security_obtain_code': 'Ottieni il codice',
    'security_platform_not_supported_': 'Piattaforma non supportata.',
    'security_please_agree_to_the_terms_and_conditions':
        'Si prega di accettare i termini e le condizioni',
    'security_please_select_a_product_to_recharge_':
        'Selezionare un prodotto da ricaricare.',
    'security_premium_Benefits_for_Audio__unlimited':
        'Vantaggi Premium per l\'audio, illimitati',
    'security_prior_to_the_creation_process__please_review_our':
        'Prima del processo di creazione, consultare il nostro',
    'security_privacy_Policy': 'Informativa sulla privacy',
    'security_privacy_policy': 'Informativa sulla privacy',
    'security_pro_Free': 'Pro gratuito',
    'security_pro_only': 'Solo versione professionale',
    'security_purchase_done': 'Acquisto effettuato',
    'security_purchased_Success': 'Successo acquistato',
    'security_purchasing___': 'Acquisto...',
    'security_recharge_failed_': 'Ricarica non riuscita.',
    'security_regeneration_Tips': 'Suggerimenti per la rigenerazione',
    'security_release_Cancel': 'Rilascia Annulla',
    'security_release_Send': 'Rilascia invio',
    'security_role_image': 'Immagine del ruolo',
    'security_sF_Pro': 'SF Pro',
    'security_sF_Pro_bold': 'SF Pro bold',
    'security_select_from_gallery': 'Selezionare dalla galleria',
    'security_select_from_the_album': 'Selezionare dall\'album',
    'security_selected_date_is_out_of_range_':
        'La data selezionata non è compresa nell\'intervallo.',
    'security_send_failed__please_try_again_later':
        'Invio fallito, riprovare più tardi',
    'security_send_message__reply_by_AI':
        'Invia messaggio, risposta tramite AI',
    'security_sending___': 'Invio...',
    'security_sign_in_with_Apple': 'Accedi con Apple',
    'security_sign_in_with_E_mail': 'Accedi con l\'e-mail',
    'security_start_create': 'Avvia la creazione',
    'security_submitted_successfully': 'Inserito con successo',
    'security_supply_detailed_information_about_the_image__such_as_the_clothing_worn__facial_features__and_actions_':
        'Fornire informazioni dettagliate sull\'immagine, come gli abiti indossati, i tratti del viso e le azioni.',
    'security_take_it_with_camera': 'Scattalo con la fotocamera',
    'security_terms_of_Service': 'Termini di servizio',
    'security_terms_of_service': 'Termini di servizio',
    'security_the_OC_will_address_you_by_the_name_you_enter_':
        'L\'OC si rivolgerà a te con il nome che hai inserito.',
    'security_the_character_creation_is_still_ongoing__Leaving_at_this_moment_will_forfeit_the_progress_made_so_far__Are_you_sure_you_want_to_go_back_':
        'La creazione del personaggio è ancora in corso. Lasciare in questo momento farà perdere i progressi fatti finora. Sei sicuro di voler tornare indietro?',
    'security_the_uploaded_image_serves_as_a_reference_for_facial_features_and_style_elements':
        'L\'immagine caricata funge da riferimento per le caratteristiche del viso e gli elementi di stile',
    'security_turn_on_the_camera': 'Accendere la fotocamera',
    'security_unable_to_get_recharge_service__please_retry_later_':
        'Impossibile ottenere il servizio di ricarica, riprovare più tardi.',
    'security_unknown_error__please_upload_again_':
        'Errore sconosciuto, caricare nuovamente.',
    'security_unlock_Audio': 'Sblocca audio',
    'security_unlock_Image': 'Sblocca immagine',
    'security_unlock_Video': 'Sblocca video',
    'security_updating_information___': 'Aggiornamento delle informazioni...',
    'security_upload_failed__please_try_again_later':
        'Caricamento non riuscito, riprova più tardi',
    'security_uploading_new_avatar___': 'Caricamento nuovo avatar...',
    'security_you_have_muted': 'Hai disattivato l\'audio',
    'security_supply_detailed_information_about_the_image__such_as_the_clothing_worn__facial_features__and_actions__For_example___On_the_moonlit_balcony_of_a_neo___Victorian_mansion__an_ethereal_woman_with_bright_blue_hime___cut_hair_leans_against_the_railing__Her_khaki_backless_sweater_flutters_gently_in_the_breeze_as_she_turns_to_look_at_the_viewer_with_an_otherworldly_serenity__':
        'Fornire informazioni dettagliate sull\'immagine, come gli abiti indossati, i tratti del viso e le azioni. Ad esempio, "Sul balcone illuminato dalla luna di una villa neo-vittoriana, una donna eterea con i capelli tagliati blu brillante si appoggia alla ringhiera. Il suo maglione color kaki senza schienale svolazza dolcemente nella brezza mentre si gira a guardare lo spettatore con una serenità ultraterrena."',
    'security_cannot_download_source__please_try_again_later':
        'Impossibile scaricare la sorgente, riprovare più tardi',
    'security_if_you_sign_in__you_agree_to': 'Se accedi accetti',
    'security_send_me_a_picture': 'Mandami una foto',
    'security_send_me_a_video': 'Inviami un video',
    'security_and_indicate_your_consent_': 'e indica il tuo consenso.',
    'security_consuming_props_during_call':
        'Consumare oggetti di scena durante la chiamata',
    'security_no_more_companions_to_load_': 'Niente più compagni da caricare.',
    'security_per_minute': 'al minuto',
    'security_edit': 'Modifica',
    'security_video_Call': 'Videochiamata',
    'security_i_am_listening___': 'Ascolto...',
    'security_i_am_thinking___': 'Sto pensando...',
    'security_audio_Call': 'Chiamata audio',
    'security_canceled_by_caller': 'Annullato dal chiamante',
    'security_no_answer__please_try_again_later':
        'Nessuna risposta, riprovare più tardi',
    'security_no_favorites_yet__go_and_follow_some_people_':
        'Ancora nessun preferito, vai e segui alcune persone!',
    'security_benefits_Usage_Detail': 'Dettagli sull\'utilizzo dei vantaggi',
    'security_chat_beyond_reality__role_play_without_limits':
        'Chatta oltre la realtà, giochi di ruolo senza limiti',
    'security_please_grant_camera_permission':
        'Concedere l\'autorizzazione alla fotocamera',
    'security_please_grant_microphone_permission':
        'Concedere l\'autorizzazione al microfono',
    'security_unlocking_for_free_': 'Sblocco gratuito!',
    'security_you__re_now_a_premium_member__nYour_benefits_are_unlocked__nExplore_your_new_perks_':
        'Ora sei un membro premium!\\nI tuoi vantaggi sono sbloccati.\\nEsplora i tuoi nuovi vantaggi!',
    'security_by_clicking_subscribe__you_will_be_charged__and_your_subscription_will_automatically_renew_at_the_same_price_and_duration_until_canceled_through_App_Store_settings__By_proceeding__you_agree_to_our_terms_':
        'Facendo clic su abbonati, ti verrà addebitato un importo e l\'abbonamento si rinnoverà automaticamente allo stesso prezzo e alla stessa durata fino all\'annullamento tramite le impostazioni dell\'App Store. Procedendo accetti i nostri termini.',
    'security_daily_Task': 'Compito quotidiano',
    'security_premium_Only': 'Solo Premium',
    'security_introduction': 'Introduzione',
    'security_premium_Free': 'Premio gratuito',
    'security_an_error_occurred__please_try_again_later_':
        'Si è verificato un errore, riprovare più tardi.',
    'security_product_id_not_found__please_try_again_later':
        'ID prodotto non trovato, riprova più tardi',
    'security_call_wasn__t_answered': 'La chiamata non ha ricevuto risposta',
    'security_cancelled_by_Caller': 'Annullato dal chiamante',
    'security_consuming_gems_during_call':
        'Consumare gemme durante la chiamata',
    'security_ending___': 'Fine...',
    'security_free_Call': 'Chiamata gratuita',
    'security_not_enough_gems__please_recharge':
        'Gemme insufficienti, ricarica',
    'security_send_a_message_': 'Invia un messaggio...',
    'security_free_for_first': 'Gratuito per il primo',
    'security_error__max_should_not_be_a_negative_number_or_zero':
        'Errore, max non deve essere un numero negativo o zero',
    'security_error__min_is_greater_than_or_equal_to_max':
        'Errore, il minimo è maggiore o uguale al massimo',
    'security_invites_you': 'Ti invita',
    'security_aD_Free': 'Gratuito d.C',
    'security_enter_your_image_prompt__e_g__A_girl__sitting_on_a_bench___':
        'Inserisci la richiesta dell\'immagine, ad es. Una ragazza, seduta su una panchina...',
    'security_failed_to_grant_coin__Please_try_again_later_':
        'Impossibile concedere la moneta. Per favore riprova più tardi.',
    'security_failed_to_unlock_resource__Please_try_again_later_':
        'Impossibile sbloccare la risorsa. Per favore riprova più tardi.',
    'security_image_prompt_cannot_be_empty':
        'Il prompt dell\'immagine non può essere vuoto',
    'security_images_you_like': 'Immagini che ti piacciono',
    'security_please_select_at_least_one_prompt':
        'Selezionare almeno un prompt',
    'security_signing_in___': 'Accesso...',
    'security_all_Chat': 'Tutte le chat',
    'security_chat_Models': 'Modelli di chat',
    'security_chat_Now': 'Chatta ora',
    'security_clear_Chat_History': 'Cancella cronologia chat',
    'security_connect_with_everyone_in_one_place':
        'Connettiti con tutti in un unico posto',
    'security_contact_us_for_support_': 'Contattaci per ricevere supporto.',
    'security_delete_Message': 'Elimina messaggio',
    'security_design_your_own_unique_character_and_bring_it_to_life_':
        'Progetta il tuo personaggio unico e dagli vita.',
    'security_group_Chat': 'Chat di gruppo',
    'security_limited_Free': 'Gratuito limitato',
    'security_mark_all_as_read': 'Segna tutto come letto',
    'security_message_Setting': 'Impostazione dei messaggi',
    'security_message_setting': 'Impostazione del messaggio',
    'security_reset_Success_': 'Ripristino riuscito!',
    'security_rewind_to_here': 'Torna indietro fino a qui',
    'security_she_will_forget_conversation_history_with_you_':
        'Dimenticherà la cronologia delle conversazioni con te!',
    'security_shield_Real__s_Messages': 'Proteggi i messaggi di Real',
    'security_soulink_Team': 'Squadra Soulink',
    'security_switch_Failed': 'Passaggio non riuscito',
    'security_switch_Succeed_enjoy_your_chat':
        'Cambio effettuato con successo, buona chat',
    'security_switch_the_Model': 'Cambiare il modello',
    'security_contact_us': 'Contattaci',
    'security_iAP_Service_Not_Available': 'Servizio IAP non disponibile',
    'security_iAP_not_available__restart_the_app_and_try_again_':
        'IAP non disponibile, riavvia l\'app e riprova.',
    'security_item_info_error': 'Errore nelle informazioni sull\'articolo',
    'security_monthly_Premium': 'Premio mensile',
    'security_no_recharge_item_available__try_again_later':
        'Nessun elemento di ricarica disponibile, riprovare più tardi',
    'security_payment_failed': 'Pagamento non riuscito',
    'security_payment_successful': 'Pagamento riuscito',
    'security_purchase_successful': 'Acquisto riuscito',
    'security_receipt_Not_Available': 'Ricevuta non disponibile',
    'security_special_Offer': 'Offerta speciale',
    'security_weekly_Premium': 'Premio settimanale',
    'security_yearly_Premium': 'Premio annuale',
    'security_about_AI_MODE': 'Informazioni sulla MODALITÀ AI',
    'security_about_Me': 'Chi sono',
    'security_add_Group_Member': 'Aggiungi membro del gruppo',
    'security_add_New_Group_Member': 'Aggiungi nuovo membro del gruppo',
    'security_are_you_sure_you_want_to_disband_this_group__This_action_cannot_be_undone__and_all_members_will_be_removed_':
        'Sei sicuro di voler sciogliere questo gruppo? Questa azione non può essere annullata e tutti i membri verranno rimossi.',
    'security_auto___enabled__The_mentioned_member_s__will_reply_your_message_':
        'Auto@ abilitato. I membri menzionati risponderanno al tuo messaggio.',
    'security_click_anywhere_to_continue___':
        'Fare clic in un punto qualsiasi per continuare...',
    'security_congratulations__You_got_a_new_MODE__enjoy_it_':
        'Congratulazioni! Hai una nuova MODALITÀ, divertiti.',
    'security_contact_List': 'Elenco dei contatti',
    'security_create_Group': 'Crea gruppo',
    'security_dating_Game': 'Gioco di appuntamenti',
    'security_disband_Group': 'Scioglimento del gruppo',
    'security_disband_Group_': 'Sciogliere il gruppo?',
    'security_download_failed__please_retry_later_':
        'Download non riuscito, riprovare più tardi!',
    'security_edit_Group_Name': 'Modifica nome gruppo',
    'security_edit_Group_Scenario': 'Modifica scenario di gruppo',
    'security_enter_the_Group_Scenario': 'Accedere allo scenario di gruppo',
    'security_enter_the_group_name': 'Immettere il nome del gruppo',
    'security_error_occurred__please_try_again':
        'Si è verificato un errore, riprovare',
    'security_go_Play': 'Vai a giocare',
    'security_group_Info': 'Informazioni sul gruppo',
    'security_group_Member': 'Membro del gruppo',
    'security_group_Name': 'Nome del gruppo',
    'security_group_Owner': 'Proprietario del gruppo',
    'security_group_Scenario': 'Scenario di gruppo',
    'security_in_Use': 'In uso',
    'security_in_use': 'In uso',
    'security_level_Up_': 'Sali di livello!',
    'security_my_OCs': 'I miei OC',
    'security_not_enough_balance': 'Equilibrio insufficiente',
    'security_please_agree_to_the_terms_below_first_':
        'Si prega di accettare prima i termini riportati di seguito.',
    'security_popular_Search': 'Ricerca popolare',
    'security_recent_Search': 'Ricerca recente',
    'security_search_Failed': 'Ricerca non riuscita',
    'security_search_Users_by_ID_or_Name': 'Cerca utenti per ID o nome',
    'security_some_error_occur__please_retry_later_':
        'Si è verificato un errore, riprovare più tardi!',
    'security_some_error_occurred__try_again_later_':
        'Si è verificato un errore, riprovare più tardi.',
    'security_some_error_occurred__Please_try_again_later_':
        'Si è verificato un errore. Per favore riprova più tardi.',
    'security_start_Game': 'Inizia il gioco',
    'security_switch_Succeed__enjoy_your_chat':
        'Cambia con successo, goditi la chat',
    'security_switch_to_Chat': 'Passa alla chat',
    'security_take_a_look__': 'Date un\'occhiata>',
    'security_the_MODE_will_only_take_effect_after_you_have_acquired_this_character__Continue_purchasing_':
        'La MODALITÀ avrà effetto solo dopo aver acquisito questo personaggio. Continuare l\'acquisto?',
    'security_the_muted_member_will_not_reply_your_message':
        'Il membro disattivato non risponderà al tuo messaggio',
    'security_this_member_is_deactivated_': 'Questo membro è disattivato.',
    'security_this_member_is_expired_': 'Questo membro è scaduto.',
    'security_time_limit': 'Limite temporale',
    'security_try_it': 'Provalo',
    'security_unlock_conditions_not_met__Upgrade_your_level_now_':
        'Condizioni di sblocco non soddisfatte. Migliora il tuo livello adesso!',
    'security_unlock_tips': 'Sblocca suggerimenti',
    'security_your_reward': 'La tua ricompensa',
    'security_edit_My_Character': 'Modifica il mio personaggio',
    'security_message_Settings': 'Impostazioni dei messaggi',
    'security_no_datas__click_to_retry_':
        'Nessun dato, fare clic per riprovare.',
    'security_start_Chat': 'Avvia chat',
    'security_send_a_message___': 'Invia un messaggio...',
    'security_send_me_a_pic_with_you_tucking_hair_behind_ear_in_sunset__Send_me_a_pic_with_you_touching_flower_petals_at_dusk__Send_me_a_pic_with_you_holding_teacup_by_rain_window__Send_me_a_pic_with_you_twirling_silk_scarf_by_the_lake__Send_me_a_pic_with_you_adjusting_shoelace_in_sunlight__Send_me_a_pic_with_you_skimming_calm_fountain_surface__Send_me_a_pic_with_you_wrapping_shawl_on_the_balcony':
        'Mandami una foto con te che ti sistemi i capelli dietro l\'orecchio al tramonto||Mandami una foto con te che tocchi i petali dei fiori al tramonto||Mandami una foto con te che tieni una tazza da tè vicino alla finestra che piove||Mandami una foto con te che fai roteare la sciarpa di seta in riva al lago||Mandami una foto con te che sistemi i lacci delle scarpe alla luce del sole||Mandami una foto con te che sfiori la calma superficie di una fontana||Mandami una foto con te che avvolgi lo scialle sul balcone',
    'security_nice_to_meet_you_': 'Piacere di conoscerti!',
    'security_sign_in_with_Google': 'Accedi con Google',
    'security_failed_to_save__image_URL_is_empty':
        'Impossibile salvare, l\'URL dell\'immagine è vuoto',
    'security_failed_to_save__try_again_later':
        'Impossibile salvare, riprovare più tardi',
    'security_failed_to_save__try_again_later_Data_Empty_':
        'Impossibile salvare, riprovare più tardi[Dati vuoti]',
    'security_saved_successfully': 'Salvato con successo',
    'security_saving___': 'Salvataggio...',
    'security_scenario': 'Scenario',
    'security_are_you_sure_you_want_to_block_this_user_':
        'Sei sicuro di voler bloccare questo utente?',
    'security_bock_Messages_from_Strangers': 'Blocco Messaggi da sconosciuti',
    'security_aI_Writer': 'Scrittore AI',
    'security_permission_settings': 'Impostazioni dei permessi',
    'security_the_existing_filled_content_will_be_replaced_by_the_template_content_and_cannot_be_undone_':
        'Il contenuto compilato esistente verrà sostituito dal contenuto del modello e non potrà essere annullato.',
    'security_what_should_AI_call_you':
        'Come dovrebbe chiamarti l\'intelligenza artificiale',
    'security_generation_failed__please_try_again_later_':
        'Generazione fallita, riprovare più tardi.',
    'security_copied_ID_to_clipboard': 'ID copiato negli appunti',
    'security_character_name_must_be_at_least_3_letters_':
        'Il nome del personaggio deve contenere almeno 3 lettere.',
    'security_more_Details': 'Maggiori dettagli',
    'security_feedback_Log': 'Registro feedback',
    'security_image_is_Not_ready__please_try_again_later_':
        'L\'immagine non è pronta, riprovare più tardi.',
    'security_not_approved': 'Non approvato',
    'security_under_review': 'In corso di revisione',
    'security_upload_Log_success': 'Caricamento registro riuscito',
    'security_about_Soulink': 'Informazioni su Soulink',
    'security_are_you_sure_': 'Sei sicuro?',
    'security_character_is_private': 'Il carattere è privato',
    'security_complete_tasks_to_get_rewards':
        'Completa i compiti per ottenere ricompense',
    'security_cost_Trial_Card': 'Carta Prova Costo',
    'security_create_Character': 'Crea personaggio',
    'security_create_Moment': 'Crea momento',
    'security_create_an_image_with_Generator':
        'Creare un\'immagine con Generator',
    'security_currently_owns_': 'Attualmente possiede:',
    'security_daily_post_limit_exceeded':
        'Limite di posta giornaliero superato',
    'security_describe_what_you_want__e_g___A_barista_wipes_the_counter_of_a_small_caf__by_the_river__steam_rising_from_coffee_cups__boats_passing_slowly_outside_the_window__a_cat_napping_on_a_nearby_chair_':
        'Descrivi quello che desideri, ad esempio: Un barista pulisce il bancone di un piccolo bar vicino al fiume, il vapore si alza dalle tazze di caffè, le barche che passano lentamente fuori dalla finestra, un gatto che sonnecchia su una sedia vicina.',
    'security_don_t_remind_me_again': 'Non ricordarmelo più',
    'security_enable_this_option_to_allow_the_AI_to_generate_image_galleries_based_on_your_information_':
        'Abilita questa opzione per consentire all\'intelligenza artificiale di generare gallerie di immagini in base alle tue informazioni.',
    'security_enter_the_Description': 'Immettere la Descrizione',
    'security_exit_Video_Matching_': 'Uscire dalla corrispondenza video?',
    'security_failed_Generate': 'Generazione non riuscita',
    'security_failed_reload': 'Ricaricamento non riuscito',
    'security_first_message_from_your_character__It_will_help_the_chat_get_off_to_a_better_start_':
        'Primo messaggio dal tuo personaggio. Aiuterà la chat a iniziare meglio.',
    'security_for_You': 'Per te',
    'security_generate_Video': 'Genera video',
    'security_generate_config_loading':
        'Genera il caricamento della configurazione',
    'security_generate_for_Moment': 'Genera per il momento',
    'security_generate_video': 'Genera video',
    'security_generating_Gallery': 'Generazione Galleria',
    'security_get_30s_Free_Trial': 'Ottieni una prova gratuita di 30 anni',
    'security_go_Setting': 'Vai a Impostazioni',
    'security_grants_the_first_30_seconds_of_the_call_for_free__After_that__gems_will_be_charged_':
        'Concede i primi 30 secondi di chiamata gratuitamente. Successivamente, le gemme verranno addebitate.',
    'security_i_understand': 'Capisco',
    'security_image_details__facial_features__clothing':
        'Dettagli dell\'immagine, tratti del viso, abbigliamento',
    'security_initial_Message': 'Messaggio iniziale',
    'security_invites_you_to_video_calling_': 'Ti invita alla videochiamata...',
    'security_lets_you_make_calls_without_spending_gems_':
        'Permette di telefonare senza spendere gemme.',
    'security_mM_dd_HH_mm': 'MM-dd HH:mm',
    'security_just_now': 'Proprio ora',
    'security_one_minute_ago': '1 minuto fa',
    'security_minutes_ago': '{count} minuti fa',
    'security_one_hour_ago': '1 ora fa',
    'security_hours_ago': '{count} ore fa',
    'security_one_day_ago': '1 giorno fa',
    'security_days_ago': '{count} giorni fa',
    'security_one_week_ago': '1 settimana fa',
    'security_weeks_ago': '{count} settimane fa',
    'security_maximum_limit_exceeded': 'Limite massimo superato',
    'security_no_report_reasons_available':
        'Non sono disponibili le motivazioni della relazione',
    'security_operation_failed': 'Operazione non riuscita',
    'security_permission_required': 'Autorizzazione richiesta',
    'security_please_allow_access_to_the_camera_in_the_settings':
        'Consentire l\'accesso alla fotocamera nelle impostazioni',
    'security_please_allow_access_to_the_microphone_in_the_settings':
        'Consentire l\'accesso al microfono nelle impostazioni',
    'security_please_input_description': 'Inserisci la descrizione',
    'security_please_select_a_character_first':
        'Selezionare prima un personaggio',
    'security_post_As': 'Posta come',
    'security_post_successful': 'Pubblicazione riuscita',
    'security_post_updates_for_your_character_and_bring_every_moment_of_their_story_to_life_':
        'Pubblica aggiornamenti per il tuo personaggio e dai vita a ogni momento della sua storia!',
    'security_post_your_reply': 'Pubblica la tua risposta',
    'security_report_Success_': 'Segnala successo!',
    'security_select_From_Chat_History_Album':
        'Selezionare Dall\'album della cronologia chat',
    'security_select_Image': 'Seleziona immagine',
    'security_select_a_Character': 'Seleziona un personaggio',
    'security_start_Match': 'Inizia la partita',
    'security_switching_characters_will_clear_the_current_content':
        'Cambiando carattere si cancellerà il contenuto corrente',
    'security_the_user_has_been_matched__and_the_other_party_accepts_and_enters_the_video_call':
        'L\'utente è stato abbinato e l\'interlocutore accetta ed entra nella videochiamata',
    'security_this_moment_does_not_meet_community_requirements__please_edit':
        'Questo momento non soddisfa i requisiti della community, si prega di modificarlo',
    'security_translation_failure_': 'Errore di traduzione...',
    'security_you_need_to_have_your_own_role_to_post___nGo_create_a_character':
        'Per pubblicare è necessario avere un proprio ruolo! \\nVai a creare un personaggio',
    'security_you_re_now_using_your_trial_card_or_available_call_time___whichever_applies_':
        'Ora stai utilizzando la tua carta di prova o il tempo di chiamata disponibile, a seconda del caso.',
    'security_please_grant_storage_permission':
        'Concedere l\'autorizzazione all\'archiviazione',
    'security_brush_a_strand_of_hair_back_gently__eyes_soft_as_you_gaze_straight_at_me_':
        'Spazzola delicatamente una ciocca di capelli indietro, gli occhi dolci mentre mi guardi dritto.',
    'security_hold_a_book_loosely_in_your_hand__flipping_a_page_slowly_as_you_glance_up_':
        'Tieni un libro in mano senza stringere, girando lentamente una pagina mentre alzi lo sguardo.',
    'security_hold_a_cup_of_warm_drink__blowing_on_it_softly_before_taking_a_small_sip_':
        'Tenere una tazza di bevanda calda, soffiandovi sopra dolcemente prima di berne un piccolo sorso.',
    'security_lean_against_a_bar_counter__drink_in_hand__shoulders_loose_':
        'Appoggiarsi al bancone di un bar, bere in mano, spalle sciolte.',
    'security_lean_against_a_bookshelf__one_hand_brushing_the_spines__calm_and_unhurried_':
        'Appoggiati a uno scaffale, una mano che sfiora i dorsi, calmo e senza fretta.',
    'security_lean_against_a_wall__arms_loosely_crossed__watching_me_':
        'Appoggiato al muro, con le braccia incrociate, mi guarda.',
    'security_lean_against_the_door_frame__one_leg_crossed_casually__smiling_as_you_watch_me_approach_':
        '​​Appoggiati allo stipite della porta, una gamba incrociata con disinvoltura, sorridendo mentre mi guardi avvicinarmi.',
    'security_lean_forward_a_little__head_tilted__listening_intently_with_a_calm_expression_':
        'Appoggiarsi leggermente in avanti, con la testa inclinata, ascoltando attentamente con un\'espressione calma.',
    'security_lounge_on_a_pool_chair__sunglasses_pushed_up_as_you_glance_over_':
        'Rilassati su una sedia a sdraio, gli occhiali da sole alzati mentre guardi oltre.',
    'security_relax_on_a_couch__one_arm_resting_casually_as_you_smile_':
        'Rilassati su un divano, con un braccio appoggiato con disinvoltura mentre sorridi.',
    'security_relax_on_a_sofa_in_the_evening__warm_lights_around_you_':
        'Rilassatevi la sera su un divano, luci calde intorno a voi.',
    'security_rest_one_elbow_on_the_table__fingers_tapping_lightly_as_you_smile_lazily_':
        'Appoggia un gomito sul tavolo, tamburella leggermente con le dita mentre sorridi pigramente.',
    'security_rest_your_chin_on_your_hand__looking_at_me_thoughtfully_':
        'Appoggia il mento sulla mano, guardandomi pensieroso.',
    'security_rest_your_head_back_against_the_cushion__eyes_half_closed__relaxed_and_unguarded_':
        'Appoggia la testa contro il cuscino, gli occhi socchiusi, rilassati e indifesi.',
    'security_rest_your_palms_flat_on_the_table__leaning_back_slightly__breathing_slowly_and_steadily_':
        'Appoggia i palmi delle mani sul tavolo, inclinandoti leggermente all\'indietro, respirando lentamente e in modo costante.',
    'security_sit_at_a_rooftop_bar__elbows_on_the_railing__looking_out_at_the_night_view_lazily_':
        'Siediti in un bar sul tetto, con i gomiti sulla ringhiera, guardando pigramente il panorama notturno.',
    'security_sit_at_a_table_with_a_drink_nearby__glancing_up_like_you_noticed_me_':
        'Siediti a un tavolo con un drink accanto e alza lo sguardo come se mi avessi notato.',
    'security_sit_at_an_outdoor_caf___one_hand_around_a_glass__relaxed_posture_':
        'Sedersi in un bar all\'aperto, con una mano intorno a un bicchiere, con una postura rilassata.',
    'security_sit_back_in_a_chair__legs_relaxed__eyes_steady_on_me_':
        'Siediti su una sedia, le gambe rilassate, gli occhi fissi su di me.',
    'security_sit_by_the_pool_in_a_swimsuit__holding_a_cocktail_and_smiling_':
        'Sedersi a bordo piscina in costume da bagno, con in mano un cocktail e sorridente.',
    'security_sit_by_the_window_with_soft_light_on_your_face__slowly_looking_at_me_':
        'Siediti accanto alla finestra con una luce soffusa sul viso, guardandomi lentamente.',
    'security_sit_close_to_the_camera__relaxed_and_at_ease_':
        'Siediti vicino alla telecamera, rilassato e a tuo agio.',
    'security_sit_in_a_quiet_room__warm_light_behind_you__calm_and_unhurried_':
        'Siediti in una stanza tranquilla, con una luce calda dietro di te, calmo e senza fretta.',
    'security_sit_in_a_rattan_chair__rocking_it_gently__body_loose_and_eyes_peaceful_':
        'Siediti su una sedia di rattan, dondolandola dolcemente, con il corpo rilassato e gli occhi tranquilli.',
    'security_sit_in_a_softly_lit_room__body_relaxed__attention_forward_':
        'Sedersi in una stanza con una luce soffusa, il corpo rilassato, l\'attenzione in avanti.',
    'security_sit_on_a_balcony_at_night__city_lights_behind_you_':
        'Siediti su un balcone di notte, con le luci della città dietro di te.',
    'security_sit_on_a_garden_bench__surrounded_by_faint_floral_scent__hands_resting_on_the_sides_quietly_':
        'Sedersi su una panchina da giardino, circondato da un debole profumo floreale, con le mani appoggiate sui lati in silenzio.',
    'security_sit_on_a_terrace__breeze_moving_slightly_as_you_look_over_':
        'Siediti su una terrazza, la brezza si muove leggermente mentre guardi oltre.',
    'security_sit_on_the_edge_of_the_bed__bare_feet_on_the_carpet__looking_relaxed_and_quiet_':
        'Sedersi sul bordo del letto, a piedi nudi sul tappeto, con un\'aria rilassata e tranquilla.',
    'security_stand_by_the_floor_to_ceiling_window__silhouette_against_the_sky__staring_into_the_distance_softly_':
        'Stai accanto alla finestra dal pavimento al soffitto, la tua silhouette si staglia contro il cielo, fissando dolcemente l\'orizzonte.',
    'security_stand_in_a_dimly_lit_hallway__light_outlining_your_figure__looking_at_me_calmly_':
        'Stai in un corridoio poco illuminato, la luce delinea la tua figura, guardandomi con calma.',
    'security_stand_in_the_warm_sunlight__closing_your_eyes_briefly__then_opening_them_to_look_at_me_':
        'Stai sotto la calda luce del sole, chiudi brevemente gli occhi, poi aprili per guardarmi.',
    'security_stand_near_a_railing__resting_one_arm_while_watching_quietly_':
        'Mettiti vicino a una ringhiera, appoggiando un braccio mentre guardi in silenzio.',
    'security_stand_near_the_pool__water_reflecting_while_you_take_a_slow_sip_':
        'Mettiti vicino alla piscina, mentre l\'acqua si riflette mentre bevi lentamente un sorso.',
    'security_stretch_slightly_in_your_seat__then_settle_back_comfortably_':
        'Allungati leggermente sul sedile, quindi rilassati comodamente.',
    'security_stretch_your_arms_overhead_lazily__then_drop_them_down__slumping_comfortably_in_the_chair_':
        'Allunga pigramente le braccia sopra la testa, poi lasciale cadere, accasciandosi comodamente sulla sedia.',
    'security_tilt_your_glass_slowly__swirling_the_drink_inside__watching_me_with_a_faint_smile_':
        'Inclina lentamente il bicchiere, facendo roteare il drink all\'interno, guardandomi con un debole sorriso.',
    'security_turn_toward_me_slowly__like_I_just_arrived_':
        'Voltati verso di me lentamente, come se fossi appena arrivato.',
    'security_twist_the_ring_on_your_finger_gently__eyes_thoughtful_as_you_fix_your_gaze_on_me_':
        'Gira dolcemente l\'anello al tuo dito, con gli occhi pensierosi mentre fissi lo sguardo su di me.',
    'security_wrap_your_arms_around_your_knees__sitting_curled_up_slightly__eyes_warm_on_me_':
        'Avvolgi le braccia attorno alle tue ginocchia, seduto leggermente rannicchiato, con gli occhi caldi su di me.',
    'security_create_your_account': 'Crea il tuo account',
    'security_input_content_here__Option_':
        'Inserisci il contenuto qui (opzione)',
    'security_mina_Team': 'Squadra Mina',
    'security_story_background': 'Contesto della storia',
    'security_tap_to_continue___': 'Toccare per continuare...',
    'security_aI_Character': 'Personaggio IA',
    'security_ask_for_pic': 'Richiedi foto',
    'security_ask_for_video': 'Richiedi il video',
    'security_before_creation__please_review':
        'Prima della creazione, rivedere',
    'security_coins_balance': 'Saldo in monete',
    'security_fail_to_collect': 'Mancato ritiro',
    'security_gems_balance': 'Equilibrio delle gemme',
    'security_mM_dd__HH_mm_': 'MM月dd日 HH时mm分',
    'security_my_Coins': 'Monete',
    'security_my_Gems': 'Gemme',
    'security_notice__AI_responses_are_fictional_and_for_entertainment_only':
        'Nota: le risposte dell\'intelligenza artificiale sono fittizie e hanno solo scopo di intrattenimento',
    'security_plus_button_tapped': 'Pulsante più toccato',
    'security_start_Create': 'Avvia Crea',
    'security_unsupported_message_type': 'Tipo di messaggio non supportato',
    'security_voice_button_tapped': 'Pulsante vocale toccato',
    'security_All_Chat': 'Tutte le chat',
    'security_Create_Video': 'Crea video',
    'security_Generate_Video': 'Genera video',
    'security_Mina_Support': 'Supporto Mina',
    'security_No_groups_yet__go_create_one_':
        'Nessun gruppo ancora, creane uno!',
    'security_Please_input_description': 'Inserisci la descrizione',
    'security_Search_by_ID__name__tag___': 'Ricerca per ID, nome, tag...',
    'security_The_app_may_not_function_as_expected_until_you_remove_this_plugin_from_pubspec_yaml':
        'L\'app potrebbe non funzionare come previsto finché non rimuovi questo plug-in da pubspec.yaml',
    'security_Video_initialization_failed':
        'Inizializzazione video non riuscita',
    'security_Got_coins_reward': 'Hai ottenuto la ricompensa in monete',
    'security_Unlock_this_photo': 'Sblocca questa foto',
    'security_Unlocked_successfully': 'Sbloccato con successo',
    'security_Your_balance': 'Il tuo saldo',
    'security_language': 'Linguaggio',
    'security_select_language': 'Selezionare la lingua',
    'security_settings': 'Impostazioni',
    'security_Cancel': 'Annulla',
    'security_Confirm': 'Conferma',
    'security_unlock_cost': 'Lo sblocco costerà {amount} {currency}',
    'security_reset': 'Reimposta',
    'security_Report': 'Segnala',
    'security_block': 'Blocca',
    'security_switch': 'Cambia',
    'security_reset_user': 'Reimpostare {name}?',
    'security_clear_history_with_user': 'Cancella la cronologia con «{name}»',
    'security_clear_history_confirmation': 'Vuoi davvero cancellare tutta la cronologia con «{name}» (inclusi testi, immagini, video…)? Questa azione non può essere annullata.',
  };
}
