// Generated by toolchain/translate/generate_copywriting_localizations.py.
// Edit Copywriting or the generator instead of changing keys by hand.

abstract final class CopywritingStringsFr {
  static const Map<String, String> values = <String, String>{
    'security_notifications': 'Notifications',
    'security_collections': 'Collections',
    'security_feedback': 'Commentaires',
    'security_about_her': 'À propos d\'elle',
    'security_account_Deletion': 'Suppression de compte',
    'security_add_rounds': 'Ajouter des tours',
    'security_all_Gender': 'Tous genres',
    'security_appears_exclusively_in_your_character__s_public_profile_This_biographical_information_will_not_be_utilized_in_generation_prompts_or_influence_behavioral_patterns_':
        'Apparaît exclusivement dans le profil public de votre personnage. Ces informations biographiques ne seront pas utilisées dans les invites de génération ni n\'influenceront les modèles de comportement.',
    'security_are_you_sure_you_want_to_delete_your_account_':
        'Êtes-vous sûr de vouloir supprimer votre compte ?',
    'security_are_you_sure_you_want_to_log_out_':
        'Êtes-vous sûr de vouloir vous déconnecter ?',
    'security_audio_Library': 'Bibliothèque audio',
    'security_audio_input_is_too_short_to_send_':
        'L\'entrée audio est trop courte pour être envoyée.',
    'security_avatar_upload_failed__please_try_again_later_':
        'Le téléchargement de l\'avatar a échoué, veuillez réessayer plus tard.',
    'security_avatar_uploaded': 'Avatar téléchargé',
    'security_birth_date': 'Date de naissance',
    'security_by_clicking_Security_security_Subscribe__you_will_be_charged__and_your_subscription_will_automatically_renew_at_the_same_price_and_duration_until_canceled_through_PlayStore_settings__By_proceeding__you_agree_to_our_terms_':
        'En cliquant sur Security.security_Subscribe, vous serez facturé et votre abonnement sera automatiquement renouvelé au même prix et pendant la même durée jusqu\'à son annulation via les paramètres PlayStore. En poursuivant, vous acceptez nos conditions.',
    'security_call_Duration': 'Durée de l\'appel',
    'security_cannot_get_information__please_retry_later':
        'Impossible d\'obtenir des informations, veuillez réessayer plus tard',
    'security_cannot_get_physique_details__please_retry_later':
        'Impossible d\'obtenir les détails du physique, veuillez réessayer plus tard',
    'security_cannot_open_date_picker__please_retry_later':
        'Impossible d\'ouvrir le sélecteur de date, veuillez réessayer plus tard',
    'security_click_to_add': 'Cliquez pour ajouter',
    'security_click_to_play': 'Cliquez pour jouer',
    'security_coin_balance': 'Solde des pièces',
    'security_connecting___': 'Connexion...',
    'security_copyright_Agreement': 'Accord sur les droits d\'auteur',
    'security_create_My_Character': 'Créer mon personnage',
    'security_create_Now': 'Créer maintenant',
    'security_create_an_account': 'Créer un compte',
    'security_current_device_not_support__try_restart_app_':
        'L\'appareil actuel n\'est pas pris en charge, essayez de redémarrer l\'application.',
    'security_defines_the_conversational_patterns_between_you_and_your_character__This_crucial_setting_determines_how_your_character_formulates_responses_and_maintains_personality_consistency_':
        'Définit les modèles de conversation entre vous et votre personnage. Ce paramètre crucial détermine la manière dont votre personnage formule ses réponses et maintient la cohérence de sa personnalité.',
    'security_delete_account_': 'Supprimer le compte ?',
    'security_deleting___': 'Suppression...',
    'security_describe_the_conversation_scenario_and_involved_characters_':
        'Décrivez le scénario de la conversation et les personnages impliqués.',
    'security_describe_the_issue': 'Décrivez le problème',
    'security_dialogue_Style': 'Style de dialogue',
    'security_edit_information': 'Modifier les informations',
    'security_enter_verification_code': 'Entrez le code de vérification',
    'security_entry_your_email': 'Saisissez votre email',
    'security_expires_on': 'Expire le',
    'security_failed_to_follow': 'Échec du suivi',
    'security_failed_to_load_subscription_data':
        'Échec du chargement des données d\'abonnement',
    'security_failed_to_process_subscription__please_try_again_later_':
        'Échec du traitement de l\'abonnement, veuillez réessayer plus tard.',
    'security_failed_to_record_audio__please_try_again':
        'Échec de l\'enregistrement audio, veuillez réessayer',
    'security_failed_to_send_gift': 'Échec de l\'envoi du cadeau',
    'security_failed_to_unfollow': 'Échec du désabonnement',
    'security_failed_to_update__please_retry_later':
        'Échec de la mise à jour, veuillez réessayer plus tard',
    'security_feelie_Pro': 'FeeliePro',
    'security_fill_in_your_introduction___': 'Remplissez votre introduction...',
    'security_following_the_regeneration_process__you_ll_receive_a_brand_new_image__You_are_also_welcome_to_revisit_the_images_you_created_earlier__Are_you_ready_to_move_forward_':
        'Après le processus de régénération, vous recevrez une toute nouvelle image. Vous êtes également invités à revoir les images que vous avez créées précédemment. Êtes-vous prêt à aller de l’avant ?',
    'security_for_example___On_the_moonlit_balcony_of_a_neo___Victorian_mansion__an_ethereal_woman_with_bright_blue_hime___cut_hair':
        'Par exemple, « Sur le balcon éclairé par la lune d\'un manoir néo-victorien, une femme éthérée aux cheveux coupés à l\'hime bleu vif',
    'security_gem_balance': 'Solde des gemmes',
    'security_generating_in_progress': 'Génération en cours',
    'security_generating___': 'Génération...',
    'security_get_full_access_': 'Obtenez un accès complet !',
    'security_hold_to_talk': 'Attendez pour parler',
    'security_how_would_you_like_OC_to_address_you_':
        'Comment souhaiteriez-vous qu’OC s’adresse à vous ?',
    'security_image_Prompt': 'Invite d\'image',
    'security_information_updated_': 'Informations mises à jour.',
    'security_insufficient_balance_': 'Solde insuffisant.',
    'security_interrupt_AI': 'Interrompre l\'IA',
    'security_loading___': 'Chargement...',
    'security_log_out': 'Se déconnecter',
    'security_logging_in___': 'Connexion...',
    'security_master_name_must_be_2_24_characters_in_length':
        'Le nom du maître doit comporter entre 2 et 24 caractères.',
    'security_modify_Now': 'Modifier maintenant',
    'security_name_your_character': 'Nommez votre personnage',
    'security_network_error': 'Erreur réseau',
    'security_network_error__please_try_again_later':
        'Erreur réseau, veuillez réessayer plus tard',
    'security_network_exception__please_try_again_later':
        'Exception réseau, veuillez réessayer plus tard',
    'security_no_chat_partner_has_been_initiated_yet':
        'Aucun partenaire de chat n\'a encore été initié',
    'security_no_companions_yet': 'Pas encore de compagnons',
    'security_no_data': 'Aucune donnée',
    'security_no_user_information__getting_back___':
        'Aucune information utilisateur, retour...',
    'security_notice__Everything_AI_says_is_made_up':
        'Remarque : tout ce que dit l\'IA est inventé',
    'security_obtain_code': 'Obtenir le code',
    'security_platform_not_supported_': 'Plateforme non prise en charge.',
    'security_please_agree_to_the_terms_and_conditions':
        'Veuillez accepter les termes et conditions',
    'security_please_select_a_product_to_recharge_':
        'Veuillez sélectionner un produit à recharger.',
    'security_premium_Benefits_for_Audio__unlimited':
        'Avantages Premium pour l\'audio, illimités',
    'security_prior_to_the_creation_process__please_review_our':
        'Avant le processus de création, veuillez consulter notre',
    'security_privacy_Policy': 'Politique de confidentialité',
    'security_privacy_policy': 'Politique de confidentialité',
    'security_pro_Free': 'Pro Gratuit',
    'security_pro_only': 'Professionnel uniquement',
    'security_purchase_done': 'Achat effectué',
    'security_purchased_Success': 'Succès acheté',
    'security_purchasing___': 'Achat...',
    'security_recharge_failed_': 'La recharge a échoué.',
    'security_regeneration_Tips': 'Conseils de régénération',
    'security_release_Cancel': 'Libérer Annuler',
    'security_release_Send': 'Libérer l\'envoi',
    'security_role_image': 'Image de rôle',
    'security_sF_Pro': 'SF Pro',
    'security_sF_Pro_bold': 'SF Pro bold',
    'security_select_from_gallery': 'Sélectionner dans la galerie',
    'security_select_from_the_album': 'Sélectionner dans l\'album',
    'security_selected_date_is_out_of_range_':
        'La date sélectionnée est hors plage.',
    'security_send_failed__please_try_again_later':
        'Échec de l\'envoi, veuillez réessayer plus tard',
    'security_send_message__reply_by_AI': 'Envoyer un message, réponse par AI',
    'security_sending___': 'Envoi...',
    'security_sign_in_with_Apple': 'Connectez-vous avec Apple',
    'security_sign_in_with_E_mail': 'Connectez-vous avec e-mail',
    'security_start_create': 'Commencer à créer',
    'security_submitted_successfully': 'Soumis avec succès',
    'security_supply_detailed_information_about_the_image__such_as_the_clothing_worn__facial_features__and_actions_':
        'Fournissez des informations détaillées sur l\'image, telles que les vêtements portés, les traits du visage et les actions.',
    'security_take_it_with_camera': 'Prenez-le avec l\'appareil photo',
    'security_terms_of_Service': 'Conditions d\'utilisation',
    'security_terms_of_service': 'Conditions d\'utilisation',
    'security_the_OC_will_address_you_by_the_name_you_enter_':
        'L\'OC vous appellera par le nom que vous aurez indiqué.',
    'security_the_character_creation_is_still_ongoing__Leaving_at_this_moment_will_forfeit_the_progress_made_so_far__Are_you_sure_you_want_to_go_back_':
        'La création du personnage est toujours en cours. Partir à ce moment annulera les progrès réalisés jusqu’à présent. Etes-vous sûr de vouloir y retourner ?',
    'security_the_uploaded_image_serves_as_a_reference_for_facial_features_and_style_elements':
        'L\'image téléchargée sert de référence pour les traits du visage et les éléments de style.',
    'security_turn_on_the_camera': 'Allumez l\'appareil photo',
    'security_unable_to_get_recharge_service__please_retry_later_':
        'Impossible d\'obtenir le service de recharge, veuillez réessayer plus tard.',
    'security_unknown_error__please_upload_again_':
        'Erreur inconnue, veuillez télécharger à nouveau.',
    'security_unlock_Audio': 'Déverrouiller l\'audio',
    'security_unlock_Image': 'Déverrouiller l\'image',
    'security_unlock_Video': 'Déverrouiller la vidéo',
    'security_updating_information___': 'Mise à jour des informations...',
    'security_upload_failed__please_try_again_later':
        'Échec du téléchargement, veuillez réessayer plus tard',
    'security_uploading_new_avatar___': 'Téléchargement d\'un nouvel avatar...',
    'security_you_have_muted': 'Vous avez coupé le son',
    'security_supply_detailed_information_about_the_image__such_as_the_clothing_worn__facial_features__and_actions__For_example___On_the_moonlit_balcony_of_a_neo___Victorian_mansion__an_ethereal_woman_with_bright_blue_hime___cut_hair_leans_against_the_railing__Her_khaki_backless_sweater_flutters_gently_in_the_breeze_as_she_turns_to_look_at_the_viewer_with_an_otherworldly_serenity__':
        'Fournissez des informations détaillées sur l\'image, telles que les vêtements portés, les traits du visage et les actions. Par exemple, "Sur le balcon éclairé par la lune d\'un manoir néo-victorien, une femme éthérée aux cheveux bleu vif coupés en hime s\'appuie contre la balustrade. Son pull kaki dos nu flotte doucement dans la brise alors qu\'elle se tourne pour regarder le spectateur avec une sérénité surnaturelle."',
    'security_cannot_download_source__please_try_again_later':
        'Impossible de télécharger la source, veuillez réessayer plus tard',
    'security_if_you_sign_in__you_agree_to':
        'Si vous vous connectez, vous acceptez',
    'security_send_me_a_picture': 'Envoyez-moi une photo',
    'security_send_me_a_video': 'Envoyez-moi une vidéo',
    'security_and_indicate_your_consent_': 'et indiquez votre consentement.',
    'security_consuming_props_during_call':
        'Consommer des accessoires pendant un appel',
    'security_no_more_companions_to_load_': 'Plus de compagnons à charger.',
    'security_per_minute': 'par minute',
    'security_edit': 'Modifier',
    'security_video_Call': 'Appel vidéo',
    'security_i_am_listening___': 'J\'écoute...',
    'security_i_am_thinking___': 'Je pense...',
    'security_audio_Call': 'Appel audio',
    'security_canceled_by_caller': 'Annulé par l\'appelant',
    'security_no_answer__please_try_again_later':
        'Pas de réponse, veuillez réessayer plus tard',
    'security_no_favorites_yet__go_and_follow_some_people_':
        'Pas encore de favoris, allez suivre quelques personnes !',
    'security_benefits_Usage_Detail': 'Détails de l\'utilisation des avantages',
    'security_chat_beyond_reality__role_play_without_limits':
        'Chat au-delà du réel, jeu de rôle sans limites',
    'security_please_grant_camera_permission':
        'Veuillez accorder l\'autorisation à la caméra',
    'security_please_grant_microphone_permission':
        'Veuillez accorder l\'autorisation au microphone',
    'security_unlocking_for_free_': 'Déverrouillage gratuit !',
    'security_you__re_now_a_premium_member__nYour_benefits_are_unlocked__nExplore_your_new_perks_':
        'Vous êtes désormais membre premium !\\nVos avantages sont débloqués.\\nExplorez vos nouveaux avantages !',
    'security_by_clicking_subscribe__you_will_be_charged__and_your_subscription_will_automatically_renew_at_the_same_price_and_duration_until_canceled_through_App_Store_settings__By_proceeding__you_agree_to_our_terms_':
        'En cliquant sur S\'abonner, vous serez facturé et votre abonnement sera automatiquement renouvelé au même prix et pour la même durée jusqu\'à son annulation via les paramètres de l\'App Store. En poursuivant, vous acceptez nos conditions.',
    'security_daily_Task': 'Tâche quotidienne',
    'security_premium_Only': 'Prime uniquement',
    'security_introduction': 'Introduction',
    'security_premium_Free': 'Prime gratuite',
    'security_an_error_occurred__please_try_again_later_':
        'Une erreur s\'est produite, veuillez réessayer plus tard.',
    'security_product_id_not_found__please_try_again_later':
        'L\'identifiant du produit est introuvable, veuillez réessayer plus tard',
    'security_call_wasn__t_answered': 'L\'appel n\'a pas reçu de réponse',
    'security_cancelled_by_Caller': 'Annulé par l\'appelant',
    'security_consuming_gems_during_call':
        'Consommer des gemmes pendant un appel',
    'security_ending___': 'Fin...',
    'security_free_Call': 'Appel gratuit',
    'security_not_enough_gems__please_recharge':
        'Pas assez de gemmes, veuillez recharger',
    'security_send_a_message_': 'Envoyer un message…',
    'security_free_for_first': 'Gratuit pour la première fois',
    'security_error__max_should_not_be_a_negative_number_or_zero':
        'Erreur, max ne doit pas être un nombre négatif ou zéro',
    'security_error__min_is_greater_than_or_equal_to_max':
        'Erreur, min est supérieur ou égal à max',
    'security_invites_you': 'Vous invite',
    'security_aD_Free': 'Sans publicité',
    'security_enter_your_image_prompt__e_g__A_girl__sitting_on_a_bench___':
        'Entrez votre invite d\'image, par ex. Une fille assise sur un banc...',
    'security_failed_to_grant_coin__Please_try_again_later_':
        'Échec de l\'octroi de pièces. Veuillez réessayer plus tard.',
    'security_failed_to_unlock_resource__Please_try_again_later_':
        'Échec du déverrouillage de la ressource. Veuillez réessayer plus tard.',
    'security_image_prompt_cannot_be_empty':
        'L\'invite d\'image ne peut pas être vide',
    'security_images_you_like': 'Images que vous aimez',
    'security_please_select_at_least_one_prompt':
        'Veuillez sélectionner au moins une invite',
    'security_signing_in___': 'Connexion...',
    'security_all_Chat': 'Tous les chats',
    'security_chat_Models': 'Modèles de discussion',
    'security_chat_Now': 'Discutez maintenant',
    'security_clear_Chat_History': 'Effacer l\'historique des discussions',
    'security_connect_with_everyone_in_one_place':
        'Connectez-vous avec tout le monde en un seul endroit',
    'security_contact_us_for_support_':
        'Contactez-nous pour obtenir de l\'aide.',
    'security_delete_Message': 'Supprimer le message',
    'security_design_your_own_unique_character_and_bring_it_to_life_':
        'Créez votre propre personnage unique et donnez-lui vie.',
    'security_group_Chat': 'Discussion de groupe',
    'security_limited_Free': 'Gratuit Limité',
    'security_mark_all_as_read': 'Marquer tout comme lu',
    'security_message_Setting': 'Paramètres des messages',
    'security_message_setting': 'Paramétrage des messages',
    'security_reset_Success_': 'Réinitialisation réussie !',
    'security_rewind_to_here': 'Revenir ici',
    'security_she_will_forget_conversation_history_with_you_':
        'Elle oubliera l\'historique des conversations avec vous !',
    'security_shield_Real__s_Messages': 'Messages de Shield Real',
    'security_soulink_Team': 'Équipe Soulink',
    'security_switch_Failed': 'Échec du commutateur',
    'security_switch_Succeed_enjoy_your_chat':
        'Changement réussi, profitez de votre conversation',
    'security_switch_the_Model': 'Changer de modèle',
    'security_contact_us': 'Contactez-nous',
    'security_iAP_Service_Not_Available': 'Service IAP non disponible',
    'security_iAP_not_available__restart_the_app_and_try_again_':
        'IAP non disponible, redémarrez l\'application et réessayez.',
    'security_item_info_error': 'Erreur d\'informations sur l\'article',
    'security_monthly_Premium': 'Prime mensuelle',
    'security_no_recharge_item_available__try_again_later':
        'Aucun élément de recharge disponible, réessayez plus tard',
    'security_payment_failed': 'Échec du paiement',
    'security_payment_successful': 'Paiement réussi',
    'security_purchase_successful': 'Achat réussi',
    'security_receipt_Not_Available': 'Reçu non disponible',
    'security_special_Offer': 'Offre spéciale',
    'security_weekly_Premium': 'Prime hebdomadaire',
    'security_yearly_Premium': 'Prime annuelle',
    'security_about_AI_MODE': 'À propos du MODE IA',
    'security_about_Me': 'À propos de moi',
    'security_add_Group_Member': 'Ajouter un membre du groupe',
    'security_add_New_Group_Member': 'Ajouter un nouveau membre du groupe',
    'security_are_you_sure_you_want_to_disband_this_group__This_action_cannot_be_undone__and_all_members_will_be_removed_':
        'Êtes-vous sûr de vouloir dissoudre ce groupe ? Cette action ne peut pas être annulée et tous les membres seront supprimés.',
    'security_auto___enabled__The_mentioned_member_s__will_reply_your_message_':
        'Auto @ activé. Le(s) membre(s) mentionné(s) répondront à votre message.',
    'security_click_anywhere_to_continue___':
        'Cliquez n\'importe où pour continuer...',
    'security_congratulations__You_got_a_new_MODE__enjoy_it_':
        'Félicitations ! Vous avez un nouveau MODE, profitez-en.',
    'security_contact_List': 'Liste de contacts',
    'security_create_Group': 'Créer un groupe',
    'security_dating_Game': 'Jeu de rencontres',
    'security_disband_Group': 'Dissoudre le groupe',
    'security_disband_Group_': 'Dissoudre le groupe ?',
    'security_download_failed__please_retry_later_':
        'Échec du téléchargement, veuillez réessayer plus tard !',
    'security_edit_Group_Name': 'Modifier le nom du groupe',
    'security_edit_Group_Scenario': 'Modifier le scénario de groupe',
    'security_enter_the_Group_Scenario': 'Entrez dans le scénario de groupe',
    'security_enter_the_group_name': 'Entrez le nom du groupe',
    'security_error_occurred__please_try_again':
        'Une erreur s\'est produite, veuillez réessayer',
    'security_go_Play': 'Allez jouer',
    'security_group_Info': 'Informations sur le groupe',
    'security_group_Member': 'Membre du groupe',
    'security_group_Name': 'Nom du groupe',
    'security_group_Owner': 'Propriétaire du groupe',
    'security_group_Scenario': 'Scénario de groupe',
    'security_in_Use': 'En cours d\'utilisation',
    'security_in_use': 'En cours d\'utilisation',
    'security_level_Up_': 'Montez de niveau !',
    'security_my_OCs': 'Mes OC',
    'security_not_enough_balance': 'Pas assez d\'équilibre',
    'security_please_agree_to_the_terms_below_first_':
        'Veuillez d\'abord accepter les conditions ci-dessous.',
    'security_popular_Search': 'Recherche populaire',
    'security_recent_Search': 'Recherche récente',
    'security_search_Failed': 'Échec de la recherche',
    'security_search_Users_by_ID_or_Name':
        'Rechercher des utilisateurs par identifiant ou par nom',
    'security_some_error_occur__please_retry_later_':
        'Une erreur s\'est produite, veuillez réessayer plus tard !',
    'security_some_error_occurred__try_again_later_':
        'Une erreur s\'est produite, réessayez plus tard.',
    'security_some_error_occurred__Please_try_again_later_':
        'Une erreur s\'est produite. Veuillez réessayer plus tard.',
    'security_start_Game': 'Commencer la partie',
    'security_switch_Succeed__enjoy_your_chat':
        'Switch Succeed, profitez de votre conversation',
    'security_switch_to_Chat': 'Passer au chat',
    'security_take_a_look__': 'Jetez un oeil >',
    'security_the_MODE_will_only_take_effect_after_you_have_acquired_this_character__Continue_purchasing_':
        'Le MODE ne prendra effet qu\'après avoir acquis ce personnage. Continuer vos achats ?',
    'security_the_muted_member_will_not_reply_your_message':
        'Le membre mis en sourdine ne répondra pas à votre message',
    'security_this_member_is_deactivated_': 'Ce membre est désactivé.',
    'security_this_member_is_expired_': 'Ce membre est expiré.',
    'security_time_limit': 'Délai',
    'security_try_it': 'Essayez-le',
    'security_unlock_conditions_not_met__Upgrade_your_level_now_':
        'Conditions de déverrouillage non remplies. Améliorez votre niveau maintenant !',
    'security_unlock_tips': 'Astuces pour débloquer',
    'security_your_reward': 'Votre récompense',
    'security_edit_My_Character': 'Modifier mon personnage',
    'security_message_Settings': 'Paramètres des messages',
    'security_no_datas__click_to_retry_':
        'Aucune donnée, cliquez pour réessayer.',
    'security_start_Chat': 'Démarrer la discussion',
    'security_send_a_message___': 'Envoyer un message...',
    'security_send_me_a_pic_with_you_tucking_hair_behind_ear_in_sunset__Send_me_a_pic_with_you_touching_flower_petals_at_dusk__Send_me_a_pic_with_you_holding_teacup_by_rain_window__Send_me_a_pic_with_you_twirling_silk_scarf_by_the_lake__Send_me_a_pic_with_you_adjusting_shoelace_in_sunlight__Send_me_a_pic_with_you_skimming_calm_fountain_surface__Send_me_a_pic_with_you_wrapping_shawl_on_the_balcony':
        'Envoyez-moi une photo de vous mettant vos cheveux derrière l\'oreille au coucher du soleil ||Envoyez-moi une photo de vous touchant des pétales de fleurs au crépuscule||Envoyez-moi une photo de vous tenant une tasse de thé près de la fenêtre de pluie||Envoyez-moi une photo de votre foulard en soie virevoltant au bord du lac||Envoyez-moi une photo de vous ajustant vos lacets au soleil||Envoyez-moi une photo de vous effleurant la surface calme de la fontaine||Envoyez-moi une photo de vous enveloppant un châle sur le balcon',
    'security_nice_to_meet_you_': 'Enchanté de vous rencontrer !',
    'security_sign_in_with_Google': 'Connectez-vous avec Google',
    'security_failed_to_save__image_URL_is_empty':
        'Échec de l\'enregistrement, l\'URL de l\'image est vide',
    'security_failed_to_save__try_again_later':
        'Échec de l\'enregistrement, réessayez plus tard',
    'security_failed_to_save__try_again_later_Data_Empty_':
        'Échec de l\'enregistrement, réessayez plus tard [Données vides]',
    'security_saved_successfully': 'Enregistré avec succès',
    'security_saving___': 'Sauvegarde...',
    'security_scenario': 'Scénario',
    'security_are_you_sure_you_want_to_block_this_user_':
        'Êtes-vous sûr de vouloir bloquer cet utilisateur ?',
    'security_bock_Messages_from_Strangers': 'Messages Bock d\'étrangers',
    'security_aI_Writer': 'Écrivain IA',
    'security_permission_settings': 'Paramètres d\'autorisation',
    'security_the_existing_filled_content_will_be_replaced_by_the_template_content_and_cannot_be_undone_':
        'Le contenu rempli existant sera remplacé par le contenu du modèle et ne pourra pas être annulé.',
    'security_what_should_AI_call_you':
        'Comment l\'IA devrait-elle vous appeler',
    'security_generation_failed__please_try_again_later_':
        'La génération a échoué, veuillez réessayer plus tard.',
    'security_copied_ID_to_clipboard': 'ID copié dans le presse-papiers',
    'security_character_name_must_be_at_least_3_letters_':
        'Le nom du personnage doit contenir au moins 3 lettres.',
    'security_more_Details': 'Plus de détails',
    'security_feedback_Log': 'Journal de commentaires',
    'security_image_is_Not_ready__please_try_again_later_':
        'L\'image n\'est pas prête, veuillez réessayer plus tard.',
    'security_not_approved': 'Non approuvé',
    'security_under_review': 'En cours de révision',
    'security_upload_Log_success': 'Réussite du téléchargement du journal',
    'security_about_Soulink': 'À propos de Soulink',
    'security_are_you_sure_': 'Etes-vous sûr ?',
    'security_character_is_private': 'Le personnage est privé',
    'security_complete_tasks_to_get_rewards':
        'Terminez des tâches pour obtenir des récompenses',
    'security_cost_Trial_Card': 'Carte d\'essai de coût',
    'security_create_Character': 'Créer un personnage',
    'security_create_Moment': 'Créer un moment',
    'security_create_an_image_with_Generator': 'Créer une image avec Generator',
    'security_currently_owns_': 'Possède actuellement :',
    'security_daily_post_limit_exceeded':
        'Limite de publication quotidienne dépassée',
    'security_describe_what_you_want__e_g___A_barista_wipes_the_counter_of_a_small_caf__by_the_river__steam_rising_from_coffee_cups__boats_passing_slowly_outside_the_window__a_cat_napping_on_a_nearby_chair_':
        'Décrivez ce que vous voulez, par exemple, un barista essuie le comptoir d\'un petit café au bord de la rivière, de la vapeur s\'échappant des tasses à café, des bateaux passant lentement devant la fenêtre, un chat faisant la sieste sur une chaise à proximité.',
    'security_don_t_remind_me_again': 'Ne me le rappelle plus',
    'security_enable_this_option_to_allow_the_AI_to_generate_image_galleries_based_on_your_information_':
        'Activez cette option pour permettre à l\'IA de générer des galeries d\'images basées sur vos informations.',
    'security_enter_the_Description': 'Entrez la description',
    'security_exit_Video_Matching_': 'Quitter la correspondance vidéo ?',
    'security_failed_Generate': 'Échec de la génération',
    'security_failed_reload': 'Échec du rechargement',
    'security_first_message_from_your_character__It_will_help_the_chat_get_off_to_a_better_start_':
        'Premier message de votre personnage. Cela aidera le chat à mieux démarrer.',
    'security_for_You': 'Pour vous',
    'security_generate_Video': 'Générer une vidéo',
    'security_generate_config_loading':
        'Générer le chargement de la configuration',
    'security_generate_for_Moment': 'Générer pour un moment',
    'security_generate_video': 'Générer une vidéo',
    'security_generating_Gallery': 'Génération de galerie',
    'security_get_30s_Free_Trial': 'Obtenez un essai gratuit de 30 s',
    'security_go_Setting': 'Aller au réglage',
    'security_grants_the_first_30_seconds_of_the_call_for_free__After_that__gems_will_be_charged_':
        'Accorde gratuitement les 30 premières secondes de l\'appel. Après cela, les gemmes seront facturées.',
    'security_i_understand': 'Je comprends',
    'security_image_details__facial_features__clothing':
        'Détails de l\'image, traits du visage, vêtements',
    'security_initial_Message': 'Message initial',
    'security_invites_you_to_video_calling_': 'Vous invite à un appel vidéo…',
    'security_lets_you_make_calls_without_spending_gems_':
        'Vous permet de passer des appels sans dépenser de pierres précieuses.',
    'security_mM_dd_HH_mm': 'MM-dd HH:mm',
    'security_just_now': "À l'instant",
    'security_one_minute_ago': 'Il y a 1 minute',
    'security_minutes_ago': 'Il y a {count} minutes',
    'security_one_hour_ago': 'Il y a 1 heure',
    'security_hours_ago': 'Il y a {count} heures',
    'security_one_day_ago': 'Il y a 1 jour',
    'security_days_ago': 'Il y a {count} jours',
    'security_one_week_ago': 'Il y a 1 semaine',
    'security_weeks_ago': 'Il y a {count} semaines',
    'security_maximum_limit_exceeded': 'Limite maximale dépassée',
    'security_no_report_reasons_available': 'Aucun motif de rapport disponible',
    'security_operation_failed': 'L\'opération a échoué',
    'security_permission_required': 'Autorisation requise',
    'security_please_allow_access_to_the_camera_in_the_settings':
        'Veuillez autoriser l\'accès à la caméra dans les paramètres',
    'security_please_allow_access_to_the_microphone_in_the_settings':
        'Veuillez autoriser l\'accès au microphone dans les paramètres',
    'security_please_input_description': 'Veuillez saisir une description',
    'security_please_select_a_character_first':
        'Veuillez d\'abord sélectionner un personnage',
    'security_post_As': 'Publier en tant que',
    'security_post_successful': 'Publication réussie',
    'security_post_updates_for_your_character_and_bring_every_moment_of_their_story_to_life_':
        'Publiez des mises à jour pour votre personnage et donnez vie à chaque instant de son histoire !',
    'security_post_your_reply': 'Postez votre réponse',
    'security_report_Success_': 'Rapport de réussite !',
    'security_select_From_Chat_History_Album':
        'Sélectionner dans l\'album de l\'historique des discussions',
    'security_select_Image': 'Sélectionner une image',
    'security_select_a_Character': 'Sélectionnez un personnage',
    'security_start_Match': 'Commencer le match',
    'security_switching_characters_will_clear_the_current_content':
        'Changer de caractère effacera le contenu actuel',
    'security_the_user_has_been_matched__and_the_other_party_accepts_and_enters_the_video_call':
        'L\'utilisateur a été mis en correspondance et l\'autre partie accepte et participe à l\'appel vidéo.',
    'security_this_moment_does_not_meet_community_requirements__please_edit':
        'Ce moment ne répond pas aux exigences de la communauté, veuillez modifier',
    'security_translation_failure_': 'Échec de la traduction…',
    'security_you_need_to_have_your_own_role_to_post___nGo_create_a_character':
        'Vous devez avoir votre propre rôle pour publier ! \\nAllez créer un personnage',
    'security_you_re_now_using_your_trial_card_or_available_call_time___whichever_applies_':
        'Vous utilisez maintenant votre carte d\'essai ou le temps d\'appel disponible, selon le cas.',
    'security_please_grant_storage_permission':
        'Veuillez accorder l\'autorisation de stockage',
    'security_brush_a_strand_of_hair_back_gently__eyes_soft_as_you_gaze_straight_at_me_':
        'Repoussez doucement une mèche de cheveux en arrière, les yeux doux pendant que vous me regardez droit dans les yeux.',
    'security_hold_a_book_loosely_in_your_hand__flipping_a_page_slowly_as_you_glance_up_':
        'Tenez un livre sans serrer dans votre main, en tournant lentement une page tout en levant les yeux.',
    'security_hold_a_cup_of_warm_drink__blowing_on_it_softly_before_taking_a_small_sip_':
        'Tenez une tasse de boisson chaude en soufflant doucement dessus avant d\'en prendre une petite gorgée.',
    'security_lean_against_a_bar_counter__drink_in_hand__shoulders_loose_':
        'Appuyez-vous contre un comptoir de bar, verre à la main, épaules relâchées.',
    'security_lean_against_a_bookshelf__one_hand_brushing_the_spines__calm_and_unhurried_':
        'Appuyez-vous contre une étagère, une main effleurant le dos, calme et sans hâte.',
    'security_lean_against_a_wall__arms_loosely_crossed__watching_me_':
        'Appuyez-vous contre un mur, les bras légèrement croisés, et me regardez.',
    'security_lean_against_the_door_frame__one_leg_crossed_casually__smiling_as_you_watch_me_approach_':
        '​​Appuyez-vous contre le cadre de la porte, une jambe croisée avec désinvolture, souriant en me regardant approcher.',
    'security_lean_forward_a_little__head_tilted__listening_intently_with_a_calm_expression_':
        'Penchez-vous un peu en avant, la tête penchée, écoutant attentivement avec une expression calme.',
    'security_lounge_on_a_pool_chair__sunglasses_pushed_up_as_you_glance_over_':
        'Détendez-vous sur une chaise de piscine, lunettes de soleil relevées tandis que vous regardez par-dessus.',
    'security_relax_on_a_couch__one_arm_resting_casually_as_you_smile_':
        'Détendez-vous sur un canapé, un bras posé avec désinvolture pendant que vous souriez.',
    'security_relax_on_a_sofa_in_the_evening__warm_lights_around_you_':
        'Détendez-vous sur un canapé le soir, des lumières chaudes autour de vous.',
    'security_rest_one_elbow_on_the_table__fingers_tapping_lightly_as_you_smile_lazily_':
        'Posez un coude sur la table, tapotez légèrement avec vos doigts tout en souriant paresseusement.',
    'security_rest_your_chin_on_your_hand__looking_at_me_thoughtfully_':
        'Pose ton menton sur ta main, en me regardant pensivement.',
    'security_rest_your_head_back_against_the_cushion__eyes_half_closed__relaxed_and_unguarded_':
        'Posez votre tête en arrière contre le coussin, les yeux mi-clos, détendus et sans surveillance.',
    'security_rest_your_palms_flat_on_the_table__leaning_back_slightly__breathing_slowly_and_steadily_':
        'Posez vos paumes à plat sur la table, en vous penchant légèrement en arrière, en respirant lentement et régulièrement.',
    'security_sit_at_a_rooftop_bar__elbows_on_the_railing__looking_out_at_the_night_view_lazily_':
        'Asseyez-vous devant un bar sur le toit, les coudes sur la balustrade, regardant paresseusement la vue nocturne.',
    'security_sit_at_a_table_with_a_drink_nearby__glancing_up_like_you_noticed_me_':
        'Asseyez-vous à une table avec un verre à proximité, en levant les yeux comme si vous m\'aviez remarqué.',
    'security_sit_at_an_outdoor_caf___one_hand_around_a_glass__relaxed_posture_':
        'Asseyez-vous à la terrasse d\'un café, une main autour d\'un verre, dans une posture détendue.',
    'security_sit_back_in_a_chair__legs_relaxed__eyes_steady_on_me_':
        'Asseyez-vous sur une chaise, les jambes détendues, les yeux fixés sur moi.',
    'security_sit_by_the_pool_in_a_swimsuit__holding_a_cocktail_and_smiling_':
        'Asseyez-vous au bord de la piscine en maillot de bain, tenant un cocktail et souriant.',
    'security_sit_by_the_window_with_soft_light_on_your_face__slowly_looking_at_me_':
        'Asseyez-vous près de la fenêtre avec une douce lumière sur votre visage, en me regardant lentement.',
    'security_sit_close_to_the_camera__relaxed_and_at_ease_':
        'Asseyez-vous près de la caméra, détendu et à l\'aise.',
    'security_sit_in_a_quiet_room__warm_light_behind_you__calm_and_unhurried_':
        'Asseyez-vous dans une pièce calme, une lumière chaude derrière vous, calme et sans hâte.',
    'security_sit_in_a_rattan_chair__rocking_it_gently__body_loose_and_eyes_peaceful_':
        'Asseyez-vous sur une chaise en rotin, balancez-la doucement, le corps détendu et les yeux paisibles.',
    'security_sit_in_a_softly_lit_room__body_relaxed__attention_forward_':
        'Asseyez-vous dans une pièce faiblement éclairée, le corps détendu, l\'attention tournée vers l\'avant.',
    'security_sit_on_a_balcony_at_night__city_lights_behind_you_':
        'Asseyez-vous sur un balcon la nuit, les lumières de la ville derrière vous.',
    'security_sit_on_a_garden_bench__surrounded_by_faint_floral_scent__hands_resting_on_the_sides_quietly_':
        'Asseyez-vous sur un banc de jardin, entouré d\'un léger parfum floral, les mains posées tranquillement sur les côtés.',
    'security_sit_on_a_terrace__breeze_moving_slightly_as_you_look_over_':
        'Asseyez-vous sur une terrasse, la brise bougeant légèrement lorsque vous regardez.',
    'security_sit_on_the_edge_of_the_bed__bare_feet_on_the_carpet__looking_relaxed_and_quiet_':
        'Asseyez-vous sur le bord du lit, pieds nus sur le tapis, l\'air détendu et calme.',
    'security_stand_by_the_floor_to_ceiling_window__silhouette_against_the_sky__staring_into_the_distance_softly_':
        'Tenez-vous près de la baie vitrée, silhouette sur le ciel, regardant doucement au loin.',
    'security_stand_in_a_dimly_lit_hallway__light_outlining_your_figure__looking_at_me_calmly_':
        'Tenez-vous dans un couloir faiblement éclairé, la lumière soulignant votre silhouette, et me regardez calmement.',
    'security_stand_in_the_warm_sunlight__closing_your_eyes_briefly__then_opening_them_to_look_at_me_':
        'Tenez-vous au chaud soleil, fermez brièvement les yeux, puis ouvrez-les pour me regarder.',
    'security_stand_near_a_railing__resting_one_arm_while_watching_quietly_':
        'Tenez-vous près d\'une balustrade, posant un bras tout en regardant tranquillement.',
    'security_stand_near_the_pool__water_reflecting_while_you_take_a_slow_sip_':
        'Tenez-vous près de la piscine, l\'eau se reflétant pendant que vous prenez une lente gorgée.',
    'security_stretch_slightly_in_your_seat__then_settle_back_comfortably_':
        'Étirez-vous légèrement sur votre siège, puis installez-vous confortablement.',
    'security_stretch_your_arms_overhead_lazily__then_drop_them_down__slumping_comfortably_in_the_chair_':
        'Étirez paresseusement vos bras au-dessus de votre tête, puis laissez-les tomber, vous affalant confortablement sur la chaise.',
    'security_tilt_your_glass_slowly__swirling_the_drink_inside__watching_me_with_a_faint_smile_':
        'Inclinez lentement votre verre, faites tourner la boisson à l\'intérieur, en me regardant avec un léger sourire.',
    'security_turn_toward_me_slowly__like_I_just_arrived_':
        'Tournez-vous lentement vers moi, comme si je venais d\'arriver.',
    'security_twist_the_ring_on_your_finger_gently__eyes_thoughtful_as_you_fix_your_gaze_on_me_':
        'Tournez doucement la bague à votre doigt, les yeux pensifs pendant que vous fixez votre regard sur moi.',
    'security_wrap_your_arms_around_your_knees__sitting_curled_up_slightly__eyes_warm_on_me_':
        'Enroulez vos bras autour de vos genoux, assis légèrement recroquevillé, les yeux chaleureux sur moi.',
    'security_create_your_account': 'Créez votre compte',
    'security_input_content_here__Option_': 'Saisissez le contenu ici (Option)',
    'security_mina_Team': 'L\'équipe Mina',
    'security_story_background': 'Contexte de l\'histoire',
    'security_tap_to_continue___': 'Appuyez pour continuer...',
    'security_aI_Character': 'Personnage IA',
    'security_ask_for_pic': 'Demander une photo',
    'security_ask_for_video': 'Demander une vidéo',
    'security_before_creation__please_review':
        'Avant la création, veuillez consulter',
    'security_coins_balance': 'Solde des pièces',
    'security_fail_to_collect': 'Échec de la collecte',
    'security_gems_balance': 'Solde des gemmes',
    'security_mM_dd__HH_mm_': 'MM月dd日 HH时mm分',
    'security_my_Coins': 'Pièces',
    'security_my_Gems': 'Gemmes',
    'security_notice__AI_responses_are_fictional_and_for_entertainment_only':
        'Remarque : les réponses de l\'IA sont fictives et destinées uniquement au divertissement.',
    'security_plus_button_tapped': 'Touche Plus enfoncée',
    'security_start_Create': 'Démarrer la création',
    'security_unsupported_message_type': 'Type de message non pris en charge',
    'security_voice_button_tapped': 'Touche vocale enfoncée',
    'security_All_Chat': 'Tous les chats',
    'security_Create_Video': 'Créer une vidéo',
    'security_Generate_Video': 'Générer une vidéo',
    'security_Mina_Support': 'Assistance Mina',
    'security_No_groups_yet__go_create_one_':
        'Pas encore de groupe, allez en créer un !',
    'security_Please_input_description': 'Veuillez saisir une description',
    'security_Search_by_ID__name__tag___':
        'Recherche par identifiant, nom, tag...',
    'security_The_app_may_not_function_as_expected_until_you_remove_this_plugin_from_pubspec_yaml':
        'L\'application peut ne pas fonctionner comme prévu jusqu\'à ce que vous supprimiez ce plugin de pubspec.yaml',
    'security_Video_initialization_failed':
        'L\'initialisation de la vidéo a échoué',
    'security_Got_coins_reward': 'Vous avez reçu une récompense en pièces',
    'security_Unlock_this_photo': 'Débloquez cette photo',
    'security_Unlocked_successfully': 'Débloqué avec succès',
    'security_Your_balance': 'Votre solde',
    'security_language': 'Langue',
    'security_select_language': 'Sélectionner la langue',
    'security_settings': 'Paramètres',
    'security_Cancel': 'Annuler',
    'security_Confirm': 'Confirmer',
    'security_unlock_cost': 'Le déverrouillage coûtera {amount} {currency}',
    'security_reset': 'Réinitialiser',
    'security_Report': 'Signaler',
    'security_block': 'Bloquer',
    'security_switch': 'Changer',
    'security_reset_user': 'Réinitialiser {name} ?',
    'security_clear_history_with_user': 'Effacer l’historique avec « {name} »',
    'security_clear_history_confirmation': 'Voulez-vous vraiment effacer tout l’historique avec « {name} » (textes, images, vidéos…) ? Cette action est irréversible.',
  };
}
